# Generated by Django 5.0.1 on 2025-10-31 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile Picture')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('marketing_emails', models.BooleanField(default=False, verbose_name='Marketing Emails')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS Notifications')),
                ('show_email', models.BooleanField(default=False, verbose_name='Show Email on Profile')),
                ('show_phone', models.BooleanField(default=True, verbose_name='Show Phone on Listings')),
                ('public_profile', models.BooleanField(default=True, verbose_name='Public Profile')),
                ('show_location_map', models.BooleanField(default=True, help_text='Display your listing locations on Google Maps', verbose_name='Show Location on Map')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
