# Generated by Django 5.0.1 on 2026-03-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='Lithuania', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='House Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number_secondary',
            field=models.CharField(blank=True, max_length=20, verbose_name='Secondary Phone Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Street'),
        ),
    ]
