# Generated by Django 5.0.1 on 2026-03-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_city_profile_country_profile_house_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_messages',
            field=models.BooleanField(default=True, verbose_name='Email Messages Notifications'),
        ),
    ]
