# Generated by Django 5.0.1 on 2026-03-31 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_email_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Company Description'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/', verbose_name='Company Logo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating_count',
            field=models.IntegerField(default=0, verbose_name='Rating Count'),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_type',
            field=models.CharField(choices=[('private', 'Private Seller'), ('dealer', 'Car Dealer / Autohouse')], default='private', max_length=20, verbose_name='Seller Type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Review',
                'verbose_name_plural': 'Seller Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('reviewer', 'seller')},
            },
        ),
    ]
