# Generated by Django 5.0.1 on 2026-03-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_company_description_profile_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='Working Hours'),
        ),
    ]
