# Generated by Django 5.0.1 on 2026-05-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_wallettransaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('private', 'Private'), ('dealer', 'Dealer')], default='private', max_length=10, verbose_name='Account type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dealer_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='dealer_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dealer_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dealer_company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='dealer_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dealer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='dealer_logos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dealer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='dealer_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='none', max_length=10, verbose_name='Dealer status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dealer_subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='dealer_subscription_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='private_subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='private_subscription_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
