# Generated by Django 5.0.1 on 2026-05-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_account_type_profile_dealer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('private', 'Private seller'), ('dealer', 'Dealer')], default='private', max_length=10, verbose_name='Account type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dealer_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=10, verbose_name='Dealer status'),
        ),
    ]
