# Generated by Django 5.0.1 on 2026-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('lt', 'Lietuvių'), ('lv', 'Latviešu'), ('et', 'Eesti'), ('pl', 'Polski'), ('de', 'Deutsch'), ('ru', 'Русский'), ('fr', 'Français')], default='en', max_length=5, verbose_name='Preferred Language'),
        ),
    ]
