# Generated by Django 5.0.1 on 2026-05-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('lt', 'Lietuvių'), ('lv', 'Latviešu'), ('et', 'Eesti'), ('pl', 'Polski'), ('de', 'Deutsch'), ('ru', 'Русский'), ('fr', 'Français')], default='en', max_length=10, verbose_name='Preferred Language'),
        ),
    ]
