# Generated by Django 5.0.1 on 2026-05-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dealer_working_hours',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"mon": {"open": "09:00", "close": "18:00", "closed": false}, ...}', verbose_name='Dealer working hours'),
        ),
    ]
