# Generated by Django 5.0.1 on 2026-08-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_dealer_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='price_drop_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='price_drop_onsite',
            field=models.BooleanField(default=True),
        ),
    ]
