# Generated by Django 5.0.1 on 2026-08-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_pranesimai_apie_kainos_kritima'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signup_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='signup_user_agent',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
