# Generated by Django 5.0.1 on 2026-08-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_signup_ip_profile_signup_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tapatybe_patvirtinta',
            field=models.BooleanField(default=False, verbose_name='Tapatybė patvirtinta'),
        ),
    ]
