# Generated by Django 5.0.1 on 2026-10-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_tapatybe_patvirtinta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_aktyvavimo_priminimai',
            field=models.BooleanField(default=True, verbose_name='Priminimai aktyvuoti neaktyvuotą skelbimą'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_apie_skelbimus_isjungta',
            field=models.BooleanField(default=False, verbose_name='Nesiųsti jokių laiškų apie mano skelbimus'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_galiojimas',
            field=models.BooleanField(default=True, verbose_name='Pranešimai apie skelbimo galiojimo pabaigą'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_susidomejimas',
            field=models.BooleanField(default=True, verbose_name='Pranešimai apie skelbimo peržiūras ir susidomėjimą'),
        ),
    ]
