# Generated by Django 5.0.1 on 2026-10-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_laisku_apie_skelbimus_nustatymai'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gali_matyti_pokalbius',
            field=models.BooleanField(default=False, verbose_name='Gali peržiūrėti pokalbius (ginčams)'),
        ),
    ]
