# apps/listings/translatable_db.py
# ═══════════════════════════════════════════════════════════
# DB reikšmės (VehicleType.name, SubCategory.name), kurias reikia versti.
#
# Šis failas niekur neimportuojamas — egzistuoja tik tam, kad
# makemessages surinktų šiuos stringus į .po failus. Rodymo metu
# jie verčiami per {{ value|tdb }} filtrą (templatetags/i18n_db.py)
# arba gettext() view'e (pvz. get_subcategories_ajax).
# ═══════════════════════════════════════════════════════════

from django.utils.translation import gettext_lazy as _


VEHICLE_TYPE_NAMES = [
    _('Cars'), _('Minibuses, Buses & Campers'), _('Motorcycles & Moto Gear'),
    _('Trucks & Commercial'), _('Parts'), _('Tyres & Wheels'),
    _('Boats & Water Transport'), _('Trailers & Semi-trailers'),
    _('Construction & Warehouse Equipment'), _('Agricultural & Forestry'),
    _('Bicycles & Scooters'), _('Services'), _('Car Rental'), _('Planes & Aircraft'),
    _('Aircraft Parts'), _('Vilkikai'), _('Autotraukiniai, autovežiai'),
    _('Komunalinio ūkio transportas'), _('Krovimo ir sandėliavimo technika'),
    _('Automobilių supirkimas'), _('Video, audio, navigacijos'), _('Miško ūkio technika'),
    _('Turistiniai nameliai'),
]

# Kategorijų medžio suvienodinimas — naujos subkategorijos (0058 migracija).
# LT yra šaltinio kalba, todėl msgid = rodomas tekstas.
CATEGORY_TREE_NAMES = [
    _('Komunalinio ūkio transportas'),
    _('Žemės ūkio, spec. dalys'),
    _('Aksesuarai, Tuning'),
    _('Automobilių nuoma'),
    _('Mikroautobusų, turistinio, vandens tr. nuoma'),
    _('Statybinė technika'),
]

SUBCATEGORY_NAMES = [
    _('Aircraft Accessories'), _('Airplanes'), _('Avionics'), _('Balers'), _('Bicycles'),
    _('Boat Trailers'), _('Boats'), _('Body Repair'), _('Bulldozers'), _('Buses'),
    _('Campers'), _('Car Parts'), _('Car Service'), _('Car Trailers'), _('Car Wash'),
    _('Caravans'), _('Cargo Minibuses over 3.5t'), _('Cargo Minibuses up to 3.5t'),
    _('Combine Harvesters'), _('Compactors'), _('Concrete Mixers'), _('Cranes'),
    _('Cultivators'), _('Curtainsider Trailers'), _('Diagnostics'), _('Drones'),
    _('Electric Bikes'), _('Electric Scooters'), _('Engine Parts'), _('Excavators'),
    _('Fishing Boats'), _('Flatbed Trailers'), _('Forestry Machines'), _('Forklifts'),
    _('Helicopters'), _('Inflatable Boats'), _('Jet Skis'),
    _('Limuzinų, vestuvių transporto nuoma'), _('Loaders'), _('Moto Gear, accessories'),
    _('Moto Parts'), _('Motociklų nuoma'), _('Motorboats'), _('Motorcycles'),
    # Moto gear 3rd level
    _('Helmets'), _('Jackets'), _('Pants'), _('Suits / Combinations'), _('Gloves'),
    _('Boots'), _('Protective gear'), _('Travel bags'), _('Goggles & other gear'),
    _('Other Agricultural'), _('Other Construction'), _('Other Trailers'),
    _('Other Watercraft'), _('Painting'), _('Passenger Minibuses'), _('Ploughs'),
    _('Refrigerator Trailers'), _('Rims'), _('Sailboats'), _('Semi-Trucks / Tractors'),
    _('Semi-trailers'), _('Single moto part'), _('Single part / parts kit'),
    _('Single truck part'), _('Sprayers'),
    _('Statybinės technikos priedai'), _('Sunkiojo transporto, priekabų nuoma'),
    _('Tipper Trailers'), _('Towing'), _('Tractors'), _('Truck Parts'), _('Trucks'),
    _('Tyres'), _('Ultralight Aircraft'), _('Vans'), _('Vehicle Transporters'),
    _('Whole car for parts'), _('Whole moto for parts'), _('Whole truck for parts'),
    _('Yachts'),
]


FUEL_AND_TRANSMISSION_NAMES = [
    _('Automatic'), _('CVT'), _('Diesel'), _('Diesel / Electric (Hybrid)'),
    _('Diesel / Electric (Plug-in)'), _('Electric'), _('Ethanol'), _('LPG'), _('Manual'),
    _('Other'), _('Petrol'), _('Petrol / CNG'), _('Petrol / Electric (Hybrid)'),
    _('Petrol / Electric (Plug-in)'), _('Petrol / Electric / LPG'), _('Petrol / LPG'),
    _('Semi-automatic'),
]

# Automobilių savybių pavadinimai (Equipment.name) — DB jie lietuviški,
# o rodomi per {{ eq.name|tdb }}, todėl msgid'ai turi patekti į katalogus.
CAR_EQUIPMENT_NAMES = [
    _('360° vaizdo kamera'),
    _('APVA kompensacija nepanaudota'),
    _('AUX jungtis'),
    _('Aklosios zonos stebėjimo sistema'),
    _('Apple CarPlay / Android Auto'),
    _('Atsarginis ratas'),
    _('Atstumo jutiklių sistema'),
    _('Atstumo palaikymo sistema'),
    _('Audio grotuvas'),
    _('Automatinio parkavimo sistema'),
    _('Automatiškai užsilenkiantys veidrodėliai'),
    _('Automatiškai įsijungiantys žibintai'),
    _('Automobilis iš Amerikos'),
    _('Autonominis šildymas'),
    _('Autopilotas (kruizo kontrolė)'),
    _('Avarinio stabdymo sistema'),
    _('Bagažinės uždangalas'),
    _('Baterijos garantija'),
    _('Beraktė užvedimo sistema'),
    _('Bevielis telefono krovimas'),
    _('Bluetooth'),
    _('CD grotuvas'),
    _('CD keitiklis'),
    _('DVD grotuvas'),
    _('Daugiafunkcinis vairas'),
    _('Dinaminis posūkių apšvietimas'),
    _('Durelių pritraukimas'),
    _('Dvipusis energijos perdavimas'),
    _('ESP (stabilumo kontrolės sistema)'),
    _('El. langai'),
    _('El. reguliuojami veidrodėliai'),
    _('Elektra reguliuojama vairo padėtis'),
    _('Elektra valdomas bagažinės dangtis'),
    _('Elektra valdomos sėdynės'),
    _('Elektra valdomos sėdynės su atmintimi'),
    _('Elektra šildomas priekinis stiklas'),
    _('Galinio vaizdo kamera'),
    _('Garantija'),
    _('Greitasis krovimas'),
    _('HiFi audio sistema'),
    _('ISOFIX (vaiko kėdutės tvirtinimo taškai)'),
    _('Juostos palaikymo sistema'),
    _('Kablys'),
    _('Keli raktų komplektai'),
    _('Kelio ženklų atpažinimo sistema'),
    _('Klimato kontrolė'),
    _('Kritulių jutiklis'),
    _('LCD ekranas'),
    _('LED dienos žibintai'),
    _('LED žibintai'),
    _('Laisvų rankų įranga'),
    _('Lengvo lydinio ratlankiai'),
    _('Lietuvoje neeksploatuotas'),
    _('Liečiamas ekranas'),
    _('MP3 grotuvas'),
    _('Masažinės sėdynės'),
    _('Matriciniai žibintai'),
    _('Naktinio matymo asistentas'),
    _('Navigacija/GPS'),
    _('Nuotolinis užvedimas'),
    _('Nuovargio įspėjimo sistema'),
    _('Odinis salonas'),
    _('Oro kondicionierius'),
    _('Oro pagalvės'),
    _('Padangų slėgio stebėjimo sistema'),
    _('Padidinta variklio galia'),
    _('Pagalbos iškvietimo sistema (eCall)'),
    _('Palydovinė sekimo sistema'),
    _('Panoraminis stogas'),
    _('Papildoma audio įranga'),
    _('Parduodama lizingu'),
    _('Paruoštas autosportui'),
    _('Pavarų perjungimas prie vairo'),
    _('Pneumatinė pakaba'),
    _('Priekinio vaizdo kamera'),
    _('Priekinių žibintų plovimo įtaisas'),
    _('Pritaikytas neįgaliems'),
    _('Pritemstantis veidrodėlis'),
    _('Projekcinis ekranas ant stiklo (HUD)'),
    _('Rūko žibintai'),
    _('Serviso knygelė'),
    _('Signalizacija/Imobilaizeris'),
    _('Skaitmeninis prietaisų skydelis'),
    _('Skelbimas su VIN'),
    _('Sportinės sėdynės'),
    _('Start-Stop sistema'),
    _('Stoglangis'),
    _('Stogo bagažinės laikikliai'),
    _('Susidūrimo prevencijos sistema'),
    _('TV ekranas'),
    _('Tamsinti stiklai'),
    _('Tolimųjų šviesų asistentas'),
    _('Traukos kontrolės sistema'),
    _('Trifazis krovimas'),
    _('USB Type-C jungtis'),
    _('USB jungtis'),
    _('Valdymas balsu'),
    _('Vasarinių padangų komplektas'),
    _('Veliūro salonas'),
    _('Ventiliuojamos sėdynės'),
    _('Virtualūs veidrodėliai'),
    _('Įkalnės stabdis'),
    _('Šildomas vairas'),
    _('Šildomi veidrodėliai'),
    _('Šildomos sėdynės'),
    _('Šilumos siurblys'),
    _('Žemų dažnių garsiakalbis'),
    _('Žibintai „Xenon“'),
    _('Žieminių padangų komplektas'),
]
