# apps/listings/translatable_db.py
# ═══════════════════════════════════════════════════════════
# DB reikšmės (VehicleType.name, SubCategory.name), kurias reikia versti.
#
# Šis failas niekur neimportuojamas — egzistuoja tik tam, kad
# makemessages surinktų šiuos stringus į .po failus. Rodymo metu
# jie verčiami per {{ value|tdb }} filtrą (templatetags/i18n_db.py)
# arba gettext() view'e (pvz. get_subcategories_ajax).
# ═══════════════════════════════════════════════════════════

from django.utils.translation import gettext_lazy as _


VEHICLE_TYPE_NAMES = [
    _('Cars'), _('Minibuses, Buses & Campers'), _('Motorcycles & Moto Gear'),
    _('Trucks & Commercial'), _('Parts'), _('Tyres & Wheels'),
    _('Boats & Water Transport'), _('Trailers & Semi-trailers'),
    _('Construction & Warehouse Equipment'), _('Agricultural & Forestry'),
    _('Bicycles & Scooters'), _('Services'), _('Car Rental'), _('Planes & Aircraft'),
    _('Aircraft Parts'), _('Vilkikai'), _('Autotraukiniai, autovežiai'),
    _('Komunalinio ūkio transportas'), _('Krovimo ir sandėliavimo technika'),
    _('Automobilių supirkimas'), _('Video, audio, navigacijos'), _('Miško ūkio technika'),
    _('Turistiniai nameliai'),
]

# Kategorijų medžio suvienodinimas — naujos subkategorijos (0058 migracija).
# LT yra šaltinio kalba, todėl msgid = rodomas tekstas.
CATEGORY_TREE_NAMES = [
    _('Komunalinio ūkio transportas'),
    _('Žemės ūkio, spec. dalys'),
    _('Aksesuarai, Tuning'),
    _('Automobilių nuoma'),
    _('Mikroautobusų, turistinio, vandens tr. nuoma'),
    _('Statybinė technika'),
]

SUBCATEGORY_NAMES = [
    _('Aircraft Accessories'), _('Airplanes'), _('Avionics'), _('Balers'), _('Bicycles'),
    _('Boat Trailers'), _('Boats'), _('Body Repair'), _('Bulldozers'), _('Buses'),
    _('Campers'), _('Car Parts'), _('Car Service'), _('Car Trailers'), _('Car Wash'),
    _('Caravans'), _('Cargo Minibuses over 3.5t'), _('Cargo Minibuses up to 3.5t'),
    _('Combine Harvesters'), _('Compactors'), _('Concrete Mixers'), _('Cranes'),
    _('Cultivators'), _('Curtainsider Trailers'), _('Diagnostics'), _('Drones'),
    _('Electric Bikes'), _('Electric Scooters'), _('Engine Parts'), _('Excavators'),
    _('Fishing Boats'), _('Flatbed Trailers'), _('Forestry Machines'), _('Forklifts'),
    _('Helicopters'), _('Inflatable Boats'), _('Jet Skis'),
    _('Limuzinų, vestuvių transporto nuoma'), _('Loaders'), _('Moto Gear, accessories'),
    _('Moto Parts'), _('Motociklų nuoma'), _('Motorboats'), _('Motorcycles'),
    # Moto gear 3rd level
    _('Helmets'), _('Jackets'), _('Pants'), _('Suits / Combinations'), _('Gloves'),
    _('Boots'), _('Protective gear'), _('Travel bags'), _('Goggles & other gear'),
    _('Other Agricultural'), _('Other Construction'), _('Other Trailers'),
    _('Other Watercraft'), _('Painting'), _('Passenger Minibuses'), _('Ploughs'),
    _('Refrigerator Trailers'), _('Rims'), _('Sailboats'), _('Semi-Trucks / Tractors'),
    _('Semi-trailers'), _('Single moto part'), _('Single part / parts kit'),
    _('Single truck part'), _('Sprayers'),
    _('Statybinės technikos priedai'), _('Sunkiojo transporto, priekabų nuoma'),
    _('Tipper Trailers'), _('Towing'), _('Tractors'), _('Truck Parts'), _('Trucks'),
    _('Tyres'), _('Ultralight Aircraft'), _('Vans'), _('Vehicle Transporters'),
    _('Whole car for parts'), _('Whole moto for parts'), _('Whole truck for parts'),
    _('Yachts'),
]


FUEL_AND_TRANSMISSION_NAMES = [
    _('Automatic'), _('CVT'), _('Diesel'), _('Diesel / Electric (Hybrid)'),
    _('Diesel / Electric (Plug-in)'), _('Electric'), _('Ethanol'), _('LPG'), _('Manual'),
    _('Other'), _('Petrol'), _('Petrol / CNG'), _('Petrol / Electric (Hybrid)'),
    _('Petrol / Electric (Plug-in)'), _('Petrol / Electric / LPG'), _('Petrol / LPG'),
    _('Semi-automatic'),
]

# Automobilių savybių pavadinimai (Equipment.name) — DB jie lietuviški,
# o rodomi per {{ eq.name|tdb }}, todėl msgid'ai turi patekti į katalogus.
CAR_EQUIPMENT_NAMES = [
    _('360° vaizdo kamera'),
    _('APVA kompensacija nepanaudota'),
    _('AUX jungtis'),
    _('Aklosios zonos stebėjimo sistema'),
    _('Apple CarPlay / Android Auto'),
    _('Atsarginis ratas'),
    _('Atstumo jutiklių sistema'),
    _('Atstumo palaikymo sistema'),
    _('Audio grotuvas'),
    _('Automatinio parkavimo sistema'),
    _('Automatiškai užsilenkiantys veidrodėliai'),
    _('Automatiškai įsijungiantys žibintai'),
    _('Automobilis iš Amerikos'),
    _('Autonominis šildymas'),
    _('Autopilotas (kruizo kontrolė)'),
    _('Avarinio stabdymo sistema'),
    _('Bagažinės uždangalas'),
    _('Baterijos garantija'),
    _('Beraktė užvedimo sistema'),
    _('Bevielis telefono krovimas'),
    _('Bluetooth'),
    _('CD grotuvas'),
    _('CD keitiklis'),
    _('DVD grotuvas'),
    _('Daugiafunkcinis vairas'),
    _('Dinaminis posūkių apšvietimas'),
    _('Durelių pritraukimas'),
    _('Dvipusis energijos perdavimas'),
    _('ESP (stabilumo kontrolės sistema)'),
    _('El. langai'),
    _('El. reguliuojami veidrodėliai'),
    _('Elektra reguliuojama vairo padėtis'),
    _('Elektra valdomas bagažinės dangtis'),
    _('Elektra valdomos sėdynės'),
    _('Elektra valdomos sėdynės su atmintimi'),
    _('Elektra šildomas priekinis stiklas'),
    _('Galinio vaizdo kamera'),
    _('Garantija'),
    _('Greitasis krovimas'),
    _('HiFi audio sistema'),
    _('ISOFIX (vaiko kėdutės tvirtinimo taškai)'),
    _('Juostos palaikymo sistema'),
    _('Kablys'),
    _('Keli raktų komplektai'),
    _('Kelio ženklų atpažinimo sistema'),
    _('Klimato kontrolė'),
    _('Kritulių jutiklis'),
    _('LCD ekranas'),
    _('LED dienos žibintai'),
    _('LED žibintai'),
    _('Laisvų rankų įranga'),
    _('Lengvo lydinio ratlankiai'),
    _('Lietuvoje neeksploatuotas'),
    _('Liečiamas ekranas'),
    _('MP3 grotuvas'),
    _('Masažinės sėdynės'),
    _('Matriciniai žibintai'),
    _('Naktinio matymo asistentas'),
    _('Navigacija/GPS'),
    _('Nuotolinis užvedimas'),
    _('Nuovargio įspėjimo sistema'),
    _('Odinis salonas'),
    _('Oro kondicionierius'),
    _('Oro pagalvės'),
    _('Padangų slėgio stebėjimo sistema'),
    _('Padidinta variklio galia'),
    _('Pagalbos iškvietimo sistema (eCall)'),
    _('Palydovinė sekimo sistema'),
    _('Panoraminis stogas'),
    _('Papildoma audio įranga'),
    _('Parduodama lizingu'),
    _('Paruoštas autosportui'),
    _('Pavarų perjungimas prie vairo'),
    _('Pneumatinė pakaba'),
    _('Priekinio vaizdo kamera'),
    _('Priekinių žibintų plovimo įtaisas'),
    _('Pritaikytas neįgaliems'),
    _('Pritemstantis veidrodėlis'),
    _('Projekcinis ekranas ant stiklo (HUD)'),
    _('Rūko žibintai'),
    _('Serviso knygelė'),
    _('Signalizacija/Imobilaizeris'),
    _('Skaitmeninis prietaisų skydelis'),
    _('Skelbimas su VIN'),
    _('Sportinės sėdynės'),
    _('Start-Stop sistema'),
    _('Stoglangis'),
    _('Stogo bagažinės laikikliai'),
    _('Susidūrimo prevencijos sistema'),
    _('TV ekranas'),
    _('Tamsinti stiklai'),
    _('Tolimųjų šviesų asistentas'),
    _('Traukos kontrolės sistema'),
    _('Trifazis krovimas'),
    _('USB Type-C jungtis'),
    _('USB jungtis'),
    _('Valdymas balsu'),
    _('Vasarinių padangų komplektas'),
    _('Veliūro salonas'),
    _('Ventiliuojamos sėdynės'),
    _('Virtualūs veidrodėliai'),
    _('Įkalnės stabdis'),
    _('Šildomas vairas'),
    _('Šildomi veidrodėliai'),
    _('Šildomos sėdynės'),
    _('Šilumos siurblys'),
    _('Žemų dažnių garsiakalbis'),
    _('Žibintai „Xenon“'),
    _('Žieminių padangų komplektas'),
]

# Paieškos panelių laukų etiketės iš search_config/*.json — jos verčiamos
# per _() vykdymo metu, todėl makemessages jų nesurenka be šio sąrašo.
PANEL_FIELD_LABELS = [
    _('(A) statramsčio apdaila'),
    _('(B) statramsčio apdaila (apatinė)'),
    _('(B) statramsčio apdaila (viršutinė)'),
    _('(C) statramsčio apdaila'),
    _('(D) statramsčio apdaila (apatinė)'),
    _('(D) statramsčio apdaila (viršutinė)'),
    _('ABS rėlė'),
    _('ACC daviklio grotelės'),
    _('APD hidro transformatorius (automato pūslė)'),
    _('AdBlue purkštukas'),
    _('AdBlue skysčio bakelio laikiklis'),
    _('AdBlue skysčio bakelis'),
    _('AdBlue skysčio tiekimo vamzdelis'),
    _('AdBlue skysčio užpylimo vamzdis'),
    _('Akinių dėklas/ stalčiukas'),
    _('Akinių tipas'),
    _('Aklosios zonos stebėjimo sistema'),
    _('Aktyvaus stabilizatoriaus valdymo/ vožtuvų blokas'),
    _('Aktyvaus stabilizatoriaus valdymo/ vožtuvų bloko laikiklis'),
    _('Aktyvaus stabilizatoriaus vamzdelis (-ai)/ žarna (-os)'),
    _('Aktyvios anglies (degalų garų) filtras'),
    _('Akumuliatoriaus dėžė'),
    _('Akumuliatoriaus saugiklis (rėlė)'),
    _('Alkūninio veleno apsukų daviklis'),
    _('Alkūninio veleno dantratis/ skriemulys (paskirstimo)'),
    _('Alkūninio veleno laikiklis'),
    _('Alkūninio veleno padėties dantratis'),
    _('Alkūninio veleno padėties daviklis'),
    _('Alkūninis velenas'),
    _('Alsuoklio vožtuvas'),
    _('Alsuoklio žarnos sensorius'),
    _('Alsuoklis/ alsuoklio vamzdelis (-ai)/ žarna (-os)'),
    _('Amortizatoriaus atrama (kronšteinas)'),
    _('Amortizatorius galinio dangčio'),
    _('Amortizatorius variklio dangčio'),
    _('Antra eilė sėdynių'),
    _('Antros sėdynių eilės kilimėlis'),
    _('Apatinis, bagažinės šono, apdailos skydas'),
    _('Apatinė apdaila'),
    _('Apatinė bamperio dalis'),
    _('Apatinė bamperio dalis (lūpa)'),
    _('Apatinė dalis radiatorių panelės (televizoriaus)'),
    _('Apatinė slidė'),
    _('Apdaila aplink degalų bako dangtelį'),
    _('Apdaila bagažinės dangčio (komplektas)'),
    _('Apdaila galinio dangčio'),
    _('Apdaila galinių durų (moldingas)'),
    _('Apdaila krovinių durų (moldingas)'),
    _('Apdaila prie degalų bako dangtelio'),
    _('Apdaila priekinių durų (moldingas)'),
    _('Apdaila slankiojančių durų (moldingas)'),
    _('Apdaila variklio dangčio spynos'),
    _('Apdailinė galinio bamperio juosta'),
    _('Apdailinė priekinio bamperio juosta'),
    _('Apdailinė stogo juosta "moldingas"'),
    _('Apdailos detalės'),
    _('Apmušimas galinių durų (obšifke)'),
    _('Apmušimas priekinių durų (obšifke)'),
    _('Apmušimas slankiojančių durų (obšifke)'),
    _('Apsauginės durų stiklo grotos'),
    _('Apsauginės slankiojančių durų stiklo grotos'),
    _('Apsaugos nuo vaikų jungtukas'),
    _('Apšildoma kabina'),
    _('Apšvietimo konsolės apdaila'),
    _('Atbulinės eigos daviklis (varlytė)'),
    _('Atidarymo rankenėlė (su kamera) galinio dangčio'),
    _('Atidarymo rankenėlė galinio dangčio (išorinė)'),
    _('Atidarymo rankenėlė galinio dangčio (vidinė)'),
    _('Atidarymo rankenėlė slankiojančių durų (vidinė)'),
    _('Atitraukiami šonai'),
    _('Atlenkiamos sėdynės'),
    _('Atrama galinio dangčio'),
    _('Atraminė variklio dangčio kojelė'),
    _('Atsarginė padanga "plona"'),
    _('Atstumo jutiklių sistema'),
    _('Atveriamas bagažinės dangčio stiklas'),
    _('Atvėrimo rankenėlė galinio borto'),
    _('Audio aparatūra'),
    _('Aukšta kabina'),
    _('Aukštas'),
    _('Aukštis'),
    _('Aukštis m'),
    _('Aukšto dažnio garsiakalbis (-iai) priekinėse duryse'),
    _('Aukšto dažnio garsiakalbis galinėse duryse'),
    _('Aukštos įtampos ritė "babyna"'),
    _('Aukštos įtampos uždegimo laidas (žvaklaidis)'),
    _('Aukščio daviklis (priek. žibintų)'),
    _('Aukščio daviklis (priekinių žibintų)'),
    _('Automatinė pavarų dėžė'),
    _('Automatiškai užsilenkiantys veidrodėliai'),
    _('Automatiškai įsijungiantys žibintai'),
    _('Automobilio pašildymo laikmatis'),
    _('Automobilio užvedimo jungtukas'),
    _('Automobilis iš Amerikos'),
    _('Automobilis ne iš JAV'),
    _('Autonominio šildytuvo (Webastos) dugno apsauga'),
    _('Autonominio šildytuvo (webastos) cirkuliacinis siurbliukas'),
    _('Autonominio šildytuvo (webastos) degalų pompa (siurbliukas)'),
    _('Autonominio šildytuvo (webastos) degalų vamzdelis (-iai)'),
    _('Autonominio šildytuvo (webastos) distancinio valdymo komplektas'),
    _('Autonominio šildytuvo (webastos) distancinio valdymo pultelis'),
    _('Autonominio šildytuvo (webastos) duslintuvas'),
    _('Autonominio šildytuvo (webastos) tvirtinimo kronšteinas'),
    _('Autonominio šildytuvo (webastos) valdymo blokas'),
    _('Autonominis šildymas'),
    _('Autonominis šildymas (webasto)'),
    _('Autonominis šildytuvas (webasto)'),
    _('Autopilotas (kruizo kontrolė)'),
    _('Autovežio antstatas'),
    _('Aušinimas'),
    _('Aušinimo skysčio išsiplėtimo bakelio dangtelis'),
    _('Aušinimo skysčio išsiplėtimo bakelis'),
    _('Aušinimo skysčio lygio daviklis'),
    _('Aušinimo skysčio lygio rėl'),
    _('Aušinimo skysčio radiatorius'),
    _('Aušinimo skysčio temperatūros daviklis'),
    _('Aušinimo vamzdelis (-iai)/ žarna (-os)'),
    _('Aušinimo ventiliatoriaus instaliacija'),
    _('Aušinimo ventiliatoriaus rėlė'),
    _('Avarinio ženklo laikiklis'),
    _('Avarinis ženklas'),
    _('Avarinių šviesų rėlė'),
    _('Avarinių žibintų jungtukas'),
    _('Ašelė (galinio rato)'),
    _('Ašių skaičius'),
    _('Bagažinės'),
    _('Bagažinės Lango užuolaidėlė'),
    _('Bagažinės amortizatorius'),
    _('Bagažinės apatinis vyris'),
    _('Bagažinės apdailos dangtelis'),
    _('Bagažinės apšvietimo žibintas'),
    _('Bagažinės dangčio atidarymo jungtukas'),
    _('Bagažinės dangčio daviklis'),
    _('Bagažinės dangčio uždarymo jungtukas'),
    _('Bagažinės dangčio valdymo blokas'),
    _('Bagažinės dugnas'),
    _('Bagažinės dugno apsauga'),
    _('Bagažinės grindys'),
    _('Bagažinės grotos'),
    _('Bagažinės kilimas'),
    _('Bagažinės kilimėlis (guminis)'),
    _('Bagažinės lango užuolaidėlė'),
    _('Bagažinės pertvara'),
    _('Bagažinės sandarinimo guma (ant kėbulo)'),
    _('Bagažinės sandarinimo guma (prie stiklo)'),
    _('Bagažinės slenksčio apdaila'),
    _('Bagažinės spyna'),
    _('Bagažinės troselis'),
    _('Bagažinės uždangalas'),
    _('Bagažinės viršutinis vyris'),
    _('Bagažinės vyrių komplektas'),
    _('Bagažo skyrius'),
    _('Baliono (multi) vožtuvas'),
    _('Balkis panelės tvirtinimo'),
    _('Bamperio apsauga visureigiams (džipams)'),
    _('Bamperių pastiprinimai'),
    _('Belaidžio įkrovimo modulis'),
    _('Bendroji masė kg'),
    _('Beraktė užvedimo sistema'),
    _('Beraktės sistemos KESSY valdymo blokas/ modulis'),
    _('Betonvežio antstatas'),
    _('Bortinė platforma'),
    _('CB radio įranga'),
    _('Centr. skylės diametras'),
    _('Centrinio garsiakalbio rėmelis'),
    _('Centrinio užrakto jungtukas'),
    _('Centrinio užrakto rėlė'),
    _('Centrinio užrakto vakuuminė pompa'),
    _('Centrinio užrakto valdymo blokas'),
    _('Centrinio užrakto varikliukas'),
    _('Centrinis užraktas'),
    _('Centrinis vožtuvas'),
    _('Centrinė konsolė'),
    _('Centrinės konsolės valdymo blokas'),
    _('Centrinės oro grotelės'),
    _('Cilindrų galvutė'),
    _('Daiktadežė lubų'),
    _('Daiktadėžė'),
    _('Daiktadėžė automobilio priekyje'),
    _('Daiktadėžė bagažinėje'),
    _('Daiktadėžė centrinės konsolės'),
    _('Daiktadėžė galinių durų'),
    _('Daiktadėžė priekinių durų'),
    _('Daiktadėžės (bordačioko) dangtis'),
    _('Daiktadėžės (bordačioko) komplektas'),
    _('Daiktadėžės (bordačioko) rankenėlė'),
    _('Daiktadėžės (bordačioko) remas'),
    _('Daiktadėžės (bordačioko) spyna'),
    _('Daiktadėžės automobilio priekyje apdaila'),
    _('Daiktadėžės paklotėlis'),
    _('Daiktadėžės pertvara'),
    _('Daiktadėžės žibintas'),
    _('Dangtelis degalų bako'),
    _('Dangtelis durų rankenos'),
    _('Dangtelis galinių durų rankenos'),
    _('Dangtelis kibirkšties paskirstytojo (tramplioriaus)'),
    _('Dangtelis oro pagalvės'),
    _('Dangtelis palangėje'),
    _('Dangtelis priekinių durų rankenos'),
    _('Dangtelis saugiklių dėžės'),
    _('Dangtelis slankiojančių durų rankenos'),
    _('Dangtelis su skysčio lygio davikliu'),
    _('Dangtelis užuolaidos (štorkės) laikiklio'),
    _('Dangtis akumuliatoriaus dėžės'),
    _('Darbinis tūris (litrai)'),
    _('Darbinis tūris cm³'),
    _('Daužtas'),
    _('Deflektorius variklio dangčio'),
    _('Degalių lygio matuoklio rėlė'),
    _('Degalų (kuro) paskirstytojas'),
    _('Degalų (kuro) siurblio valdymo blokas'),
    _('Degalų (kuro) siurblys'),
    _('Degalų aušintuvas (radiatorius)'),
    _('Degalų bakas'),
    _('Degalų bako atidarymo jungtukas'),
    _('Degalų bako atidarymo trosas'),
    _('Degalų bako dangtelio atidarymo rankenėlė'),
    _('Degalų bako dangtelio spyna'),
    _('Degalų bako dangtelio spynos varikliukas'),
    _('Degalų bako dugno apsauga'),
    _('Degalų bako laikiklis (-iai)'),
    _('Degalų bako užpylimo vamzdis'),
    _('Degalų bako užsukamas dangtelis'),
    _('Degalų bako vožtuvas'),
    _('Degalų filtras'),
    _('Degalų filtro korpusas'),
    _('Degalų filtro laikiklis'),
    _('Degalų filtro šildytuvas'),
    _('Degalų grąžinimo vamzdelis/ žarnelė'),
    _('Degalų lygio daviklis'),
    _('Degalų magistralinis vamzdelis'),
    _('Degalų perjungimo (dujų) jungtukas'),
    _('Degalų purkštukų (forsunkių) laidai'),
    _('Degalų purkštukų (forsunkių) valdymo blokas'),
    _('Degalų siurblio (degalų bake) veržlė'),
    _('Degalų siurblio dantratis (skriemulys)'),
    _('Degalų siurblio kronšteinas'),
    _('Degalų siurbliuko rėlė'),
    _('Degalų siurblys (degalų bake)'),
    _('Degalų slėgio daviklis'),
    _('Degalų slėgio reguliatorius'),
    _('Degalų temperatūros daviklis'),
    _('Degalų temperatūros matuoklis'),
    _('Degalų tiekimo į purkštukus vamzdelis (-iai)'),
    _('Degalų vamzdelis (-ai)/ žarna (-os)'),
    _('Degalų vamzdelis (-iai)'),
    _('Degalų įpurškimas kita'),
    _('Degalų šildytuvas'),
    _('Degimo rėlė'),
    _('Dekoratyvinė apdaila'),
    _('Dekoratyvinė apdailos juostelė'),
    _('Dienos šviesų rėlė'),
    _('Diferencialų blokavimo jungtukas'),
    _('Difūzorius'),
    _('Dinaminis posūkių apšvietimas'),
    _('Diržo įtempėjas'),
    _('Diržo įtempėjo skriemulys'),
    _('Diskiniai stabdžiai'),
    _('Droselinė sklendė'),
    _('Dugno apsauga galinės važiuoklės'),
    _('Dujinė viryklė'),
    _('Dujų filtras'),
    _('Dujų purkštukas'),
    _('Dujų reduktoriaus temperatūros daviklis'),
    _('Dujų įrangos valdymo blokas'),
    _('Dujų įrangos vamzdelis (-ai)/ žarna (-os)'),
    _('Durelių pritraukimas'),
    _('Durys šone'),
    _('Durų apdailų komplektas'),
    _('Durų apmušalai'),
    _('Durų atvėrimo/ užvėrimo daviklis (varlytė)'),
    _('Durų elektronikos valdymo blokas'),
    _('Durų peleninė'),
    _('Durų skaičius'),
    _('Durų spyna (dvidurio)'),
    _('Durų stiklo apdaila'),
    _('Durų stiklo bėgelis'),
    _('Durų stiklo rėmas'),
    _('Dušas'),
    _('Dvidurio galinių vietų šoninis apdailos skydas'),
    _('Dviračių laikikliai'),
    _('Dviračių laikiklis'),
    _('EGR aušintuvas'),
    _('EGR aušintuvo kronšteinas'),
    _('EGR vamzdelis (-iai)/ žarna (-os)'),
    _('EGR vožtuvas'),
    _('ESP (Stabilumo kontrolės sistema)'),
    _('ESP (stabilumo sistemos) daviklis (išilginio pagreičio daviklis)'),
    _('Ekranas/ displėjus/ ekraniukas'),
    _('El. Lango pakėlimo mechanizmo komplektas'),
    _('El. lango pakėlimo mechanizmas be varikliuko'),
    _('El. langų rėlė'),
    _('El. oro padavimo sklendė'),
    _('El. reguliuojami veidrodėliai'),
    _('El. sėdynės'),
    _('El. veidrodėliai'),
    _('Elektra reguliuojama vairo padėtis'),
    _('Elektra valdomas bagažinės dangtis'),
    _('Elektra valdomos sėdynės'),
    _('Elektra valdomos sėdynės su atmintimi'),
    _('Elektra šildomas priekinis stiklas'),
    _('Elektrinis radiatorių ventiliatorius'),
    _('Elektrinis salono (220V) šildytuvas'),
    _('Elektrinis salono pečiuko radiatorius'),
    _('Elektrinių langų jungtukas'),
    _('Elektrinė galinio stiklo užuolaida'),
    _('Elektrinė lango užuolaidėlė'),
    _('Elektrinė tempimo gervė'),
    _('Elektrinė variklio pašildymo sistema (papildoma)'),
    _('Elektromagnetinis vožtuvas'),
    _('Elektromobilio įkrovimo laidas'),
    _('Elektroninė klimato kontrolė'),
    _('Energijos šaltinis'),
    _('Galimybė prijungti papildomą bateriją'),
    _('Galinio aukščio daviklio svirtis'),
    _('Galinio dangčio (bagažinės) instaliacija'),
    _('Galinio dangčio numerio apšvietimo juosta'),
    _('Galinio el. lango pakėlimo mechanizmas be varikliuko'),
    _('Galinio kėbulo slenksčio apdaila'),
    _('Galinio lango atidarymo rankenėlė'),
    _('Galinio reduktoriaus kronšteinas'),
    _('Galinio reduktoriaus pagalvė'),
    _('Galinio slenksčio apdaila (išorinė)'),
    _('Galinio slenksčio apdaila (vidinė)'),
    _('Galinio stalčiuko/lentinėlės paklotėlis'),
    _('Galinio stiklo atidarymo mygtukas/ rankenėlė'),
    _('Galinio stiklo valytuvo kojelė'),
    _('Galinio šoninio lango užuolaidėlė'),
    _('Galinio šoninio stiklo apdaila'),
    _('Galinio žibinto apdaila (juostelė)'),
    _('Galinio žibinto dangtelis (lizdas)'),
    _('Galinio žibinto detalė'),
    _('Galinio žibinto stiklas (dangtyje)'),
    _('Galinio žibinto stiklas (kėbule)'),
    _('Galinis amortizatorius (pneumatinė/ hidraulinė važiuoklė)'),
    _('Galinis atšvaitas'),
    _('Galinis dangtis (bagažinės)'),
    _('Galinis kilimėlis'),
    _('Galinis lankas visureigiams (džipams)'),
    _('Galinis pusašis'),
    _('Galinis slenkstis (kėbulo dalis)'),
    _('Galinis stabdžių ABS daviklis'),
    _('Galinis stabdžių diskas'),
    _('Galinis suvedimo varžtas'),
    _('Galinis varikliukas langų pakėlėjo'),
    _('Galinis važiuoklės balkis'),
    _('Galinis viršutinis vyris'),
    _('Galinis vyrių komplektas'),
    _('Galinis vėjo deflek'),
    _('Galinis šoninis kėbulo stiklas'),
    _('Galinis žibintas'),
    _('Galinis žibintas bamperyje'),
    _('Galinis žibintas dangtyje'),
    _('Galinis žibintas kėbule'),
    _('Galinių durų'),
    _('Galinių durų apšvietimo žibintas (viduje)'),
    _('Galinių durų atvėrimo/ užvėrimo daviklis (varlytė)'),
    _('Galinių durų garsiakalbio apdaila'),
    _('Galinių durų instaliacija'),
    _('Galinių durų oro pagalvė'),
    _('Galinių durų pritraukėjas'),
    _('Galinių durų rankenos apšvietimo žibintas (išorėje)'),
    _('Galinių durų sandarinimo guma'),
    _('Galinių durų spyna'),
    _('Galinių durų stiklo apdaila'),
    _('Galinių durų stiklo bėgelis'),
    _('Galinių durų stiklo rėmas'),
    _('Galinių durų troselis'),
    _('Galinių langų jungtuko apdaila'),
    _('Galinių stabdžio (EMF) valdymo blokas'),
    _('Galinių vietų apšvietimo žibintas'),
    _('Galinių žibintų istaliacija'),
    _('Galinių žibintų komplektas'),
    _('Galinių žibintų rėlė'),
    _('Galinė'),
    _('Galinė amortizatoriaus cilindro apsauga'),
    _('Galinė apdailos juosta'),
    _('Galinė arka'),
    _('Galinė atidarymo rankenėlė (vidinė)'),
    _('Galinė atidarymo rankenėlė vidinė'),
    _('Galinė dalis'),
    _('Galinė kreipenčioji įvorė (-ės) (sailentblokas)'),
    _('Galinė kėbulo dalis'),
    _('Galinė lango užuolaidėlė'),
    _('Galinė lingė'),
    _('Galinė pneumatinė (oro) pagalvė'),
    _('Galinė pneumatinė (oro) pagalvė su amortizatoriumi'),
    _('Galinė pūslė'),
    _('Galinė sandarinimo guma (ant kėbulo)'),
    _('Galinė sandarinimo guma (prie stiklo)'),
    _('Galinė spynos kilpa'),
    _('Galinė spyruoklė'),
    _('Galinė spyruoklės guminė atrama'),
    _('Galinė stabdžių disko apsauga'),
    _('Galinė stabilizatoriaus traukė'),
    _('Galinė stebulė'),
    _('Galinė svirtis'),
    _('Galinė sėdynė'),
    _('Galinė uždarymo rankena/ apdaila'),
    _('Galinė šakė'),
    _('Galinė švytuoklė'),
    _('Galinės arkos apdaila'),
    _('Galinės durys'),
    _('Galinės orinės pakabos vamzdelis'),
    _('Galinės pakabos aukščio daviklio svirtelė'),
    _('Galinės pakabos aukščio daviklis'),
    _('Galinės sedynės porankis'),
    _('Galinės spynos varikliukas'),
    _('Galinės sėdynės galvos atrama'),
    _('Galinės važiuoklės komplektas'),
    _('Galiojanti techninė apžiūra (TA)'),
    _('Galvutė'),
    _('Galvutės dangtelis'),
    _('Galvutės tvirtinimo varžtai/ smeigės'),
    _('Gamintojo ženkliukas'),
    _('Gamintojo ženkliukas/ modelio raidės'),
    _('Gamyklinis rato centrinės skylės dangtelis (-iai)'),
    _('Garažo vartų jungtukas'),
    _('Garsiakalbio apdaila slankiojančių durų'),
    _('Garsiakalbis (-iai) galinėje palangėje'),
    _('Garsiakalbis (-iai) galinėse duryse'),
    _('Garsiakalbis (-iai) priekinėse duryse'),
    _('Garsiakalbis panelėje'),
    _('Garso aparatūra'),
    _('Garso izoliacija variklio dangčio'),
    _('Garso signalo rėlė'),
    _('Generatoriaus detalė (-ės)'),
    _('Generatoriaus diržas'),
    _('Generatoriaus diržo atraminis guolis'),
    _('Generatoriaus diržo įtempėjas'),
    _('Generatoriaus kronšteinas'),
    _('Geros būklės'),
    _('Grandinės'),
    _('Grandinės šliaužiklis (variklio)'),
    _('Greičio daviklis'),
    _('Greičio daviklis (spidometro daviklis)'),
    _('Greičio palaikymo sistema'),
    _('Greičio palaikymo siurbliukas'),
    _('Greičio variatorius'),
    _('Greičių dėžės karteris'),
    _('Grotelės apatinės (trijų dalių)'),
    _('Grotelės dangčio plokštumoje'),
    _('Grotelės palangėje'),
    _('Grotelės priekinės'),
    _('Grotelės sparne'),
    _('Grotelės viršutinės'),
    _('Guma sandarinimo (ant bagažinės durų)'),
    _('Guma sandarinimo (ant galinio dangčio)'),
    _('Guma sandarinimo (ant priekinių durų)'),
    _('Guma sandarinimo (ant slankiojančių durų)'),
    _('Guma sandarinimo priekinių durų (prie stiklo)'),
    _('Guma sandarinimo slankiojančių durų (prie stiklo)'),
    _('Guminė kardano jungtis'),
    _('Guoliavietė (galinė ašis)'),
    _('Guoliavietė (priekinė ašis)'),
    _('Gyvulių pervežimo'),
    _('Head-up ekranas/ displėjus'),
    _('Hibrido/ elektromobilio akumuliatoriaus laikiklis/ kronšteinas'),
    _('Hibrido/ elektromobilio akumuliatorius aušintuvas (ventiliatorius)'),
    _('Hidraulikos komplektas galinio dangčio'),
    _('Hidraulikos siurblys galinio dangčio'),
    _('Hidraulinis SERVOTRONIC vožtuvas'),
    _('Hidraulinis stogo užrakto cilindriukas'),
    _('Hidraulinis važiuoklės siurblys'),
    _('Hidrocilindras galinio dangčio'),
    _('ISOFIX (Vaiko kėdutės tvirtinimo taškai)'),
    _('Ieškoti'),
    _('Indikatoriaus rėlė'),
    _('Interjero apšvietimo jungtukas'),
    _('Interkūlerio radiatorius'),
    _('Interkūlerio žarna (-os)/ vamzdelis (-iai)'),
    _('Interkūlerio žarnos/ vamzdelio laikiklis/ kronšteinas'),
    _('Inverteris (įtampos keitiklis)'),
    _('Išilginiai stogo strypai "ragai"'),
    _('Išilginė traukė'),
    _('Išmetamųjų dujų slėgio daviklis'),
    _('Išmetamųjų dujų temperatūros daviklis'),
    _('Išmetamųjų dujų vamzdelis'),
    _('Išmetimo daviklis'),
    _('Išmetimo kolektoriaus kita detalė (-ės)'),
    _('Išmetimo kolektorius'),
    _('Išmetimo termo izoliacija (apsauga nuo karščio)'),
    _('Išmetimo valymo valdymo blokas'),
    _('Išminamasis guolis'),
    _('Išminamasis guolis su cilindriuku'),
    _('Išminamasis guolis su svirtimi'),
    _('Išminamojo guolio svirtis/ šakutė'),
    _('Išorinio pusašio šarnyro (granatos) guma'),
    _('Išorinis pusašio šarnyras (granata)'),
    _('Išorinė atidarymo rankena'),
    _('Išorinė atidarymo rankena galinių durų'),
    _('Išorinė atidarymo rankena slankiojančių durų'),
    _('Išorinė bagažinės atidarymo rankena'),
    _('Išorės apdailos komplektas'),
    _('Jungiklis galinio dangčio uždarymo'),
    _('Jungiklių komplektas'),
    _('Kalnų stabdis'),
    _('Kampinė galinio bamperio dalis'),
    _('Kampinė priekinio bamperio dalis'),
    _('Kampinės bamperio dalies laikiklis'),
    _('Karbiuratoriaus/ mono įpurškimo padas'),
    _('Kardano kryžminė jungtis'),
    _('Karštas vanduo'),
    _('Katalizatorius/ FAP/DPF kietųjų dalelių filtras'),
    _('Keleivio atlošas'),
    _('Keleivio oro pagalvė'),
    _('Keleivio oro pagalvės jungtukas'),
    _('Keli raktų komplektai'),
    _('Kelio ženklų atpažinimo sistema'),
    _('Kelių oro pagalvė'),
    _('Kibirkšties paskirstytojas (trampliorius)'),
    _('Kietašonis antstatas'),
    _('Kilimėlių komplektas'),
    _('Kilimėlių laikiklis (-iai)/ fiksatorius (-iai)'),
    _('Kilpa bagažinės durų spynos'),
    _('Kilpa priekinės spynos'),
    _('Kilpa slankiojančių durų spynos'),
    _('Kilpa variklio dangčio spynos'),
    _('Kita (-os) sėdynė (-ės)'),
    _('Kita bagažinės apdailos detalė'),
    _('Kita centrinė konsolės (tunelio) detalė'),
    _('Kita dugno detalė'),
    _('Kita galinių durų apdailos detalė'),
    _('Kita galinės važiuoklės detalė'),
    _('Kita išorės detalė'),
    _('Kita karbiuratoriaus detalė (-ės)'),
    _('Kita kėbulo dalis'),
    _('Kita palangės detalė'),
    _('Kita panelės detalė'),
    _('Kita priekinių durų apdailos detalė'),
    _('Kita priekinės važiuoklės dalis'),
    _('Kita rėlė'),
    _('Kita salono detalė'),
    _('Kita slankiojančių durų apdailos detalė'),
    _('Kita slenkscių/ statramsčių apdailos detalė'),
    _('Kita variklio detalė'),
    _('Kita variklio galvutės detalė'),
    _('Kita variklio skyriaus detalė'),
    _('Kitas prietaisų skydelis'),
    _('Kitas salono žibintas'),
    _('Kiti jungtukai/ rankenėlės/ perjungėjai'),
    _('Kiti ženkliukai/ užrašai'),
    _('Klimato kontrolė'),
    _('Klimato kontrolės/ pečiuko kontrolės apdaila'),
    _('Kojų erdvės šonine apdaila'),
    _('Kolektorius įsiurbimo'),
    _('Komplektas dujų įrangos'),
    _('Konsolės valdymo modulis'),
    _('Kontaktinė durų jungtis'),
    _('Konteinerių gabenimo'),
    _('Kopetėlės'),
    _('Korpusas purkštukų montavimo'),
    _('Kosnsolės stalčiuko/lentinėlės paklotėlis'),
    _('Kritulių jutiklis'),
    _('Kronšteinas'),
    _('Kronšteinas amortizatorius tvirtinimo'),
    _('Kronšteinas spynos tvirtinimo'),
    _('Krovininių durų stiklo apdaila'),
    _('Krovinio diržai'),
    _('Krovinių (bagažinės) durys'),
    _('Krovinių (bagažinės) durų instaliacija'),
    _('Krovinių (bagažinės) durų stiklas'),
    _('Kruizo kontrolė'),
    _('Kuro žarna'),
    _('Kėbulas'),
    _('Kėbulo modulis'),
    _('Kėbulo tipas'),
    _('Kėlimo taškas/padas'),
    _('LED dienos žibintai'),
    _('LED dienos žibintas'),
    _('LED šviesų modulis'),
    _('LED žibintai'),
    _('Laikiklis (kronšteinas)'),
    _('Laikiklis purkštuko (forsunkės)'),
    _('Laikiklis radiatorių panelės (televizoriaus)'),
    _('Laikiklis/ kronšteinas išorinės atidarymo rankenos bagažinės durų'),
    _('Laikiklis/ kronšteinas išorinės atidarymo rankenos galinių durų'),
    _('Laikiklis/ kronšteinas išorinės atidarymo rankenos slankiojančių durų'),
    _('Laikiklis/ kronšteinas išorinės priekinės atidarymo rankenos'),
    _('Laisvos eigos vožtuvas (reguliatorius)'),
    _('Laisvų rankų įranga'),
    _('Landžeronas'),
    _('Lango oro grotelės'),
    _('Lango užuolaidėlė slankiojančių durų'),
    _('Langų apiplovimo rėlė'),
    _('Langų skysčio bakelio užpylimo vamzdelis'),
    _('Langų skysčio bakelis'),
    _('Langų skysčio lygio daviklis'),
    _('Langų skysčio purkštukas (-ai) galinio stiklo'),
    _('Langų skysčio purkštukas (-ai) priekinio stiklo'),
    _('Langų skysčio siurbliukas (stiklų)'),
    _('Langų skysčio žarnelė (-ės) galinio stiklo'),
    _('Langų skysčio žarnelė (-ės) priekinio stiklo'),
    _('Langų valdymo rėlė'),
    _('Langų valytuvų intervalo rėlė'),
    _('Langų valytuvų rėlė'),
    _('Lauko temperatūros daviklis'),
    _('Lauko temperatūros matuoklis'),
    _('Lemputė'),
    _('Liečiamas ekranas'),
    _('Lingės'),
    _('Linijiniai išėjimai'),
    _('Lonžeronai'),
    _('Lopšys'),
    _('Lubų komplektas'),
    _('Lėtintos pavaros'),
    _('MONO įpurškimas'),
    _('Markė'),
    _('Masažinės sėdynės'),
    _('Matriciniai žibintai'),
    _('Max kėlimo aukštis m'),
    _('Mažasis "A" galinių durų stiklas'),
    _('Mažasis "A" priekinių durų stiklas (dvidurio)'),
    _('Mažasis "A" priekinių durų stiklas (keturdurio)'),
    _('Mechaninis galinio lango pakėlimo mechanizmas'),
    _('Mechaninis lango pakėlimo mechanizmas'),
    _('Mechaninis priekinio lango pakėlimo mechanizmas'),
    _('Mechaninė 4 pavarų dėžė'),
    _('Mechaninė 5 pavarų dėžė'),
    _('Mechaninė 6 pavarų dėžė'),
    _('Mechaninė 7 pavarų dėžė'),
    _('Mechaninė degalų pompa'),
    _('Mechaninė galinio stiklo užuolaida'),
    _('Medienvežio antstatas'),
    _('Medžiaga'),
    _('Miegamų vietų skaičius'),
    _('Modelio raidės'),
    _('Modelio raidės ant durų'),
    _('Modelio raidės ant sparno'),
    _('Multifunkcinis valdymo jungtukas/ rankenėlė'),
    _('Mygtukas kablio bagažinėje'),
    _('Navigacijos žemėlapiai CD/DVD'),
    _('Negamyklinis (papildomas) priešrūkinis žibintas'),
    _('Negamyklinis rato centrinės skylės dangtelis (-iai)'),
    _('Numerio apšvietimas'),
    _('Numerių laikiklis'),
    _('Nuotolinis užvedimas'),
    _('Nuovargio įspėjimo sistema'),
    _('Originalūs ratlankiai'),
    _('Oro filtro dėžė'),
    _('Oro filtro dėžės dangtelis'),
    _('Oro filtro dėžės laikiklis'),
    _('Oro grotelės gale'),
    _('Oro grotelės lubose'),
    _('Oro kokybės daviklis'),
    _('Oro kondicionieriaus diržo įtempėjas'),
    _('Oro kondicionieriaus išsiplėtimo vožtuvas'),
    _('Oro kondicionieriaus kita detalė'),
    _('Oro kondicionieriaus kompresoriaus kronšteinas'),
    _('Oro kondicionieriaus kompresoriaus mova/ įvorė'),
    _('Oro kondicionieriaus oro srauto sklendės varikliukas'),
    _('Oro kondicionieriaus radiatorius aušinimo'),
    _('Oro kondicionieriaus slėgio daviklis'),
    _('Oro kondicionieriaus vamzdelis (-ai)/ žarna (-os)'),
    _('Oro kondicionieriaus ventiliatorius (aušinimo)'),
    _('Oro kondicionieriaus/ klimato/ pečiuko valdymo blokas (salone)'),
    _('Oro kondicionieriaus/ šildymo valdymo blokas'),
    _('Oro mikrofiltro rėmas (dalis)'),
    _('Oro nukreipėjas/ kanalas interkūlerio radiatoriaus'),
    _('Oro pagalvių juosta (srs žiedas)'),
    _('Oro pagalvių juostos instaliacija'),
    _('Oro pagalvių komplektas'),
    _('Oro pagalvių smūgio daviklis'),
    _('Oro pagalvių valdymo blokas'),
    _('Oro pagalvės'),
    _('Oro pakabos valdymo blokas (galinės)'),
    _('Oro paėmimo kanalo detalė (-ės)'),
    _('Oro skirstytuvas/ vožtuvų blokas (pneumatinė važiuoklė)'),
    _('Oro skirstytuvas/ vožtuvų blokas (pneumatinės važiuoklės)'),
    _('Oro sklendės trosas'),
    _('Oro sklendės varikliukas'),
    _('Oro slėgio daviklis'),
    _('Oro vamzdis į turbiną'),
    _('Padangų slėgio daviklis'),
    _('Padangų slėgio stebėjimo sistema'),
    _('Padangų slėgio valdymo blokas'),
    _('Padangų tipas'),
    _('Padargas / Savaeigė'),
    _('Pagalbos iškvietimo sistema (eCall)'),
    _('Pagalvė pavarų dėžės'),
    _('Pagamintas iš'),
    _('Pagrindinis galinių durų stiklas'),
    _('Pagrindinis priekinių durų stiklas (dvidurio)'),
    _('Pagrindinis priekinių durų stiklas (keturdurio)'),
    _('Pagrindinis stabdžių cilindriukas'),
    _('Pakaitinimo žvakių laidai'),
    _('Pakaitinimo žvakė (-ės)'),
    _('Pakeliama ašis'),
    _('Pakrovėjas akumuliatorius (papildomas)'),
    _('Pakėlimo/ nuleidimo mechanizmas'),
    _('Palangė galinė'),
    _('Palangės garsiakalbio apdaila'),
    _('Palydovinė sekimo sistema'),
    _('Panelė'),
    _('Panelės apdaila'),
    _('Panelės apdailos skydas (apatinis)'),
    _('Panelės apdailos skydas (centrinis)'),
    _('Panelės apdailos skydas (šoninis)'),
    _('Panelės apšvietimo reguliavimo jungtukas'),
    _('Panelės instaliacija'),
    _('Panelės stalčiuko/lentinėlės paklotėlis'),
    _('Papildoma audio įranga'),
    _('Papildomas hidraulikos vožtuvas'),
    _('Papildomas stop žibintas'),
    _('Pardavėjo tipas'),
    _('Parduodamos po vieną'),
    _('Parduodu po vieną'),
    _('Parkavimo (PDC) daviklių ekranas/ displėjus'),
    _('Parkavimo (PDC) daviklių garsiakalbis'),
    _('Parkavimo (PDC) daviklių instaliacija'),
    _('Parkavimo (PDC) daviklių jungtukas'),
    _('Parkavimo (PDC) daviklių valdymo blokas'),
    _('Parkavimo kojelė'),
    _('Paruoštas autosportui'),
    _('Pasirinkite dalį (0/70)'),
    _('Paskirstymo diržas'),
    _('Paskirstymo diržo apsauga (dangtelis)'),
    _('Paskirstymo diržo atraminis guolis'),
    _('Paskirstymo diržo įtempėjas'),
    _('Paskirstymo diržo/ grandinės įtempėjas'),
    _('Paskirstymo fazių reguliatorius'),
    _('Paskirstymo grandinė (variklio)'),
    _('Paskirstymo grandinės dangtelis'),
    _('Paskirstymo grandinės žvaigždutė'),
    _('Paskirstymo velenėliai'),
    _('Paskirstymo velenėlio adaptacijos vožtuvas (vanos vožtuvas)'),
    _('Paskirstymo velenėlio apsukų daviklis'),
    _('Paskirstymo velenėlio laikiklis'),
    _('Paskirstymo velenėlio padėties daviklis'),
    _('Paskirstymo velenėlio skriemulys/ vanusas)'),
    _('Paskirstymo velenėlis'),
    _('Pastiprinimas slenksčio'),
    _('Pastovaus greičio (autopiloto) rankenėlė'),
    _('Pastovaus greičio (cruise) valdymo blokas'),
    _('Pastovaus greičio jungtukas'),
    _('Pastovaus greičio palaikymo rėlė'),
    _('Pavarų dėžė'),
    _('Pavarų dėžės apsauga'),
    _('Pavarų dėžės detalė'),
    _('Pavarų dėžės instaliacija'),
    _('Pavarų dėžės reduktoriaus (razdatkės) varikliukas'),
    _('Pavarų dėžės reduktorius (razdatkė)'),
    _('Pavarų dėžės reduktorius (razdatkės) valdymo blokas'),
    _('Pavarų dėžės tarpinė'),
    _('Pavarų dėžės tepalo aušintuvo vamzdelis (-ai)/ žarna (-os)'),
    _('Pavarų dėžės tepalo radiatorius'),
    _('Pavarų dėžės tvirtinimo kronšteinas'),
    _('Pavarų dėžės valdymo blokas'),
    _('Pavarų indikacinė rėlė'),
    _('Pavarų indikatorius'),
    _('Pavarų perjungimas prie vairo'),
    _('Pavarų perjungimo jungtukas/ rankenėlė'),
    _('Pavarų perjungimo mechanizmas (dėžėje)'),
    _('Pavarų perjungimo mechanizmas (kulysa) (salone)'),
    _('Pavarų perjungimo svirties apdaila (oda, bumbulas)'),
    _('Pavarų perjungimo svirties apdaila (plastikinė)'),
    _('Pavarų perjungimo svirtis'),
    _('Pavarų perjungimo traukė'),
    _('Pavarų perjungimo trosas'),
    _('Pavarų perjungimo troso laikiklis/ kronsteinas'),
    _('Pavarų selektorius'),
    _('Pedalų komplektas'),
    _('Peleninė (galinė)'),
    _('Peleninė (priekyje)'),
    _('Peleninė panelėje'),
    _('Peleninės apdaila'),
    _('Peleninės apdaila (galinės)'),
    _('Peleninės apdaila (priekyje)'),
    _('Penkto bėgio dantratis (-čiai)'),
    _('Penumatinio oro pakabos kompresoriaus laikiklis (kronšteinas)'),
    _('Personalinis apšvietimas'),
    _('Pesčiųjų oro pagalvė'),
    _('Pečiuko radiatorius'),
    _('Pečiuko radiatorius vamzdelis (-ai)/ žarna (-os)'),
    _('Pečiuko reguliavimo trosiukai'),
    _('Pečiuko ventiliatoriaus reustatas'),
    _('Pečiuko ventiliatorius/ putikas'),
    _('Pirmosios registracijos šalis'),
    _('Platforma stumiasi į abi puses'),
    _('Platforma stumiasi į vieną pusę'),
    _('Pliusinių laidų jungimo mazgas'),
    _('Pneumatinė pakaba'),
    _('Pneumatinės (oro) pakabos kompresorius'),
    _('Pneumatinės (oro) pakabos oro filtras'),
    _('Pneumatinės (oro) pakabos oro paėmimo vamzdelis'),
    _('Posūkiai'),
    _('Posūkio žibintas veidrodėlyje'),
    _('Posūkių/ šviesų rankenėlė'),
    _('Pridegėjas'),
    _('Pridegėjas (galinis)'),
    _('Pridegėjas (priekyje)'),
    _('Pridegėjo apdaila'),
    _('Pridegėjo apdaila (galinio)'),
    _('Pridegėjo apdaila (priekyje)'),
    _('Priekabos kablio rėlė'),
    _('Priekinio aukščio daviklio svirtis'),
    _('Priekinio el. Lango pakėlimo mechanizmo komplektas'),
    _('Priekinio el. lango pakėlimo mechanizmo komplektas'),
    _('Priekinio kėbulo slenksčio apdaila'),
    _('Priekinio lango atidarymo rankenėlė'),
    _('Priekinio reduktoriaus kronšteinas'),
    _('Priekinio reduktoriaus pagalvė'),
    _('Priekinio slenksčio apdaila (išorinė)'),
    _('Priekinio slenksčio apdaila (vidinė)'),
    _('Priekinio stiklo valytuvų kojelė'),
    _('Priekinio žibinto (-ų) laidas'),
    _('Priekinio žibinto (xenon) lemputė'),
    _('Priekinio žibinto apdaila'),
    _('Priekinio žibinto dangtelis'),
    _('Priekinio žibinto detalė'),
    _('Priekinio žibinto laikiklis'),
    _('Priekinio žibinto lemputė'),
    _('Priekinio žibinto stiklas'),
    _('Priekinis amortizatorius (pneumatinė/ hidraulinė važiuoklė)'),
    _('Priekinis atšvaitas'),
    _('Priekinis el. lango pakėlimo mechanizmas be varikliuko'),
    _('Priekinis kilimėlis'),
    _('Priekinis laikiklis/ kronšteinas išorinės atidarymo rankenos'),
    _('Priekinis lankas visureigiams (džipams)'),
    _('Priekinis posūkio žibintas'),
    _('Priekinis pusašis'),
    _('Priekinis slenkstis (kėbulo dalis)'),
    _('Priekinis stabdžių ABS daviklis'),
    _('Priekinis stabdžių diskas'),
    _('Priekinis suvedimo varžtas'),
    _('Priekinis varikliukas langų pakėlėjo'),
    _('Priekinis viršutinis vyris'),
    _('Priekinis vyrių komplektas'),
    _('Priekinis vėjo deflektorius'),
    _('Priekinis žibintas'),
    _('Priekinių durų'),
    _('Priekinių durų apšvietimo žibintas (viduje)'),
    _('Priekinių durų atvėrimo riotuvas'),
    _('Priekinių durų atvėrimo/ užvėrimo daviklis (varlytė)'),
    _('Priekinių durų instaliacija'),
    _('Priekinių durų oro pagalvė'),
    _('Priekinių durų pritraukėjas'),
    _('Priekinių durų pritraukėjas (dvidurio)'),
    _('Priekinių durų rankenos apšvietimo žibintas (išorėje)'),
    _('Priekinių durų stiklo apdaila'),
    _('Priekinių durų stiklo bėgelis'),
    _('Priekinių durų stiklo rėmas'),
    _('Priekinių durų troselis (dvidurio)'),
    _('Priekinių durų ventiliatorius/ putikas'),
    _('Priekinių langų jungtuko apdaila'),
    _('Priekinių vietų apšvietimo žibintas'),
    _('Priekinių žibintų komplektas'),
    _('Priekinių žibintų plovimo įtaisas'),
    _('Priekinė'),
    _('Priekinė apdailos juosta'),
    _('Priekinė arka'),
    _('Priekinė atidarymo rankenėlė (vidinė)'),
    _('Priekinė atidarymo rankenėlė vidinė'),
    _('Priekinė durų spyna'),
    _('Priekinė dvivietė sėdynė'),
    _('Priekinė garsiakalbio apdaila'),
    _('Priekinė guma sandarinimo (prie stiklo)'),
    _('Priekinė keleivio sėdynė'),
    _('Priekinė kreipenčioji įvorė (-ės) (sailentblokas)'),
    _('Priekinė kėbulo dalis'),
    _('Priekinė laidų tarpinė'),
    _('Priekinė lingė'),
    _('Priekinė mortizatoriaus cilindro apsauga'),
    _('Priekinė pneumatinė (oro) pagalvė'),
    _('Priekinė pneumatinė (oro) pagalvė su amortizatoriumi'),
    _('Priekinė pūslė'),
    _('Priekinė sandarinimo guma (ant durų)'),
    _('Priekinė sandarinimo guma ant kėbulo'),
    _('Priekinė spynos kilpa'),
    _('Priekinė spyruoklė'),
    _('Priekinė spyruoklės guminė atrama'),
    _('Priekinė stabdžių disko apsauga'),
    _('Priekinė stabilizatoriaus traukė'),
    _('Priekinė stebulė'),
    _('Priekinė svirtis'),
    _('Priekinė uždarymo rankena/ apdaila'),
    _('Priekinė užrakinimo spynelė (prie rankenos)'),
    _('Priekinė vairuotojo sėdynė'),
    _('Priekinė šakė'),
    _('Priekinės arkos apdaila'),
    _('Priekinės durys'),
    _('Priekinės durys (dvidurio)'),
    _('Priekinės keleivio sėdynės padas'),
    _('Priekinės orinės pakabos vamzdelis'),
    _('Priekinės pakabos aukščio daviklio svirtelė'),
    _('Priekinės pakabos aukščio daviklis'),
    _('Priekinės spynos varikliukas'),
    _('Priekinės sėdynės galvos atrama'),
    _('Priekinės vairuotojo sėdynės padas'),
    _('Priekinės važiuoklės dugno apsauga'),
    _('Priekinės važiuoklės komplektas'),
    _('Priekio detalių komplektas'),
    _('Prietaisų skydelio apdaila'),
    _('Prietaisų skydelis'),
    _('Priešrūkinio žibinto apdaila/ grotelės'),
    _('Priešrūkinio žibinto dalis'),
    _('Priešrūkinio žibinto laikiklis'),
    _('Priešrūkinio žibinto lemputė'),
    _('Priešrūkinis žibintas gale'),
    _('Priešrūkinis žibintas priekyje'),
    _('Priešrūkinių žibintų jungtukas'),
    _('Priešrūkinių žibintų komplektas'),
    _('Pritaikytas neįgaliems'),
    _('Pritemstantis veidrodėlis'),
    _('Pritraukėjas galinio dangčio'),
    _('Pritraukėjas šoninių slankiojančių durų'),
    _('Pritraukėjas/ solenoidas'),
    _('Prožektorius'),
    _('Puodelių laikiklio guminis paklotėlis'),
    _('Puodelių laikiklis (gale)'),
    _('Puodelių laikiklis (priekyje)'),
    _('Purkštukas (-ai) (forsunkė (-ės)'),
    _('Purkštukų (forsunkių) komplektas'),
    _('Purkštukų komplektas'),
    _('Pusašiai'),
    _('Pusašio mova'),
    _('Pusašio pakabinamas guolis'),
    _('Pusašio pakabinamo guolio kronšteinas'),
    _('R 12 anglies pluošto ratlankis (-iai)'),
    _('R 12 plieninis štampuotas ratlankis (-iai)'),
    _('R 12 vasarinė C padanga (-os)'),
    _('R 12 vasarinės padanga (-os)'),
    _('R 12 žieminė C su dygliais padanga (-os)'),
    _('R 12 žieminė padanga (-os)'),
    _('R 12 žieminė su dygliais padanga (-os)'),
    _('R 12 žieminės C padanga (-os)'),
    _('R 13 anglies pluošto ratlankis (-iai)'),
    _('R 13 plieninis štampuotas ratlankis (-iai)'),
    _('R 13 vasarinė C padanga (-os)'),
    _('R 13 vasarinės padanga (-os)'),
    _('R 13 žieminė C su dygliais padanga (-os)'),
    _('R 13 žieminė padanga (-os)'),
    _('R 13 žieminė su dygliais padanga (-os)'),
    _('R 13 žieminės C padanga (-os)'),
    _('R 14 anglies pluošto ratlankis (-iai)'),
    _('R 14 plieninis štampuotas ratlankis (-iai)'),
    _('R 14 vasarinė C padanga (-os)'),
    _('R 14 vasarinės padanga (-os)'),
    _('R 14 žieminė C su dygliais padanga (-os)'),
    _('R 14 žieminė padanga (-os)'),
    _('R 14 žieminė su dygliais padanga (-os)'),
    _('R 14 žieminės C padanga (-os)'),
    _('R 15 anglies pluošto ratlankis (-iai)'),
    _('R 15 plieninis štampuotas ratlankis (-iai)'),
    _('R 15 vasarinė C padanga (-os)'),
    _('R 15 vasarinės padanga (-os)'),
    _('R 15 žieminė C su dygliais padanga (-os)'),
    _('R 15 žieminė padanga (-os)'),
    _('R 15 žieminė su dygliais padanga (-os)'),
    _('R 15 žieminės C padanga (-os)'),
    _('R 16 anglies pluošto ratlankis (-iai)'),
    _('R 16 plieninis štampuotas ratlankis (-iai)'),
    _('R 16 vasarinė C padanga (-os)'),
    _('R 16 vasarinės padanga (-os)'),
    _('R 16 žieminė C su dygliais padanga (-os)'),
    _('R 16 žieminė padanga (-os)'),
    _('R 16 žieminė su dygliais padanga (-os)'),
    _('R 16 žieminės C padanga (-os)'),
    _('R 17 anglies pluošto ratlankis (-iai)'),
    _('R 17 plieninis štampuotas ratlankis (-iai)'),
    _('R 17 vasarinė C padanga (-os)'),
    _('R 17 vasarinės padanga (-os)'),
    _('R 17 žieminė C su dygliais padanga (-os)'),
    _('R 17 žieminė padanga (-os)'),
    _('R 17 žieminė su dygliais padanga (-os)'),
    _('R 17 žieminės C padanga (-os)'),
    _('R 18 anglies pluošto ratlankis (-iai)'),
    _('R 18 vasarinė C padanga (-os)'),
    _('R 18 vasarinės padanga (-os)'),
    _('R 18 žieminė C su dygliais padanga (-os)'),
    _('R 18 žieminė padanga (-os)'),
    _('R 18 žieminė su dygliais padanga (-os)'),
    _('R 18 žieminės C padanga (-os)'),
    _('R 19 anglies pluošto ratlankis (-iai)'),
    _('R 19 vasarinės padanga (-os)'),
    _('R 19 žieminė padanga (-os)'),
    _('R 19 žieminė su dygliais padanga (-os)'),
    _('R 20 anglies pluošto ratlankis (-iai)'),
    _('R 20 vasarinės padanga (-os)'),
    _('R 20 žieminė padanga (-os)'),
    _('R 20 žieminė su dygliais padanga (-os)'),
    _('R 21 anglies pluošto ratlankis (-iai)'),
    _('R 21 vasarinės padanga (-os)'),
    _('R 21 žieminė padanga (-os)'),
    _('R 21 žieminė su dygliais padanga (-os)'),
    _('R 22 anglies pluošto ratlankis (-iai)'),
    _('R 22 vasarinės padanga (-os)'),
    _('R 22 žieminė padanga (-os)'),
    _('R 22 žieminė su dygliais padanga (-os)'),
    _('Radiatoriaus (-ių) laikiklis/ kronšteinas'),
    _('Radiatoriaus grotelės'),
    _('Radiatoriaus oro nukreipėjas (-ai)'),
    _('Radiatorių apdaila'),
    _('Radiatorių komplektas'),
    _('Radiatorių panelė (televizorius)'),
    _('Raktas ratų varžtams'),
    _('Rankena atidarymo išorinė'),
    _('Rankena atidarymo vidinė'),
    _('Rankenos apdaila oda/medžiaga'),
    _('Rankenėlių komplektas'),
    _('Rankenėlė atidarymo vidinė'),
    _('Rankenėlė galinė'),
    _('Rankenėlė priekinė'),
    _('Rankenėlės'),
    _('Rankinio atleidimo rankenėlė'),
    _('Rankinio kaladėlės'),
    _('Rankinio stabdžio daviklis'),
    _('Rankinio stabdžio jungtukas'),
    _('Rankinio stabdžio valdymo blokas'),
    _('Rankinio tvirtinimo kronšteinas (salone)'),
    _('Rankinis užvedimas'),
    _('Ratų formulė'),
    _('Ratų išnešimo keitikliai (rastafkės)'),
    _('Ratų skersmuo, coliais'),
    _('Ratų varžtų/ veržlių dangtelis (-iai)'),
    _('Razetė priekabai (kištukinis lizdas)'),
    _('Razetės priekabai perėjimas (kištukinio lizdo)'),
    _('Reduktorius (dujų įrangos)'),
    _('Ribotuvas bagažinės durų atvėrimo'),
    _('Ribotuvas galinio borto atvėrimo'),
    _('Ribotuvas galinių durų atvėrimo'),
    _('Ribotuvas priekinių durų atvėrimo'),
    _('Ribotuvas slankiojančių durų atvėrimo'),
    _('Rida su vienu įkrovimu, km'),
    _('Ritinėlio kreiptuvas apatinis/ vyris apatinis'),
    _('Ritinėlio kreiptuvas vidurinis/ vyris vidurinis'),
    _('Ritinėlio kreiptuvas viršutinis/ vyris viršutinis'),
    _('Ritinėlių kreiptuvų/ vyrių komplektas'),
    _('Rėlių montavimo blokas'),
    _('Rėmas'),
    _('Rėmas stoglangio'),
    _('Rėmelis'),
    _('Rūko žibintai'),
    _('SRS oro pagalvės'),
    _('Sagtis diržo galine'),
    _('Sagtis diržo priekinė'),
    _('Sagtis diržo vidurinė (gale)'),
    _('Salono apšvietimo rėlė'),
    _('Salono pečiukas'),
    _('Salono pečiuko ventiliatoriaus rėlė'),
    _('Salono temperatūros daviklis'),
    _('Sandarinimo guma priekinių durų (ant kėbulo)'),
    _('Sankabos pedalo tvirtinimo kronšteinas'),
    _('Sankabos skysčio išsiplėtimo bakelis'),
    _('Sankabos skysčio lygio daviklis'),
    _('Sankabos vamzdelis (-iai)/ žarna (-os)'),
    _('Saugiklių blokas'),
    _('Saugiklių dėžė (komplektas)'),
    _('Saugos diržas (lubose)'),
    _('Saugos diržas galinis'),
    _('Saugos diržas priekinis'),
    _('Saugos diržas trečios eilės'),
    _('Saugos diržas vidurinis (gale)'),
    _('Saugos diržo apdaila'),
    _('Saugos diržo reguliavimo varikliukas'),
    _('Saugos diržų įspėjimo rėlė'),
    _('Saulės šviesos daviklis'),
    _('Savęs balansavimas'),
    _('Sedynių šildymo jungtukas'),
    _('Sedynės apdaila'),
    _('Sedynės nugaros atramos spyna'),
    _('Sedynės reguliatorių apdaila'),
    _('Selenoidinis vožtuvas'),
    _('Serviso knygelė'),
    _('Sezoniškumas'),
    _('Signalizacijos rėlė'),
    _('Skaidraus stiklo priekiniai žibintai'),
    _('Skaitmeninis prietaisų skydelis'),
    _('Skersinė (reaktyvinė) traukė'),
    _('Skirtas bet kokiam paviršiui'),
    _('Skirtas tvirtam paviršiui'),
    _('Sklendės padėties daviklis'),
    _('Sklendės valdymo varikliukas'),
    _('Skriejikas (bėgunokas)'),
    _('Skriemulys alkūninio veleno'),
    _('Skydelio nuo saulės laikiklis'),
    _('Skydelis nuo saulės'),
    _('Skėčio laikiklis'),
    _('Slankiojančių durų atidarymo rankenėlė vidinė'),
    _('Slankiojančių durų atvėrimo/ užvėrimo daviklis (varlytė)'),
    _('Slankiojančių durų el. lango pakėlimo mechanizmas be varikliuko'),
    _('Slankiojančių durų sandarinimo guma (ant kėbulo)'),
    _('Slankiojančių durų spyna'),
    _('Slankiojančių durų stiklas'),
    _('Slankiojančių durų troselis'),
    _('Slenksčiai'),
    _('Slenksčiai visureigiams (džipams)'),
    _('Slenksčio dalis'),
    _('Slidė (-ės) priekinės keleivio sėdynės'),
    _('Slidė (-ės) priekinės vairuotojo sėdynės'),
    _('Slidės apdaila'),
    _('Slidės apdaila galinės sėdynės'),
    _('Slidės apdaila priekinės keleivio sėdynės'),
    _('Slidės apdaila priekinės vairuotojo sėdynės'),
    _('Slidžių maišas'),
    _('Slėpti iš aukcionų'),
    _('Smagratis (plaukiojantis/ dviejų masių)'),
    _('Smūginis degalų blokavimo daviklis'),
    _('Sparno posūkio žibintas'),
    _('Sparno užbaigimas'),
    _('Sparnų praplatinimai'),
    _('Spidometras (prietaisų skydelis)'),
    _('Spidometro (prietaisų skydelio) trosas'),
    _('Spoileris galinio dangčio'),
    _('Sportinės padangos'),
    _('Sportinės sėdynės'),
    _('Spyna galinio dangčio'),
    _('Spyna variklio dangčio'),
    _('Spynelė galinio dangčio (išorėje)'),
    _('Spynos varikliukas galinio dangčio'),
    _('Spyruoklė (-ės) galinio dangčio'),
    _('Spyruoklės atrama (bliūdelis)'),
    _('Spyruoklės atrama (viršutinė)'),
    _('Srovės išlyginimo rėlė'),
    _('Stabdzių suporto spyruoklė/ prispaudėjas (priekis)'),
    _('Stabdžių aušinimo oro kanalas'),
    _('Stabdžių būgnas (galinis)'),
    _('Stabdžių būgnas (priekinis)'),
    _('Stabdžių diskai'),
    _('Stabdžių el. laidai'),
    _('Stabdžių intensyvumo (svorio) reguliatorius'),
    _('Stabdžių kaladėlių apkaba/ laikiklis (galas)'),
    _('Stabdžių kaladėlių apkaba/ laikiklis (priekis)'),
    _('Stabdžių kaladėlių nusidėvėjimo daviklis'),
    _('Stabdžių kaladėlės (Priekinės)'),
    _('Stabdžių kaladėlės (galinės)'),
    _('Stabdžių kitos dalys'),
    _('Stabdžių pedalas'),
    _('Stabdžių pedalo daviklis'),
    _('Stabdžių pedalo laikiklis'),
    _('Stabdžių sistemos valdymo blokas'),
    _('Stabdžių skysčio išsiplėtimo bakelis'),
    _('Stabdžių suportai'),
    _('Stabdžių suporto spyruoklė/ prispaudėjas (galas)'),
    _('Stabdžių vakuumo pūslė'),
    _('Stabdžių vamzdeliai/ žarnelės'),
    _('Stabdžių vamzdelis (-iai)/ žarna (-os)'),
    _('Stabilumo kontrolės sistema'),
    _('Stalčiukas'),
    _('Starterio detalė (-ės)'),
    _('Starterio mova/ įvorė'),
    _('Stebulė su užraktu (blokiruotė)'),
    _('Stebulės'),
    _('Stiklo kėbule (fortkės) atidarymo el. varikliukas'),
    _('Stiklo kėbule (fortkės) jungtukas'),
    _('Stiklo šildymo elektra jungtukas'),
    _('Stogo "ragų" skersiniai'),
    _('Stogo apmušalai'),
    _('Stogo bagažinė'),
    _('Stogo bagažinės laikikliai'),
    _('Stogo oro pagalvė (užuolaida)'),
    _('Stogo užraktas'),
    _('Stūmokliai'),
    _('Stūmoklio žiedas (-ai)'),
    _('Stūmoklis (-iai)'),
    _('Stūmoklis su švaistikliu'),
    _('Sudedamo stogo vamzdelis (-ai)/ žarna (-os)'),
    _('Sulankstomas rėmas'),
    _('Susidūrimo prevencijos sistema'),
    _('Sėdimų vietų skaičius'),
    _('Sėdynes pakėlimo mechanizmas'),
    _('Sėdynių / durų apdailų komplektas'),
    _('Sėdynių atminties jungtukas (-ai)'),
    _('Sėdynių komplektas'),
    _('Sėdynių reguliavimo jungtukas (-ai)'),
    _('Sėdynių šildymo rėlė'),
    _('Sėdynė'),
    _('Sėdynės'),
    _('Sėdynės instaliacija'),
    _('Sėdynės nugaros atramos atlenkimo rankenėlė'),
    _('Sėdynės oro pagalvė'),
    _('Sėdynės reguliavimo rankenėlė'),
    _('Sėdynės reguliavimo ratukas'),
    _('Sėdynės slėgio daviklis'),
    _('Sėdynės valdymo blokas'),
    _('Sėdynės valdymo varikliukas'),
    _('Sėdynės ventiliatorius/ putikas'),
    _('Sėdynės, atlošėliai'),
    _('Tarpai tarp skylių'),
    _('Tarpinė galinių laidų'),
    _('Tarpinė priekinių laidų'),
    _('Tekstinė paieška'),
    _('Tekstinė paieška / Detalės kodas'),
    _('Telefono klaviatūra'),
    _('Tepalo filtro laikiklis/ aušintuvas'),
    _('Tepalo lygio matuoklė'),
    _('Tepalo paėmimo vamzdelis (karteryje)'),
    _('Tepalo siurblio grandinė'),
    _('Tepalo slėgio daviklis'),
    _('Tepalo slėgio rėlė'),
    _('Tepalo temperatūros matuoklis'),
    _('Tepalo užpylimo angos dangtelis'),
    _('Tepalo užpylimo vamzdelis'),
    _('Tepimo vamzdelis (-iai)/ žarna (-os)'),
    _('Tinka su B kat. teisėmis'),
    _('Tolimųjų šviesų asistentas'),
    _('Tr. priem. markė'),
    _('Transmisijos tepalo aušintuvas'),
    _('Traukos kontrolės sistema'),
    _('Trečia eilė sėdynių'),
    _('Trečios eilės kilimėlis'),
    _('Trečios eilės sėdynių galvos atrama'),
    _('Trikampis stiklas kėbulo priekyje'),
    _('Troselis priekinių durų'),
    _('Troselis variklio dangčio spynos'),
    _('Turbinos slėgio matuoklis'),
    _('Turėklas (viršutinė apdaila)'),
    _('Tuščios eigos rėlė'),
    _('Tvirtinimo taškai'),
    _('Tvirtinimo varžtas (atsarginio rato)'),
    _('Uždarymo rankena (galinio dangčio)'),
    _('Užrakinimo spynelė (prie rankenos)'),
    _('Užuolaida (štorkė)'),
    _('Užuolaidos (štorkės) laikiklis'),
    _('Užuolaidos (štorkės) varikliukas'),
    _('Užvedimo komplektas'),
    _('Užvedimo kortelės skaitytuvas'),
    _('Užvedimo raktas (raktelis)/ kortelė'),
    _('Užvedimo rėlė'),
    _('Užvedimo spynelė'),
    _('Užvedimo spynelės kontaktai'),
    _('Užvedimo- blokavimo rėlė'),
    _('Vairo ašies apdaila'),
    _('Vairo kolonėle'),
    _('Vairo kolonėlės elektrinė dalis'),
    _('Vairo kolonėlės mechaninė dalis'),
    _('Vairo kolonėlės tvirtinimo kronšteinas'),
    _('Vairo kolonėlės valdymo blokas'),
    _('Vairo oro pagalvė'),
    _('Vairo oro pagalvės dangtelis'),
    _('Vairo padėties (kampo) daviklis'),
    _('Vairo padėties el. varikliukas'),
    _('Vairo padėties reguliavimo jungtukas'),
    _('Vairo padėties valdymo rankenėlė'),
    _('Vairo padėtis'),
    _('Vairo rato ašies komplektas'),
    _('Vairo rato ašies kryžminė jungtis'),
    _('Vairo rato ašis'),
    _('Vairo stiprintuvo diržas'),
    _('Vairo stiprintuvo diržo įtempėjas'),
    _('Vairo stiprintuvo siurblio tvirtinimo kronšteinas'),
    _('Vairo stiprintuvo skysčio bakelis'),
    _('Vairo stiprintuvo žarna (-os)/ vamzdelis (-iai)'),
    _('Vairo traukė'),
    _('Vairo traukės antgalis'),
    _('Vairo traukės apsuaga (guminė)'),
    _('Vairo užraktas'),
    _('Vaistinėlė'),
    _('Vaizdo kamera veidrodėlyje'),
    _('Vaizdo kamera veidrodėlyje (dvidurio)'),
    _('Vakuuminis vožtuvas'),
    _('Vakuumo vamzdelis (-ai)/ žarna (-os)'),
    _('Vakuumo vožtuvas'),
    _('Valdymo bloko aušintuvas'),
    _('Valytuvų apdaila (-os)'),
    _('Valytuvų greičio jungtukas'),
    _('Valytuvų jungtukas'),
    _('Valytuvų komplektas'),
    _('Valytuvų mechanizmas (trapecija)'),
    _('Valytuvų mechanizmo komplektas'),
    _('Valytuvų rankenėlė'),
    _('Valytuvų varikliukas'),
    _('Vamzdeliai/žarnelės'),
    _('Vandens nubėgimo žarna/vamzdelis'),
    _('Variklio aušinimo vamzdelis (-ai)/ žarna (-os)'),
    _('Variklio dangčio (kapoto) rankenėlė'),
    _('Variklio dangčio atvėrimo/ užvėrimo daviklis (varlytė)'),
    _('Variklio galvutė'),
    _('Variklio gesinimo sklendė'),
    _('Variklio kronšteinas'),
    _('Variklio pagalvė'),
    _('Variklio pagalvės vakuuminis vožtuvas'),
    _('Variklio termo izoliacija (apsauga nuo karščio)'),
    _('Variklio tvirtinimo kronšteinas'),
    _('Varikliukas priekinio langų pakėlėjo'),
    _('Varikliukas šoninių slankiojančių durų'),
    _('Varžtai/ veržlės'),
    _('Vasarinių padangų komplektas'),
    _('Važiuoklės aukščio/ standumo reguliavimo jungtukas'),
    _('Veidrodelių valdymo blokas'),
    _('Veidrodėliai'),
    _('Veidrodėlio dalys'),
    _('Veidrodėlio dalys (dvidurio)'),
    _('Veidrodėlio plastikinė apdaila'),
    _('Veidrodėlio plastikinė apdaila (dvidurio)'),
    _('Veidrodėlio stiklas'),
    _('Veidrodėlio stiklas (dvidurio)'),
    _('Veidrodėlis (elektra valdomas)'),
    _('Veidrodėlis (elektra valdomas) (dvidurio)'),
    _('Veidrodėlis (mechaninis)'),
    _('Veidrodėlis (mechaninis) (dvidurio)'),
    _('Veidrodėlių jungtukas'),
    _('Veidrodėlių jungtuko apdaila'),
    _('Veidrodėlių šildymo jungtukas'),
    _('Veliūro salonas'),
    _('Ventilecinės grotelės'),
    _('Ventiliatoriaus (-ių) valdymo blokas'),
    _('Ventiliatoriaus sparnuotė'),
    _('Ventiliatorius/ putikas priekinėse duryse'),
    _('Ventiliatorių komplektas'),
    _('Ventiliuojamos sėdynės'),
    _('Video įranga'),
    _('Vidinio pusašio šarnyro (granatos) guma'),
    _('Vidinis pusašio šarnyras (granata)'),
    _('Vidinė atmintis'),
    _('Vidurinė dugno apsauga'),
    _('Vidurinė pūslė'),
    _('Vikšrinis'),
    _('Virtualūs veidrodėliai'),
    _('Virtuvėlė'),
    _('Viršutinė apdaila (prie lango)'),
    _('Viršutinė dalis radiatorių panelės (televizoriaus)'),
    _('Viršutinė slidė'),
    _('Visureigių padangos'),
    _('Vožtuvas (-ai)'),
    _('Vožtuvas (elektro magnetinis)'),
    _('Vožtuvas vakuuminis'),
    _('Vožtuvų kėliklis (-iai) (karomislas (-ai))'),
    _('Vyris (-iai) galinio dangčio'),
    _('Vyris (-iai) variklio dangčio'),
    _('Vyriškas/moteriškas'),
    _('Vėjo deflektorius'),
    _('Yra greitojo įkrovimo jungtis'),
    _('Įkalnės stabdis'),
    _('Įkrovimo laikas, val.'),
    _('Įkrovimo rėlė'),
    _('Įpurškimo kolektorius'),
    _('Įpurškimo sistema'),
    _('Įpurškimo valdymo blokas'),
    _('Įrankių daiktadėžė'),
    _('Įrankių dėžė'),
    _('Įrankių komplektas'),
    _('Įsiurbiamo oro temperatūros daviklis'),
    _('Įsiurbimo rezonatorius'),
    _('Įtampos keitiklis/ keitimo modulis'),
    _('Įveikiama įkalnė °'),
    _('Šakės'),
    _('Šaldymo įranga'),
    _('Šaldymo įranga (krovininis automobilis)'),
    _('Šaldytuvas'),
    _('Šalis'),
    _('Šalmo tipas'),
    _('Šarnyras'),
    _('Šerdesas (kaištis)'),
    _('Šildomas priekinis stiklas'),
    _('Šildomas vairas'),
    _('Šildomi veidrodėliai'),
    _('Šildomos rankenos'),
    _('Šildomos sėdynės'),
    _('Šildymo radiatoriaus vožtuvas (-ai) (kiaušiniai)'),
    _('Šildytuvas aušinimo skysčio'),
    _('Šilumos siurblys'),
    _('Šoninio garsiakalbio apdaila'),
    _('Šoninio garsiakalbio rėmelis'),
    _('Šoninio poslinkio mechanizmas'),
    _('Šoninis apdailos skydas'),
    _('Šoninis bortas'),
    _('Šoninis stiklas kėbulo viduryje'),
    _('Šoninių (slankiojančių) durų instaliacija'),
    _('Šoninių durų'),
    _('Šoninių slankiojančių durų ECU modulis'),
    _('Šoninių slankiojančių durų uždarymo/ atidarymo jungtukas'),
    _('Šoninė apdaila (galinė)'),
    _('Šoninė apdaila (prie lango)'),
    _('Šoninė apdaila (priekinė)'),
    _('Šoninė apdaila prie galinės sėdynės (apačia)'),
    _('Šoninė apdaila prie galinės sėdynės (viršus)'),
    _('Šoninė dalis radiatorių panelės (televizoriaus)'),
    _('Šoninė dugno apsauga'),
    _('Šoninė oro pagalvė'),
    _('Šoninės oro grotelės'),
    _('Šoninės slankiojančios durys'),
    _('Švaistiklis'),
    _('Šviesų jungtukas'),
    _('Šviesų modulis'),
    _('Šviesų rėlė'),
    _('Žaliuzė kuzavo'),
    _('Žaliuzės'),
    _('Žarna (-os)/ vamzdis (-džiai)'),
    _('Žarna alsuoklio'),
    _('Žema kabina'),
    _('Žemintos pavaros'),
    _('Žemo dažnio garsiakalbio grotelės/ dangtelis'),
    _('Žemo dažnio garsiakalbis'),
    _('Žemų dažnių garsiakalbis'),
    _('Žibintai'),
    _('Žibintai „Xenon“'),
    _('Žibinto apdaila (galinio)'),
    _('Žibinto blokelis/ (xenon blokelis)'),
    _('Žibintų apiplovimo bakelis'),
    _('Žibintų apiplovimo jungtukas'),
    _('Žibintų apiplovimo purkštukas (-ai)'),
    _('Žibintų apiplovimo purkštukų dangtelis'),
    _('Žibintų apiplovimo rėlė'),
    _('Žibintų apiplovimo skysčio siurbliukas'),
    _('Žibintų apiplovimo skysčio žarnelė (-ės)'),
    _('Žibintų aukščio reguliavimo jungtukas'),
    _('Žibintų aukščio reguliavimo varikliukas'),
    _('Žibintų valytuvas'),
    _('Žibintų valytuvų jungtukas'),
    _('Žibintų valytuvų kojelių komplektas'),
    _('Žibintų valytuvų kojelė'),
    _('Žibintų valytuvų varikliukas'),
    _('Žieminių padangų komplektas'),
    _('Žieminės dygliuotos'),
    _('Žvaigždutės'),
    _('Žvakių pakaitinimo rėlė'),
    _('Žvakė (-ės)'),
    _('Žvakės (-ių) laidas (-ai)'),
]

# Panelių laukų REIKŠMĖS iš search_config/*.json (Šalmai, 2 ašys, ...).
# Rodomos vartotojui, todėl verčiamos; į URL keliauja originalas.
PANEL_FIELD_OPTIONS = [
    _('1 ašis'),
    _('2 ašys'),
    _('3 ašys'),
    _('4 ašys'),
    _('>3 ašių'),
    _('>4 ašių'),
    _('Akmens smulkinimo mašina'),
    _('Akmenė'),
    _('Akėčios'),
    _('Alkūninis keltuvas'),
    _('Anglies pluoštas'),
    _('Anykščiai'),
    _('Apsaugos sistemų montavimas'),
    _('Asenizacinė mašina'),
    _('Asenizacinės mašinos'),
    _('Asfaloto klojimo mašinos'),
    _('Atliekų (šiukšlių) konteineriai'),
    _('Auksinė'),
    _('Autobusas virš 8 vietų'),
    _('Autogido firminė atributika'),
    _('Automatinė'),
    _('Automobilinis bokštelis'),
    _('Automobilinė priekaba'),
    _('Automobiliui vežti'),
    _('Automobilių signalizacija'),
    _('Automobilių supirkimas'),
    _('Automobilių valstybiniai numeriai'),
    _('Automobilvežio'),
    _('Automobilvežis'),
    _('Autoservisų įrangos aptarnavimas'),
    _('Autovėžis'),
    _('Baidarė/Kanoja'),
    _('Be defektų'),
    _('Benzinas/Gamtinės dujos'),
    _('Benzonvėžis'),
    _('Betono gamybos įrenginys'),
    _('Betono maišyklės'),
    _('Betonvežio'),
    _('Betonvežis'),
    _('Birštonas'),
    _('Biržai'),
    _('Bortinė'),
    _('Bortinė su tentu'),
    _('Bulvių kasamosios'),
    _('Burlentė/Banglentė'),
    _('Cisterninė'),
    _('Dalių supirkimas'),
    _('Daužtas'),
    _('Degęs'),
    _('Dešinėje'),
    _('Diagnostikos įranga'),
    _('Dujų įranga'),
    _('Dujų įrangos montavimas'),
    _('Dviaukštis'),
    _('Dviejų savaičių'),
    _('Dviračių laikikliai'),
    _('Ekskavatorius vikšrinis'),
    _('Elektriniai vežimėliai'),
    _('Elektrėnai'),
    _('Furgonas, sunkvežimis iki 7,5t.'),
    _('Gargždai'),
    _('Garso aparatūros montavimas'),
    _('Gervė'),
    _('Gervės / kabliai'),
    _('Grėbliai'),
    _('Grūdų džiovinimo įranga'),
    _('Grūdų sandėliavimo įranga'),
    _('Grūdų transportavimo įranga'),
    _('Grūdų valymo įranga'),
    _('Gyvuliams vežti'),
    _('Gyvūliams vežti'),
    _('Hečbekas'),
    _('Hidrauliniai gražtai'),
    _('Hidrauliniai kūjai'),
    _('Hidraulinis grąžtas'),
    _('Hidraulinis kūjis'),
    _('Hidraulinės žirklės'),
    _('Izoterminis kėbulas'),
    _('Išmetimo sistemos Tuning dalys'),
    _('Joniškis'),
    _('Juodkrantė'),
    _('Kairėje'),
    _('Kaišiadorys'),
    _('Kapoklė'),
    _('Karinė technika'),
    _('Katalizatorių supirkimas'),
    _('Kaušai'),
    _('Kaušinis krautuvas'),
    _('Kazlų Rūda'),
    _('Keičiamas kėbulas'),
    _('Keleivių vežimas'),
    _('Kelioniniai krepšiai'),
    _('Kelių tiesimo mašina'),
    _('Kelkraščių priežiūros mašinos'),
    _('Kelmė'),
    _('Kelnės'),
    _('Keturračiams'),
    _('Kiti smulkūs defektai'),
    _('Kiti stambūs defektai'),
    _('Klaipėda'),
    _('Komercinis auto(su būda)'),
    _('Konteinerių sunkvežimis'),
    _('Konteinerių važiuoklė'),
    _('Krovimo ir sandėliavimo technika'),
    _('Krovininė'),
    _('Krovinių gabenimas'),
    _('Krūmapjovė'),
    _('Kupiškis'),
    _('Kuršėnai'),
    _('Kėbulo Styling dalys'),
    _('Kėdainiai'),
    _('Kėlimo platformos'),
    _('Laidai/Laidų komplektai'),
    _('Lengvųjų automobilių remontas'),
    _('Lėkštiniai skutikai'),
    _('Marijampolė'),
    _('Mažeikiai'),
    _('Mechaninė'),
    _('Medicininės pagalbos automobiliai'),
    _('Medkirtė'),
    _('Medvežė'),
    _('Melnragė'),
    _('Miškavežio'),
    _('Miško technika'),
    _('Miško traktorius'),
    _('Miškovežio priekaba'),
    _('Miškovežio puspriekabė'),
    _('Miškovežis'),
    _('Mišrus'),
    _('Molėtai'),
    _('Moteriškas'),
    _('Motociklų motorolerių remontas'),
    _('Motociklų nuoma'),
    _('Motociklų priekabos'),
    _('Motociklų signalizacija'),
    _('Motociklų supirkimas'),
    _('Motorinis pjūklas'),
    _('Mėlyna'),
    _('Mėšlo kratytuvai'),
    _('Naujoji Akmenė'),
    _('Navigacija žemės ūkio technikai'),
    _('Oranžinė'),
    _('Pabradė'),
    _('Padangų supirkimas'),
    _('Pagėgiai'),
    _('Palečių vyniotuvai'),
    _('Palečių šakės'),
    _('Panevėžys'),
    _('Pavarų dėžės defektas'),
    _('Pašarų dalytuvai'),
    _('Pažeistas krušos'),
    _('Pienininkystės ir fermų įrengimai'),
    _('Pienovėžis'),
    _('Pilnavidurės'),
    _('Pirštinės'),
    _('Pjovimo galvutė'),
    _('Pjūklai'),
    _('Plieniniai štampuoti'),
    _('Plungė'),
    _('Plūgai'),
    _('Poliakalės'),
    _('Prancūzija'),
    _('Priekaba, puspriekabė'),
    _('Pripučiamos'),
    _('Purkštuvai pakabinami'),
    _('Purkštuvai prikabinami'),
    _('Puspriekabė'),
    _('Radijas/CB radijo stotelės'),
    _('Radviliškis'),
    _('Ratlankių dangteliai'),
    _('Ratlankių supirkimas'),
    _('Ratų gaubtai'),
    _('Ratų montavimas, padangų remontas'),
    _('Ražieniniai skutikai'),
    _('Rokiškis'),
    _('Sandėliavimo technika'),
    _('Sandėliavimo, krovimo technika'),
    _('Savaeigis žirklinis keltuvas'),
    _('Savaeigė'),
    _('Savaeigės pjaunamosios-smulkintuvai'),
    _('Savaitės'),
    _('Savikrovė Miško priekaba'),
    _('Savivartė'),
    _('Savivarčiai su kabliu'),
    _('Semi-automatinė'),
    _('Servisų įranga/įrankiai'),
    _('Sidabrinė'),
    _('Skaldos rūšiavimo mašina'),
    _('Skaldyklė'),
    _('Skendęs'),
    _('Skysčiu'),
    _('Smėlio'),
    _('Sniego pūtikai'),
    _('Sniego valymo mašinos'),
    _('Srutų laistytuvai'),
    _('Srutų siurbliai'),
    _('Stiklo pluoštas'),
    _('Stiklų tonavimas, keitimas'),
    _('Stogo bagažinės'),
    _('Striukė'),
    _('Strėlės'),
    _('Sunkvežimiams ir autobusams'),
    _('Sunkvežimis'),
    _('Sunkvežimis virš 7,5t.'),
    _('Sunkvežimių supirkimas'),
    _('Sėjamosios'),
    _('Sėjos agregatai'),
    _('Tauragė'),
    _('Techninės pagalbos'),
    _('Techninės pagalbos automobiliai'),
    _('Tekstilės'),
    _('Telšiai'),
    _('Tentinė'),
    _('Trijų dienų'),
    _('Trąšų barstytuvai'),
    _('Turistinė'),
    _('Ukmergė'),
    _('Unia Grudziądz'),
    _('Uždaras'),
    _('Užuolaidinis tentas'),
    _('Vaikiškas'),
    _('Varėna'),
    _('Vasarinės'),
    _('Važiuoklės Tuning dalys'),
    _('Vibracinės plokštės'),
    _('Vibro mašina'),
    _('Vienatūris'),
    _('Vikšrai'),
    _('Vilkaviškis'),
    _('Violetinė'),
    _('Vyriškas'),
    _('Čekija'),
    _('Čioperis / Cruiser / Custom'),
    _('Čioperistams'),
    _('Šakiai'),
    _('Šakinis krautuvas'),
    _('Šaldytuvas'),
    _('Šalmas'),
    _('Šalčininkai'),
    _('Šarvuotas (apsaugos)'),
    _('Šasi'),
    _('Šiauliai'),
    _('Šilalė'),
    _('Šilutė'),
    _('Širvintos'),
    _('Šiukšliavežiai'),
    _('Škoda'),
    _('Šlavimo mašinos'),
    _('Šluotos / šepečiai'),
    _('Švedija'),
    _('Šveicarija'),
    _('Šventoji'),
    _('Švenčionys'),
    _('Žalia'),
    _('Žemės ūkio Padargai'),
    _('Žemės ūkio Savaeigė'),
    _('Žemės ūkio technikos remontas'),
    _('Žemės ūkio technikos supirkimas'),
    _('Žemės ūkio, statybos transportas'),
    _('Žemų dažnių garsiakalbis'),
    _('Žieminės'),
    _('Žirklinis keltuvas'),
    _('Žirklinis krautuvas'),
    _('Žoliapjovė'),
]

# Visos savybės (visų kategorijų) — Equipment.name rodomas per |tdb.
ALL_EQUIPMENT_NAMES = [
    _('360° vaizdo kamera'),
    _('4x4'),
    _('4x4 varantys ratai'),
    _('A/C radiator'),
    _('ABS'),
    _('ADR'),
    _('ADR (hazmat)'),
    _('APVA kompensacija nepanaudota'),
    _('ASR'),
    _('AUX jungtis'),
    _('AWD'),
    _('Additional fuel tank'),
    _('Air conditioning'),
    _('Air suspension'),
    _('Airbag (driver)'),
    _('Airbag (passenger)'),
    _('Airbags'),
    _('Aklosios zonos stebėjimo sistema'),
    _('Alarm'),
    _('Alternator'),
    _('Aluminum floor'),
    _('Aluminum side panels'),
    _('Amortizatoriai'),
    _('Android Auto'),
    _('Ankle protection'),
    _('Antialerginis pamušalas'),
    _('Apple CarPlay'),
    _('Apple CarPlay / Android Auto'),
    _('Apsauginis stogelis'),
    _('Apšildoma kabina'),
    _('Atitraukiamas stogas'),
    _('Atitraukiami šonai'),
    _('Atsarginis ratas'),
    _('Atstumo jutiklių sistema'),
    _('Atstumo palaikymo sistema'),
    _('Audio aparatūra'),
    _('Audio grotuvas'),
    _('Audio system'),
    _('Aukštas'),
    _('Autobusų, sunkvežimių remontas'),
    _('Automatinio parkavimo sistema'),
    _('Automatinė pavarų dėžė'),
    _('Automatiškai užsilenkiantys veidrodėliai'),
    _('Automatiškai įsijungiantys žibintai'),
    _('Automobilis iš Amerikos'),
    _('Autonominis šildymas'),
    _('Autonominis šildymas (webasto)'),
    _('Autopilotas'),
    _('Autopilotas (kruizo kontrolė)'),
    _('Auxiliary heater'),
    _('Avarinio stabdymo sistema'),
    _('Axles'),
    _('Bagažinės uždangalas'),
    _('Bamperių remontas'),
    _('Baterijos garantija'),
    _('Beraktė užvedimo sistema'),
    _('Bevielis telefono krovimas'),
    _('Blind-spot monitoring'),
    _('Blokuojamas diferencialas'),
    _('Bluetooth'),
    _('Borto kompiuteris'),
    _('Brake calipers'),
    _('Brake discs'),
    _('Bucket / grapple'),
    _('Bumper reinforcements'),
    _('Bumpers'),
    _('CB radio įranga'),
    _('CD grotuvas'),
    _('CD keitiklis'),
    _('CE armor — back'),
    _('CE armor — chest'),
    _('CE armor — elbows'),
    _('CE armor — hips'),
    _('CE armor — knees'),
    _('CE armor — shoulders'),
    _('Cabin heater'),
    _('Camshafts'),
    _('Car carrier body'),
    _('Carburetor'),
    _('Cargo straps'),
    _('Central lubrication'),
    _('Centrinis užraktas'),
    _('Chains'),
    _('Climate control'),
    _('Computer'),
    _('Concrete mixer body'),
    _('Connection zipper (jacket↔pants)'),
    _('Container carrier'),
    _('Crane'),
    _('Crane / manipulator'),
    _('Crankshaft'),
    _('Cruise control'),
    _('Cylinder head'),
    _('Cylinders'),
    _('DVD grotuvas'),
    _('Dashboard'),
    _('Daugiafunkcinis vairas'),
    _('Dažymo paslaugos'),
    _('Dempferis'),
    _('Dinaminis posūkių apšvietimas'),
    _('Diskiniai stabdžiai'),
    _('Door panels'),
    _('Doors'),
    _('Double D-ring užsegimas'),
    _('Double cabin'),
    _('Driveshaft'),
    _('Drėgmę sugerianti vidinė danga'),
    _('Dujinė viryklė'),
    _('Durelių pritraukimas'),
    _('Durys gale'),
    _('Durys šone'),
    _('Duslintuvų remontas'),
    _('Dušas'),
    _('Dvigubi ratai'),
    _('Dvipusis energijos perdavimas'),
    _('Dviračių laikikliai'),
    _('EBS'),
    _('ECU / Computer'),
    _('EDSCHA stogas'),
    _('ESP'),
    _('ESP (stabilumo kontrolės sistema)'),
    _('Ekvalaizeris'),
    _('El. langai'),
    _('El. reguliuojami veidrodėliai'),
    _('El. starteris'),
    _('El. sėdynės'),
    _('El. veidrodėliai'),
    _('Electric mirrors'),
    _('Electric steering adjustment'),
    _('Electric windows'),
    _('Elektra reguliuojama vairo padėtis'),
    _('Elektra valdomas bagažinės dangtis'),
    _('Elektra valdomos sėdynės'),
    _('Elektra valdomos sėdynės su atmintimi'),
    _('Elektra šildomas priekinis stiklas'),
    _('Elektrinis starteris'),
    _('Elektronikos diagnostika'),
    _('Elektroninė klimato kontrolė'),
    _('Engine'),
    _('Engine block'),
    _('Engine bracket'),
    _('Engine brake / retarder'),
    _('Engine cradle'),
    _('Exhaust manifold'),
    _('Expandable'),
    _('Fan'),
    _('Fender flares'),
    _('Fenders'),
    _('Final drive'),
    _('Flatbed platform'),
    _('Follow assist'),
    _('For bulk cargo'),
    _('For sale on lease'),
    _('Forks'),
    _('Frame'),
    _('Frame rails'),
    _('Galimybė prijungti papildomą bateriją'),
    _('Galinio vaizdo kamera'),
    _('Galinė dalis'),
    _('Galiojanti techninė apžiūra (TA)'),
    _('Garantija'),
    _('Garso aparatūra'),
    _('Gearbox'),
    _('Generator'),
    _('Geros būklės'),
    _('Gido mikrofonas'),
    _('Glass'),
    _('Greitasis krovimas'),
    _('Greito atsegimo dirželis'),
    _('Greičio palaikymo sistema'),
    _('Greičio variatorius'),
    _('Half-shafts'),
    _('Handlebar'),
    _('Hard-side body'),
    _('Headliner'),
    _('Heated seat'),
    _('Heel protection'),
    _('HiFi audio sistema'),
    _('Hidraulika'),
    _('Hidraulikos diagnostika'),
    _('Hill-start assist'),
    _('Hood'),
    _('Hook / winch'),
    _('Hubs'),
    _('Hump (aerodynamic)'),
    _('Hydraulics'),
    _('ISOFIX (vaiko kėdutės tvirtinimo taškai)'),
    _('Injection system'),
    _('Instrument cluster'),
    _('Insulated body'),
    _('Intake manifold'),
    _('Integruotas ekranas'),
    _('Išsegamas ir skalbiamas pamušalas'),
    _('Juostos palaikymo sistema'),
    _('Kabina'),
    _('Kablys'),
    _('Kaina su vairuotoju'),
    _('Kalnų stabdis'),
    _('Karštas vanduo'),
    _('Kavos aparatas'),
    _('Keičiama'),
    _('Keleivio atlošas'),
    _('Keli raktų komplektai'),
    _('Kelio ženklų atpažinimo sistema'),
    _('Kelioniniai krepsiai'),
    _('Kita'),
    _('Klimato kontrolė'),
    _('Knuckle protector'),
    _('Korteliu skaitytuvas'),
    _('Kritulių jutiklis'),
    _('Krovinio diržai'),
    _('Kruizo kontrolė'),
    _('Kuro žarna'),
    _('Kvėpuojantis pamušalas'),
    _('Kėbulo remontas'),
    _('LCD ekranas'),
    _('LED dienos žibintai'),
    _('LED lights'),
    _('LED žibintai'),
    _('Laisvų rankų įranga'),
    _('Lane assist'),
    _('Laptop compartment'),
    _('Lauko baldai'),
    _('Leather seats'),
    _('Lengvo lydinio ratlankiai'),
    _('Levers'),
    _('Lietuvoje neeksploatuotas'),
    _('Liečiamas ekranas'),
    _('Lift axle'),
    _('Liftas'),
    _('Liftas gale'),
    _('Lights'),
    _('Lingės'),
    _('Linijiniai išėjimai'),
    _('Livestock carrier body'),
    _('Locking differential'),
    _('Long cuff'),
    _('Lopšys'),
    _('Low cabin'),
    _('Lėtintos pavaros'),
    _('MP3 grotuvas'),
    _('Magnetic mount'),
    _('Masažinės sėdynės'),
    _('Matriciniai žibintai'),
    _('Metallic paint'),
    _('Micrometric užsegimas'),
    _('Mini kitchen'),
    _('Mirrors'),
    _('Motociklų, motorolerių remontas'),
    _('Mufflers'),
    _('Multifunkcinis valdymas nuo vairo'),
    _('Naktinio matymo asistentas'),
    _('Navigacija / GPS'),
    _('Navigacija/GPS'),
    _('Navigation'),
    _('Navigation / GPS'),
    _('Nerasojantis stiklas'),
    _('Nesibraižantis stiklas'),
    _('Neveikiantis'),
    _('Not used as taxi'),
    _('Not used in Lithuania'),
    _('Nuimami skruostų pagalvėliai'),
    _('Nuolaidos ilgesniam laikotarpiui'),
    _('Nuomojamas tik su vairuotoju'),
    _('Nuotolinio valdymo pultas'),
    _('Nuotolinis užvedimas'),
    _('Nuovargio įspėjimo sistema'),
    _('Odinis salonas'),
    _('Oil cooler'),
    _('Onboard computer'),
    _('Open to trade'),
    _('Oro kondicionierius'),
    _('Oro pagalvės'),
    _('Padangų slėgio stebėjimo sistema'),
    _('Padidinta variklio galia'),
    _('Pagalbos iškvietimo sistema (eCall)'),
    _('Pakabinamas'),
    _('Pakeliama ašis'),
    _('Palm slider'),
    _('Palydovinė sekimo sistema'),
    _('Panoraminis stogas'),
    _('Papildoma audio įranga'),
    _('Papildomas hidraulikos vožtuvas'),
    _('Papildomas kuro bakas'),
    _('Parduodama lizingu'),
    _('Parkavimo kojelė'),
    _('Paruoštas autosportui'),
    _('Pasukamas griebtuvas'),
    _('Pavarų dėžių remontas'),
    _('Pavarų perjungimas prie vairo'),
    _('Personal lighting'),
    _('Personal ventilation'),
    _('Pistons'),
    _('Platform body'),
    _('Platforma stumiasi į abi puses'),
    _('Platforma stumiasi į vieną pusę'),
    _('Platus galinis ratas'),
    _('Pneumatinė pakaba'),
    _('Power steering'),
    _('Premium sound system'),
    _('Priekabos stabdys'),
    _('Priekinio vaizdo kamera'),
    _('Priekinis skydelis'),
    _('Priekinis stiklas'),
    _('Priekinių žibintų plovimo įtaisas'),
    _('Prikabinamas'),
    _('Pritaikytas Bluetooth'),
    _('Pritaikytas Pinlock'),
    _('Pritaikytas bekelei'),
    _('Pritaikytas neįgaliems'),
    _('Pritaikytas nešiojantiems akinius'),
    _('Pritemstantis veidrodėlis'),
    _('Projekcinis ekranas ant stiklo (HUD)'),
    _('Pusiau kabina'),
    _('Radiator'),
    _('Radiator grille'),
    _('Rain cover'),
    _('Rankinis užvedimas'),
    _('Ratų montavimas, balansavimas'),
    _('Ratų remontas'),
    _('Rear axle beam'),
    _('Rear doors'),
    _('Reducer / differential'),
    _('Reflective elements'),
    _('Refrigeration unit'),
    _('Refrigerator body'),
    _('Reinforced impact zones'),
    _('Reinforced sole'),
    _('Removable liner'),
    _('Roof'),
    _('Rūko žibintai'),
    _('SRS airbags'),
    _('Salono remontas'),
    _('Savęs balansavimas'),
    _('Seats'),
    _('Seats / Backrests'),
    _('Service book'),
    _('Serviso knygelė'),
    _('Shin protection'),
    _('Shock absorber'),
    _('Short cuff'),
    _('Side airbags'),
    _('Side doors'),
    _('Signalizacija / Imobilaizeris'),
    _('Signalizacija/Imobilaizeris'),
    _('Sills'),
    _('Skaidraus stiklo priekiniai žibintai'),
    _('Skaitmeninis prietaisų skydelis'),
    _('Skelbimas su VIN'),
    _('Skirtas bet kokiam paviršiui'),
    _('Skirtas tvirtam paviršiui'),
    _('Spalvotas ekranas'),
    _('Spare wheel'),
    _('Spoilers'),
    _('Sportinės sėdynės'),
    _('Springs'),
    _('Sprockets'),
    _('Sraigtas'),
    _('Stabilumo kontrolės sistema'),
    _('Start-Stop sistema'),
    _('Start/Stop'),
    _('Starter'),
    _('Starterių, generatorių remontas'),
    _('Stoglangis'),
    _('Stogo bagažinės laikikliai'),
    _('Strap mount'),
    _('Su auto priekaba'),
    _('Su dokumentais'),
    _('Su gerve'),
    _('Su hidrauliniu kranu'),
    _('Su kietu stogu'),
    _('Su palapine'),
    _('Su prieangiu'),
    _('Su priekaba'),
    _('Su tentu'),
    _('Sulankstomas rėmas'),
    _('Sulankstomos atramos'),
    _('Sunroof'),
    _('Susidūrimo prevencijos sistema'),
    _('Swingarm'),
    _('Sėdynė'),
    _('TIR'),
    _('TV ekranas'),
    _('Tachografas'),
    _('Tachograph'),
    _('Tail lift'),
    _('Tamsinti stiklai'),
    _('Tank'),
    _('Tarpaulins'),
    _('Tentas'),
    _('Termografas'),
    _('Thermal liner'),
    _('Thermostat'),
    _('Three-way tipper'),
    _('Tilt cabin'),
    _('Timber carrier body'),
    _('Tipper body'),
    _('Toe slider'),
    _('Tolimųjų šviesų asistentas'),
    _('Touchscreen-compatible'),
    _('Tow hook'),
    _('Trailer brake'),
    _('Trailer hitch'),
    _('Traukos kontrolės sistema'),
    _('Trifazis krovimas'),
    _('Trim parts'),
    _('Trim strips'),
    _('Tualetas'),
    _('Turbinų diagnostika'),
    _('Turn signals'),
    _('Two-way tipper'),
    _('USB'),
    _('USB Type-C jungtis'),
    _('USB jungtis'),
    _('Ultravioletinių spindulių apsauga'),
    _('Vairo stiprintuvas'),
    _('Valdymas balsu'),
    _('Valdymas ratuku'),
    _('Variklio defektas'),
    _('Variklių diagnostika'),
    _('Vasarinių padangų komplektas'),
    _('Važiuoklės remontas'),
    _('Veliūro salonas'),
    _('Ventilation zippers'),
    _('Ventiliuojamos sėdynės'),
    _('Vežame į užsienį'),
    _('Video system'),
    _('Video įranga'),
    _('Vidinis saulės skydelis'),
    _('Vidinė atmintis'),
    _('Vikšrinis'),
    _('Virtualūs veidrodėliai'),
    _('Viscous fan coupling'),
    _('Water pump'),
    _('Water radiator'),
    _('Waterproof'),
    _('Windproof'),
    _('Wiring'),
    _('Wiring / Electrical'),
    _('Xenon lights'),
    _('Įkalnės stabdis'),
    _('Įrankių dėžė'),
    _('Šaldymo įranga'),
    _('Šildomas priekinis stiklas'),
    _('Šildomas stiklas'),
    _('Šildomas vairas'),
    _('Šildomi veidrodėliai'),
    _('Šildomos rankenos'),
    _('Šildomos sėdynės'),
    _('Šilumos siurblys'),
    _('Šoninio poslinkio mechanizmas'),
    _('Žaliuzės'),
    _('Žemintos pavaros'),
    _('Žemų dažnių garsiakalbis'),
    _('Žibintai'),
    _('Žibintai „Xenon“'),
    _('Žieminių padangų komplektas'),
    _('“Subwoofer” valdymas'),
    _('„Webasto“'),
]

# Įrangos registro (equipment_registry) etiketės bei punktai ir
# ratlankių/padangų reikšmės — rodomos formose.
EXTRA_UI_VALUES = [
    _('Antstato detalės'),
    _('Aušinimo detalės'),
    _('Elektros detalės'),
    _('Kėbulas ir įranga'),
    _('Kėbulo detalės'),
    _('Nuomos sąlygos'),
    _('Papildoma įranga'),
    _('Pavaros ir važiuoklė'),
    _('Salono detalės'),
    _('Variklio detalės'),
    _('Važiuoklė'),
    _('Važiuoklė ir paviršius'),
    _('Važiuoklės detalės'),
]
