# Generated by Django 5.0.1 on 2026-08-28 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VeiklosSritis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('tvarka', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Veiklos sritis',
                'verbose_name_plural': 'Veiklos sritys',
                'ordering': ['tvarka', 'pavadinimas'],
            },
        ),
        migrations.CreateModel(
            name='Imone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipas', models.CharField(choices=[('prekiautojas', 'Prekiautojas'), ('servisas', 'Servisas')], default='prekiautojas', max_length=16)),
                ('pavadinimas', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('logotipas', models.ImageField(blank=True, null=True, upload_to='imones/logo/')),
                ('aprasymas', models.TextField(blank=True)),
                ('adresas', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('miestas', models.CharField(blank=True, max_length=100)),
                ('salis', models.CharField(choices=[('LT', 'Lietuva'), ('Kaimyninės šalys', [('LV', 'Latvija'), ('EE', 'Estija'), ('PL', 'Lenkija'), ('DE', 'Vokietija')]), ('Europa', [('IE', 'Airija'), ('AT', 'Austrija'), ('BE', 'Belgija'), ('BG', 'Bulgarija'), ('CZ', 'Čekija'), ('DK', 'Danija'), ('GR', 'Graikija'), ('IS', 'Islandija'), ('ES', 'Ispanija'), ('IT', 'Italija'), ('CY', 'Kipras'), ('HR', 'Kroatija'), ('LI', 'Lichtenšteinas'), ('LU', 'Liuksemburgas'), ('MT', 'Malta'), ('NL', 'Nyderlandai'), ('NO', 'Norvegija'), ('PT', 'Portugalija'), ('FR', 'Prancūzija'), ('RO', 'Rumunija'), ('SK', 'Slovakija'), ('SI', 'Slovėnija'), ('FI', 'Suomija'), ('SE', 'Švedija'), ('CH', 'Šveicarija'), ('HU', 'Vengrija')]), ('Rytų kaimynai', [('BY', 'Baltarusija'), ('MD', 'Moldova'), ('RU', 'Rusija'), ('UA', 'Ukraina')]), ('Importo kryptys', [('AU', 'Australija'), ('GB', 'Didžioji Britanija'), ('GE', 'Gruzija'), ('JP', 'Japonija'), ('US', 'Jungtinės Valstijos'), ('AE', 'Jungtiniai Arabų Emyratai'), ('CA', 'Kanada'), ('KZ', 'Kazachstanas'), ('TR', 'Turkija')])], default='LT', max_length=2)),
                ('telefonas', models.CharField(blank=True, max_length=32)),
                ('el_pastas', models.EmailField(blank=True, max_length=254)),
                ('svetaine', models.URLField(blank=True)),
                ('darbo_laikas', models.JSONField(blank=True, default=dict)),
                ('patvirtinta', models.BooleanField(default=False)),
                ('sukurta', models.DateTimeField(auto_now_add=True)),
                ('atnaujinta', models.DateTimeField(auto_now=True)),
                ('savininkas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imones', to=settings.AUTH_USER_MODEL)),
                ('veiklos', models.ManyToManyField(blank=True, related_name='imones', to='imones.veiklossritis')),
            ],
            options={
                'verbose_name': 'Įmonė',
                'verbose_name_plural': 'Įmonės',
                'ordering': ['pavadinimas'],
            },
        ),
        migrations.CreateModel(
            name='ImonesNuotrauka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuotrauka', models.ImageField(upload_to='imones/')),
                ('tvarka', models.PositiveIntegerField(default=0)),
                ('imone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuotraukos', to='imones.imone')),
            ],
            options={
                'verbose_name': 'Įmonės nuotrauka',
                'verbose_name_plural': 'Įmonės nuotraukos',
                'ordering': ['tvarka', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImonesPaslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=160)),
                ('aprasymas', models.CharField(blank=True, max_length=255)),
                ('trukme_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Trukmė (min.)')),
                ('kaina', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('tvarka', models.PositiveIntegerField(default=0)),
                ('imone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paslaugos', to='imones.imone')),
            ],
            options={
                'verbose_name': 'Įmonės paslauga',
                'verbose_name_plural': 'Įmonės paslaugos',
                'ordering': ['tvarka', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='imone',
            index=models.Index(fields=['patvirtinta', 'tipas'], name='imones_imon_patvirt_bdfbdb_idx'),
        ),
        migrations.AddIndex(
            model_name='imone',
            index=models.Index(fields=['miestas'], name='imones_imon_miestas_1c4241_idx'),
        ),
    ]
