# Generated by Django 5.0.1 on 2026-08-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imones', '0002_veiklos_sritys'),
    ]

    operations = [
        migrations.AddField(
            model_name='imone',
            name='testine',
            field=models.BooleanField(default=False, verbose_name='Testinė'),
        ),
    ]
