# Generated by Django 5.0.1 on 2026-08-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imones', '0004_veiklos_sritys_pilnas'),
    ]

    operations = [
        migrations.AddField(
            model_name='imone',
            name='veikia_nuo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Veikia nuo (metai)'),
        ),
    ]
