# Generated by Django 5.0.1 on 2026-08-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imones', '0006_veiklos_ikonos'),
    ]

    operations = [
        migrations.AddField(
            model_name='imone',
            name='atsiliepimu_kiekis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imone',
            name='rajonas',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='imone',
            name='reitingas',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
