# Generated by Django 5.0.1 on 2026-08-30 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imones', '0007_imone_atsiliepimu_kiekis_imone_rajonas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imone',
            name='atvyksta_pas_klienta',
            field=models.BooleanField(default=False, verbose_name='Atvyksta pas klientą'),
        ),
        migrations.AddField(
            model_name='imone',
            name='dirba_vietoje',
            field=models.BooleanField(default=True, verbose_name='Turi dirbtuvę'),
        ),
        migrations.AddField(
            model_name='imone',
            name='imone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meistrai', to='imones.imone', verbose_name='Priklauso įmonei'),
        ),
        migrations.AddField(
            model_name='imone',
            name='meistras_vardas',
            field=models.CharField(blank=True, max_length=120, verbose_name='Meistro vardas'),
        ),
        migrations.AddField(
            model_name='imone',
            name='specializacija',
            field=models.CharField(blank=True, max_length=120, verbose_name='Specializacija'),
        ),
        migrations.AlterField(
            model_name='imone',
            name='tipas',
            field=models.CharField(choices=[('prekiautojas', 'Prekiautojas'), ('servisas', 'Servisas'), ('meistras', 'Meistras')], default='prekiautojas', max_length=16),
        ),
    ]
