# Generated by Django 5.0.1 on 2025-10-31 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('category', models.CharField(choices=[('interior', 'Interior'), ('electronics', 'Electronics'), ('safety', 'Safety'), ('audio_video', 'Audio/Video'), ('exterior', 'Exterior'), ('other', 'Other Features')], max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Fuel Type',
                'verbose_name_plural': 'Fuel Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Transmission',
                'verbose_name_plural': 'Transmissions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('mileage', models.IntegerField(verbose_name='Mileage (km)')),
                ('first_registration', models.DateField(blank=True, null=True, verbose_name='First Registration Date')),
                ('body_type', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('wagon', 'Wagon/Estate'), ('suv', 'SUV/Crossover'), ('van', 'Van/Minivan'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('pickup', 'Pickup')], max_length=50, verbose_name='Body Type')),
                ('engine_capacity', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Engine Capacity (L)')),
                ('power', models.IntegerField(blank=True, null=True, verbose_name='Power (kW)')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('doors', models.CharField(blank=True, choices=[('2/3', '2/3 doors'), ('4/5', '4/5 doors')], max_length=10, verbose_name='Number of Doors')),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged')], default='used', max_length=20, verbose_name='Condition')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='VIN Code')),
                ('registration_number', models.CharField(blank=True, max_length=20, verbose_name='Registration Number')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (€)')),
                ('negotiable', models.BooleanField(default=False, verbose_name='Price Negotiable')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('features', models.TextField(blank=True, help_text='E.g.: Air conditioning, Alloy wheels', verbose_name='Additional Features')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL (YouTube)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold', 'Sold'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.brand', verbose_name='Brand')),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.fueltype', verbose_name='Fuel Type')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/%Y/%m/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main Image')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['order', '-is_main'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='listings.brand')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'ordering': ['name'],
                'unique_together': {('brand', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.model', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='listing',
            name='transmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.transmission', verbose_name='Transmission'),
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.vehicletype', verbose_name='Vehicle Type'),
        ),
        migrations.AddField(
            model_name='brand',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='listings.vehicletype'),
        ),
        migrations.CreateModel(
            name='ListingEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.equipment')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Listing Equipment',
                'verbose_name_plural': 'Listing Equipment',
                'unique_together': {('listing', 'equipment')},
            },
        ),
    ]
