# Generated by Django 5.0.1 on 2025-11-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(choices=[('LT', 'Lithuania'), ('LV', 'Latvia'), ('EE', 'Estonia'), ('PL', 'Poland'), ('DE', 'Germany'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('AT', 'Austria'), ('CZ', 'Czech Republic'), ('SK', 'Slovakia'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('SE', 'Sweden'), ('DK', 'Denmark'), ('FI', 'Finland'), ('NO', 'Norway'), ('GB', 'United Kingdom'), ('IE', 'Ireland'), ('CH', 'Switzerland')], default='LT', max_length=2, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='listing',
            name='hide_exact_address',
            field=models.BooleanField(default=False, verbose_name='Hide exact address'),
        ),
        migrations.AddField(
            model_name='listing',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
    ]
