# Generated by Django 5.0.1 on 2026-03-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_country_listing_hide_exact_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='engine_capacity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Engine Capacity (L)'),
        ),
    ]
