# Generated by Django 5.0.1 on 2026-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Vehicle Type', 'verbose_name_plural': 'Vehicle Types'},
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
