# Generated by Django 5.0.1 on 2026-03-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Viewed'),
        ),
    ]
