# Generated by Django 5.0.1 on 2026-03-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_savedsearch_last_viewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='last_min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='last_results_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='track_price_drop',
            field=models.BooleanField(default=False, verbose_name='Track price drops'),
        ),
    ]
