# Generated by Django 5.0.1 on 2026-03-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_savedsearch_last_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='defects',
            field=models.CharField(choices=[('none', 'No defects'), ('dented', 'Dented'), ('burned', 'Burned'), ('gearbox_defect', 'Gearbox defect'), ('hail_damage', 'Hail damage'), ('sunken', 'Sunken'), ('engine_defect', 'Engine defect'), ('major_defects', 'Major defects')], default='none', max_length=50, verbose_name='Defects'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('estate', 'Estate/Wagon'), ('minivan', 'Minivan'), ('suv', 'SUV/Crossover'), ('coupe', 'Coupe'), ('commercial', 'Commercial'), ('convertible', 'Convertible'), ('limousine', 'Limousine'), ('pickup', 'Pickup'), ('minibus', 'Minibus'), ('truck', 'Truck/Van'), ('other', 'Other')], max_length=50, verbose_name='Body Type'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('yellow_gold', 'Yellow / Gold'), ('black', 'Black'), ('multicolor', 'Multicolor'), ('blue', 'Blue'), ('orange', 'Orange'), ('red', 'Red / Burgundy'), ('brown_beige', 'Brown / Beige'), ('purple', 'Purple'), ('green_khaki', 'Green / Khaki'), ('other', 'Other')], max_length=50, verbose_name='Color'),
        ),
    ]
