# Generated by Django 5.0.1 on 2026-03-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_defects_alter_listing_body_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='steering',
            field=models.CharField(blank=True, choices=[('left', 'Left-hand drive'), ('right', 'Right-hand drive (UK)')], max_length=10, verbose_name='Steering'),
        ),
    ]
