# Generated by Django 5.0.1 on 2026-03-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_listing_steering'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='climate',
            field=models.CharField(blank=True, choices=[('none', 'No climate control'), ('ac', 'Air conditioning'), ('climate', 'Climate control'), ('dual_climate', 'Dual-zone climate control'), ('triple_climate', 'Triple-zone climate control')], max_length=20, verbose_name='Climate Control'),
        ),
        migrations.AddField(
            model_name='listing',
            name='co2_emission',
            field=models.IntegerField(blank=True, null=True, verbose_name='CO₂ Emission (g/km)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='curb_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Curb Weight (kg)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('fwd', 'Front-wheel drive (FWD)'), ('rwd', 'Rear-wheel drive (RWD)'), ('awd', 'All-wheel drive (AWD/4WD)')], max_length=10, verbose_name='Drive Type'),
        ),
        migrations.AddField(
            model_name='listing',
            name='euro_standard',
            field=models.CharField(blank=True, choices=[('euro1', 'Euro 1'), ('euro2', 'Euro 2'), ('euro3', 'Euro 3'), ('euro4', 'Euro 4'), ('euro5', 'Euro 5'), ('euro6', 'Euro 6'), ('euro6d', 'Euro 6d')], max_length=10, verbose_name='Euro Standard'),
        ),
        migrations.AddField(
            model_name='listing',
            name='fuel_consumption_city',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Fuel Consumption City (l/100km)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='fuel_consumption_combined',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Fuel Consumption Combined (l/100km)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='fuel_consumption_highway',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Fuel Consumption Highway (l/100km)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='origin_country',
            field=models.CharField(blank=True, choices=[('LT', 'Lithuania'), ('LV', 'Latvia'), ('EE', 'Estonia'), ('PL', 'Poland'), ('DE', 'Germany'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('AT', 'Austria'), ('CZ', 'Czech Republic'), ('SK', 'Slovakia'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('SE', 'Sweden'), ('DK', 'Denmark'), ('FI', 'Finland'), ('NO', 'Norway'), ('GB', 'United Kingdom'), ('IE', 'Ireland'), ('CH', 'Switzerland')], max_length=2, verbose_name='Origin Country'),
        ),
        migrations.AddField(
            model_name='listing',
            name='rim_size',
            field=models.CharField(blank=True, choices=[('13', '13"'), ('14', '14"'), ('15', '15"'), ('16', '16"'), ('17', '17"'), ('18', '18"'), ('19', '19"'), ('20', '20"'), ('21', '21"'), ('22', '22"')], max_length=5, verbose_name='Rim Size (inches)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='seats',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('9+', '9+')], max_length=5, verbose_name='Number of Seats'),
        ),
        migrations.AddField(
            model_name='listing',
            name='technical_inspection_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Technical Inspection Month'),
        ),
        migrations.AddField(
            model_name='listing',
            name='technical_inspection_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Technical Inspection Year'),
        ),
    ]
