# Generated by Django 5.0.1 on 2026-03-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listing_climate_listing_co2_emission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rim_size',
            field=models.CharField(blank=True, choices=[('13', '13"'), ('14', '14"'), ('15', '15"'), ('16', '16"'), ('17', '17"'), ('18', '18"'), ('19', '19"'), ('20', '20"'), ('21', '21"'), ('22', '22"'), ('23', '23"'), ('24', '24"')], max_length=5, verbose_name='Rim Size (inches)'),
        ),
    ]
