# Generated by Django 5.0.1 on 2026-04-02 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_listing_rim_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodels', to='listings.model')),
            ],
            options={
                'verbose_name': 'SubModel',
                'verbose_name_plural': 'SubModels',
                'ordering': ['name'],
                'unique_together': {('model', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='submodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.submodel', verbose_name='SubModel'),
        ),
    ]
