# Generated by Django 5.0.1 on 2026-04-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_submodel_listing_submodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2, verbose_name='State (USA)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('LT', 'Lithuania'), ('LV', 'Latvia'), ('EE', 'Estonia'), ('PL', 'Poland'), ('DE', 'Germany'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('AT', 'Austria'), ('CZ', 'Czech Republic'), ('SK', 'Slovakia'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('SE', 'Sweden'), ('DK', 'Denmark'), ('FI', 'Finland'), ('NO', 'Norway'), ('GB', 'United Kingdom'), ('IE', 'Ireland'), ('CH', 'Switzerland')], default='LT', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='origin_country',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('LT', 'Lithuania'), ('LV', 'Latvia'), ('EE', 'Estonia'), ('PL', 'Poland'), ('DE', 'Germany'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('AT', 'Austria'), ('CZ', 'Czech Republic'), ('SK', 'Slovakia'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('SE', 'Sweden'), ('DK', 'Denmark'), ('FI', 'Finland'), ('NO', 'Norway'), ('GB', 'United Kingdom'), ('IE', 'Ireland'), ('CH', 'Switzerland')], max_length=2, verbose_name='Origin Country'),
        ),
    ]
