# Generated by Django 5.0.1 on 2026-04-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_listing_state_alter_listing_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='last_boosted_at',
            field=models.DateTimeField(blank=True, help_text='When the listing was last boosted (1h cooldown per seller)', null=True, verbose_name='Last Boosted At'),
        ),
        migrations.AddField(
            model_name='listing',
            name='star_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the star premium expires', null=True, verbose_name='Star Expires At'),
        ),
        migrations.AddField(
            model_name='listing',
            name='star_level',
            field=models.IntegerField(choices=[(0, 'No Stars'), (1, '⭐ One Star (7 days)'), (2, '⭐⭐ Two Stars (30 days)')], default=0, help_text='0 = none, 1 = ⭐ (7 days), 2 = ⭐⭐ (30 days)', verbose_name='Star Level'),
        ),
    ]
