# Generated by Django 5.0.1 on 2026-04-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_listing_last_boosted_at_listing_star_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='When the listing was last activated', null=True, verbose_name='Activated At'),
        ),
        migrations.AddField(
            model_name='listing',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the listing will auto-expire', null=True, verbose_name='Expires At'),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Reminder Sent'),
        ),
        migrations.AddField(
            model_name='listing',
            name='reservation_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Reservation note'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_boosted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Boosted At'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='star_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Star Expires At'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Juodraštis'), ('active', 'Aktyvus'), ('reserved', 'Rezervuotas'), ('expired', 'Neaktyvus'), ('sold', 'Parduotas'), ('archived', 'Archyvuotas')], default='draft', max_length=20),
        ),
    ]
