# Generated by Django 5.0.1 on 2026-04-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_listing_activated_at_listing_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)')], default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('LT', 'Lithuania'), ('LV', 'Latvia'), ('EE', 'Estonia'), ('PL', 'Poland'), ('DE', 'Germany'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('AT', 'Austria'), ('CZ', 'Czech Republic'), ('SK', 'Slovakia'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('SE', 'Sweden'), ('DK', 'Denmark'), ('FI', 'Finland'), ('NO', 'Norway'), ('GB', 'United Kingdom'), ('IE', 'Ireland'), ('CH', 'Switzerland')], default='US', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
