# Generated by Django 5.0.1 on 2026-04-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_listing_currency_alter_listing_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_shadow_banned',
            field=models.BooleanField(default=False, help_text='ADMIN ONLY. Hides listing from public — seller still sees it as active.', verbose_name='Shadow banned'),
        ),
    ]
