# Generated by Django 5.0.1 on 2026-04-20 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_listing_is_shadow_banned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='impressions_count',
            field=models.IntegerField(default=0, verbose_name='Impressions count'),
        ),
        migrations.CreateModel(
            name='ListingImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('shown_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_records', to='listings.listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing Impression',
                'verbose_name_plural': 'Listing Impressions',
                'ordering': ['-shown_at'],
                'indexes': [models.Index(fields=['listing', 'shown_at'], name='listings_li_listing_9b95ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='listings.listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing View',
                'verbose_name_plural': 'Listing Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['listing', 'viewed_at'], name='listings_li_listing_df08d5_idx')],
            },
        ),
    ]
