# Generated by Django 5.0.1 on 2026-04-20 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_listing_impressions_count_listingimpression_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sold_at',
            field=models.DateTimeField(blank=True, help_text='When marked as sold. Auto-deleted after SOLD_DISPLAY_DAYS.', null=True, verbose_name='Sold at'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Activated At'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='star_level',
            field=models.IntegerField(choices=[(0, 'No Stars'), (1, '⭐ One Star (7 days)'), (2, '⭐⭐ Two Stars (30 days)')], default=0, verbose_name='Star Level'),
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_email', models.EmailField(blank=True, max_length=254, verbose_name='Seller email (snapshot)')),
                ('listing_id', models.IntegerField(blank=True, null=True, verbose_name='Listing ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('listing_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Listing created')),
                ('sold_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Sold at')),
                ('days_active', models.IntegerField(default=0, verbose_name='Days active until sold')),
                ('views_count', models.IntegerField(default=0)),
                ('impressions_count', models.IntegerField(default=0)),
                ('saves_count', models.IntegerField(default=0)),
                ('marked_sold', models.BooleanField(default=False, verbose_name='Was marked SOLD before delete')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.brand')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.model')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.vehicletype')),
            ],
            options={
                'verbose_name': 'Sales Record',
                'verbose_name_plural': 'Sales Records',
                'ordering': ['-sold_at'],
                'indexes': [models.Index(fields=['-sold_at'], name='listings_sa_sold_at_501163_idx'), models.Index(fields=['seller', '-sold_at'], name='listings_sa_seller__22419d_idx')],
            },
        ),
    ]
