# Generated by Django 5.0.1 on 2026-04-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_listing_sold_at_alter_listing_activated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Matching key in EMAIL_SCENARIOS dict (e.g. 'listing_published')", max_length=100, unique=True, verbose_name='Scenario code')),
                ('name', models.CharField(max_length=200, verbose_name='Display name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('Seller', 'Seller notifications'), ('Buyer (Saved)', 'Buyer - saved listings'), ('Saved Search', 'Saved search alerts'), ('Account', 'Account / auth'), ('Communication', 'Messaging'), ('Payments', 'Payments / Stripe'), ('Marketing', 'Marketing / newsletter'), ('Admin', 'Admin notifications'), ('Extra', 'Extra / experimental')], default='Seller', max_length=50)),
                ('trigger', models.CharField(blank=True, help_text='When this is sent (e.g. "Daily cron 9:00" or "Immediate")', max_length=200)),
                ('is_enabled', models.BooleanField(default=True, help_text='Uncheck to disable this email globally (without restart)', verbose_name='Enabled')),
                ('send_count', models.IntegerField(default=0, verbose_name='Total sent')),
                ('fail_count', models.IntegerField(default=0, verbose_name='Total failed')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Last sent at')),
                ('last_failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last failed at')),
                ('last_error', models.TextField(blank=True, verbose_name='Last error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Scenario',
                'verbose_name_plural': 'Email Scenarios',
                'ordering': ['category', 'name'],
            },
        ),
    ]
