# Generated by Django 5.0.1 on 2026-04-21 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_emailscenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='co2_emission',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='CO₂ Emission (g/km)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='curb_weight',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='Curb Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='mileage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)], verbose_name='Mileage (km)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='power',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Power (kW)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Year'),
        ),
    ]
