# Generated by Django 5.0.1 on 2026-04-22 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_alter_listing_co2_emission_alter_listing_curb_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedListingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_notifications', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Save Notification Log',
                'verbose_name_plural': 'Save Notification Logs',
                'ordering': ['-notified_at'],
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
