# Generated by Django 5.0.1 on 2026-04-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_savedlistingnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='first_views_notified_at',
            field=models.DateTimeField(blank=True, help_text="When 'listing_first_views' email was sent (10 views reached).", null=True, verbose_name='First Views Milestone Notified'),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_no_sale_reminder_at',
            field=models.DateTimeField(blank=True, help_text="When 'listing_no_sale_reminder' email was sent. Reset on listing.activate().", null=True, verbose_name='Last No-Sale Reminder Sent'),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_views_milestone',
            field=models.IntegerField(default=0, help_text="Last milestone reached: 0, 100, 500, or 1000. Used by 'listing_views_milestone'.", verbose_name='Last Views Milestone Notified'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_tips_sent_at',
            field=models.DateTimeField(blank=True, help_text="When 'listing_photo_quality_tips' email was sent.", null=True, verbose_name='Photo Quality Tips Sent'),
        ),
    ]
