# Generated by Django 5.0.1 on 2026-04-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_listing_first_views_notified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='last_expired_reminder_at',
            field=models.DateTimeField(blank=True, help_text="When 'listing_expired_reminder' email was sent. Resends every 4 days while expired.", null=True, verbose_name='Last Expired Reminder Sent'),
        ),
    ]
