# Generated by Django 5.0.1 on 2026-04-24 12:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_listing_last_expired_reminder_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Motorcycle Brand',
                'verbose_name_plural': 'Motorcycle Brands',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, help_text='Leave empty if equipment is shared across vehicle types.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='listings.vehicletype'),
        ),
        migrations.AddField(
            model_name='listing',
            name='cooling_type',
            field=models.CharField(blank=True, choices=[('air', 'Air-cooled'), ('water', 'Water-cooled'), ('oil', 'Oil-cooled')], max_length=10, verbose_name='Cooling Type'),
        ),
        migrations.AddField(
            model_name='listing',
            name='engine_capacity_cc',
            field=models.IntegerField(blank=True, help_text='Motorcycle engine displacement in cm³ (e.g. 600, 1000)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Engine Capacity (cm³)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='moto_engine_type',
            field=models.CharField(blank=True, choices=[('single', 'Single-cylinder'), ('twin', 'Twin-cylinder'), ('parallel_twin', 'Parallel-twin'), ('v_twin', 'V-twin'), ('triple', 'Triple (3-cylinder)'), ('inline_4', 'Inline-4'), ('v4', 'V4'), ('boxer', 'Boxer'), ('other', 'Other')], max_length=20, verbose_name='Engine Configuration'),
        ),
        migrations.AddField(
            model_name='listing',
            name='motorcycle_type',
            field=models.CharField(blank=True, choices=[('sport', 'Sport'), ('cruiser', 'Cruiser'), ('touring', 'Touring'), ('enduro', 'Enduro'), ('motocross', 'Motocross'), ('chopper', 'Chopper'), ('naked', 'Naked'), ('scooter', 'Scooter'), ('moped', 'Moped'), ('atv', 'ATV / Quad'), ('trike', 'Trike'), ('other', 'Other')], max_length=20, verbose_name='Motorcycle Type'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('interior', 'Interior'), ('electronics', 'Electronics'), ('safety', 'Safety'), ('audio_video', 'Audio/Video'), ('exterior', 'Exterior'), ('other', 'Other Features'), ('motorcycle', 'Motorcycle Features')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.model', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='listing',
            name='motorcycle_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.motorcyclebrand', verbose_name='Motorcycle Brand'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='motorcycle_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.motorcyclebrand'),
        ),
        migrations.CreateModel(
            name='MotorcycleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='listings.motorcyclebrand')),
            ],
            options={
                'verbose_name': 'Motorcycle Model',
                'verbose_name_plural': 'Motorcycle Models',
                'ordering': ['name'],
                'unique_together': {('brand', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='motorcycle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.motorcyclemodel', verbose_name='Motorcycle Model'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='motorcycle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.motorcyclemodel'),
        ),
    ]
