# Generated by Django 5.0.1 on 2026-04-24 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_motorcyclebrand_equipment_vehicle_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.PositiveIntegerField(help_text='Plan duration in days (e.g. 30, 60, 90)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Actual price shown to customer (e.g. 19.99)', max_digits=8)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Crossed-out "value" price. Leave empty to hide.', max_digits=8, null=True)),
                ('discount_percent', models.PositiveIntegerField(blank=True, help_text='Discount % badge like -60%. Leave empty for no badge.', null=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Show "MOST POPULAR" ribbon on this plan')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the grid (lower = left)')),
                ('custom_label', models.CharField(blank=True, help_text='Optional label (e.g. "Best value", "Recommended")', max_length=50)),
                ('boost_days', models.PositiveIntegerField(default=0, help_text='Days of boost in listing (highlighted). 0 = no boost.')),
                ('vip_days', models.PositiveIntegerField(default=0, help_text='Days of VIP listing (star badge). 0 = no VIP.')),
                ('homepage_ad_days', models.PositiveIntegerField(default=0, help_text='Days shown on homepage. 0 = not shown.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this plan from customers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.ForeignKey(help_text='Which vehicle category this plan applies to', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='listings.vehicletype')),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['vehicle_type', 'order', 'duration_days'],
                'unique_together': {('vehicle_type', 'duration_days')},
            },
        ),
    ]
