# Generated by Django 5.0.1 on 2026-04-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_pricingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='draft_reminder_count',
            field=models.IntegerField(default=0, help_text='How many draft reminder emails sent. 0=none, 1=first (1h), 2=24h, 3+=daily.', verbose_name='Draft Reminder Count'),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_draft_reminder_at',
            field=models.DateTimeField(blank=True, help_text="When last 'draft_reminder' email was sent. Used to throttle daily reminders.", null=True, verbose_name='Last Draft Reminder Sent'),
        ),
    ]
