# Generated by Django 5.0.1 on 2026-04-29 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_listing_draft_reminder_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_brand_text',
            field=models.CharField(blank=True, help_text='Free text: e.g. Shoei, Alpinestars, AGV', max_length=100, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex'), ('kids', 'Kids')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_material',
            field=models.CharField(blank=True, choices=[('leather', 'Leather'), ('textile', 'Textile'), ('mixed', 'Leather + Textile'), ('synthetic', 'Synthetic'), ('mesh', 'Mesh'), ('other', 'Other')], max_length=20, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_size',
            field=models.CharField(blank=True, choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('one_size', 'One size / Universal'), ('numeric', 'Numeric (specify in description)')], max_length=20, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_type',
            field=models.CharField(blank=True, choices=[('helmet', 'Helmet'), ('protective', 'Protective gear'), ('boots', 'Boots'), ('pants', 'Pants'), ('suit', 'Suit / Combination'), ('bag', 'Bag / Backpack'), ('gloves', 'Gloves'), ('jacket', 'Jacket'), ('other', 'Other')], max_length=20, verbose_name='Gear Type'),
        ),
        migrations.AddField(
            model_name='listing',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='For moto gear items: helmet, gloves, jacket, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.subcategory', verbose_name='Sub-category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="For 3-level hierarchy: e.g. 'Helmets' parent is 'Moto Gear'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='listings.subcategory', verbose_name='Parent subcategory'),
        ),
    ]
