# Generated by Django 5.0.1 on 2026-04-29 10:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_add_moto_gear_and_subcat_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='gear_types',
            field=models.CharField(blank=True, help_text='Comma-separated gear_type codes this applies to (helmet,jacket,...). Empty = all.', max_length=200, verbose_name='Gear types'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_model_text',
            field=models.CharField(blank=True, help_text='Free text: e.g. GT-Air II, RT-1200, Tech 10', max_length=100, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_safety_cert',
            field=models.CharField(blank=True, choices=[('ece_22_06', 'ECE 22.06'), ('ece_22_05', 'ECE 22.05'), ('dot', 'DOT (FMVSS 218)'), ('snell_m2020', 'Snell M2020'), ('snell_m2015', 'Snell M2015'), ('sharp_5', 'SHARP 5 stars'), ('sharp_4', 'SHARP 4 stars'), ('ce_aaa', 'CE AAA (highest)'), ('ce_aa', 'CE AA'), ('ce_a', 'CE A'), ('ce_b', 'CE B'), ('ce_level_1', 'CE Level 1 (impact protector)'), ('ce_level_2', 'CE Level 2 (impact protector)'), ('en_certified', 'EN certified'), ('none', 'No certification'), ('other', 'Other')], max_length=20, verbose_name='Safety certification'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_subtype',
            field=models.CharField(blank=True, choices=[('helmet:full_face', 'Full face'), ('helmet:integral', 'Integral'), ('helmet:modular', 'Modular / Flip-up'), ('helmet:open_face', 'Open face / Jet'), ('helmet:off_road', 'Off-road / Motocross'), ('helmet:dual_sport', 'Dual sport / Adventure'), ('helmet:half', 'Half helmet'), ('jacket:sport', 'Sport'), ('jacket:touring', 'Touring'), ('jacket:city', 'City / Urban'), ('jacket:adventure', 'Adventure'), ('jacket:off_road', 'Off-road'), ('jacket:cruiser', 'Cruiser'), ('pants:sport', 'Sport'), ('pants:touring', 'Touring'), ('pants:jeans', 'Riding jeans'), ('pants:off_road', 'Off-road'), ('pants:rain', 'Rain pants'), ('suit:one_piece', 'One-piece'), ('suit:two_piece', 'Two-piece'), ('suit:rain', 'Rain suit'), ('boots:sport', 'Sport'), ('boots:touring', 'Touring'), ('boots:off_road', 'Off-road / Motocross'), ('boots:adventure', 'Adventure'), ('boots:urban', 'Urban / Casual'), ('gloves:sport', 'Sport'), ('gloves:touring', 'Touring'), ('gloves:off_road', 'Off-road'), ('gloves:summer', 'Summer / Mesh'), ('gloves:winter', 'Winter / Heated'), ('gloves:rain', 'Rain'), ('bag:tank', 'Tank bag'), ('bag:tail', 'Tail bag'), ('bag:saddle', 'Saddle bag'), ('bag:backpack', 'Backpack'), ('bag:top_case', 'Top case'), ('bag:roll', 'Roll bag'), ('protective:back', 'Back protector'), ('protective:chest', 'Chest protector'), ('protective:knee', 'Knee guards'), ('protective:elbow', 'Elbow guards'), ('protective:neck', 'Neck brace'), ('protective:airbag', 'Airbag vest')], help_text='E.g. helmet:full_face, jacket:sport — UI filters by gear_type.', max_length=50, verbose_name='Gear Subtype'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_ventilation_count',
            field=models.IntegerField(blank=True, help_text='Helmet ventilation port count (0-50)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Number of vents'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_business_seller',
            field=models.BooleanField(default=False, help_text='Seller is a registered business / dealer', verbose_name='Business seller'),
        ),
        migrations.AddField(
            model_name='listing',
            name='open_to_trade',
            field=models.BooleanField(default=False, help_text='Seller is willing to consider trades / part-exchange', verbose_name='Open to trade'),
        ),
        migrations.AlterField(
            model_name='emailscenario',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Scenario code'),
        ),
        migrations.AlterField(
            model_name='emailscenario',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='emailscenario',
            name='trigger',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('interior', 'Interior'), ('electronics', 'Electronics'), ('safety', 'Safety'), ('audio_video', 'Audio/Video'), ('exterior', 'Exterior'), ('other', 'Other Features'), ('motorcycle', 'Motorcycle Features'), ('gear', 'Gear Features')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='draft_reminder_count',
            field=models.IntegerField(default=0, verbose_name='Draft Reminder Count'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='engine_capacity_cc',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Engine Capacity (cm³)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='first_views_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Views Milestone Notified'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='gear_brand_text',
            field=models.CharField(blank=True, help_text='Free text: e.g. Shoei, Alpinestars, AGV', max_length=100, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_draft_reminder_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Draft Reminder Sent'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_expired_reminder_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Expired Reminder Sent'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_no_sale_reminder_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last No-Sale Reminder Sent'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_views_milestone',
            field=models.IntegerField(default=0, verbose_name='Last Views Milestone Notified'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_tips_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Photo Quality Tips Sent'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sold at'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='boost_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='custom_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='duration_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='homepage_ad_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='listings.vehicletype'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='vip_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
