# Generated by Django 5.0.1 on 2026-04-29 11:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_add_gear_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0, verbose_name='Display order')),
            ],
            options={
                'verbose_name': 'Gear Brand',
                'verbose_name_plural': 'Gear Brands',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='emailscenario',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['category', 'order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='listingequipment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['order', '-is_main']},
        ),
        migrations.AlterModelOptions(
            name='listingimpression',
            options={'ordering': ['-shown_at']},
        ),
        migrations.AlterModelOptions(
            name='listingview',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['vehicle_type', 'order', 'duration_days']},
        ),
        migrations.AlterModelOptions(
            name='salesrecord',
            options={'ordering': ['-sold_at']},
        ),
        migrations.AlterModelOptions(
            name='savedlisting',
            options={'ordering': ['-saved_at']},
        ),
        migrations.AlterModelOptions(
            name='savedlistingnotification',
            options={'ordering': ['-notified_at']},
        ),
        migrations.AlterModelOptions(
            name='savedsearch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='listing',
            name='color_other_text',
            field=models.CharField(blank=True, help_text="Used when color='other' — free text fallback", max_length=50, verbose_name='Color (custom)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_brand_other_text',
            field=models.CharField(blank=True, help_text='Used when gear_brand=Other', max_length=100, verbose_name='Manufacturer (custom)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_gender_other_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Gender (custom)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_material_other_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Material (custom)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_safety_cert_other_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Safety certification (custom)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_size_other_text',
            field=models.CharField(blank=True, help_text="Used when size='other' or 'numeric'", max_length=50, verbose_name='Size (custom)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_subtype_other_text',
            field=models.CharField(blank=True, help_text="Used when subtype ends with ':other'", max_length=100, verbose_name='Subtype (custom)'),
        ),
        migrations.AlterField(
            model_name='emailscenario',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emailscenario',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailscenario',
            name='fail_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailscenario',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailscenario',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailscenario',
            name='last_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailscenario',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailscenario',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emailscenario',
            name='send_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('interior', 'Interior'), ('electronics', 'Electronics'), ('safety', 'Safety'), ('audio_video', 'Audio/Video'), ('exterior', 'Exterior'), ('other', 'Other Features'), ('motorcycle', 'Motorcycle Features'), ('gear', 'Gear Features')], max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='gear_types',
            field=models.CharField(blank=True, help_text='CSV gear_types (helmet,jacket,...). Empty=all.', max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='listings.vehicletype'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('estate', 'Estate/Wagon'), ('minivan', 'Minivan'), ('suv', 'SUV/Crossover'), ('coupe', 'Coupe'), ('commercial', 'Commercial'), ('convertible', 'Convertible'), ('limousine', 'Limousine'), ('pickup', 'Pickup'), ('minibus', 'Minibus'), ('truck', 'Truck/Van'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='climate',
            field=models.CharField(blank=True, choices=[('none', 'No climate control'), ('ac', 'Air conditioning'), ('climate', 'Climate control'), ('dual_climate', 'Dual-zone climate control'), ('triple_climate', 'Triple-zone climate control')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='co2_emission',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(blank=True, choices=[('other', 'Other'), ('white', 'White'), ('black', 'Black'), ('red', 'Red / Burgundy'), ('blue', 'Blue'), ('green_khaki', 'Green / Khaki'), ('yellow_gold', 'Yellow / Gold'), ('orange', 'Orange'), ('purple', 'Purple'), ('brown_beige', 'Brown / Beige'), ('multicolor', 'Multicolor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged')], default='used', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cooling_type',
            field=models.CharField(blank=True, choices=[('air', 'Air-cooled'), ('water', 'Water-cooled'), ('oil', 'Oil-cooled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('LT', 'Lithuania'), ('LV', 'Latvia'), ('EE', 'Estonia'), ('PL', 'Poland'), ('DE', 'Germany'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('AT', 'Austria'), ('CZ', 'Czech Republic'), ('SK', 'Slovakia'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('SE', 'Sweden'), ('DK', 'Denmark'), ('FI', 'Finland'), ('NO', 'Norway'), ('GB', 'United Kingdom'), ('IE', 'Ireland'), ('CH', 'Switzerland')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='curb_weight',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='defects',
            field=models.CharField(choices=[('none', 'No defects'), ('dented', 'Dented'), ('burned', 'Burned'), ('gearbox_defect', 'Gearbox defect'), ('hail_damage', 'Hail damage'), ('sunken', 'Sunken'), ('engine_defect', 'Engine defect'), ('major_defects', 'Major defects')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='doors',
            field=models.CharField(blank=True, choices=[('2/3', '2/3 doors'), ('4/5', '4/5 doors')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='draft_reminder_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('fwd', 'Front-wheel drive (FWD)'), ('rwd', 'Rear-wheel drive (RWD)'), ('awd', 'All-wheel drive (AWD/4WD)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='engine_capacity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='engine_capacity_cc',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='euro_standard',
            field=models.CharField(blank=True, choices=[('euro1', 'Euro 1'), ('euro2', 'Euro 2'), ('euro3', 'Euro 3'), ('euro4', 'Euro 4'), ('euro5', 'Euro 5'), ('euro6', 'Euro 6'), ('euro6d', 'Euro 6d')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='first_views_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='fuel_consumption_city',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='fuel_consumption_combined',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='fuel_consumption_highway',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.fueltype'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='gear_brand_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Brand (legacy)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='gear_gender',
            field=models.CharField(blank=True, choices=[('other', 'Other'), ('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex'), ('kids', 'Kids')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='gear_material',
            field=models.CharField(blank=True, choices=[('other', 'Other'), ('leather', 'Leather'), ('textile', 'Textile'), ('mixed', 'Leather + Textile'), ('synthetic', 'Synthetic'), ('mesh', 'Mesh')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='gear_model_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Model name'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='gear_safety_cert',
            field=models.CharField(blank=True, choices=[('other', 'Other'), ('none', 'No certification'), ('ece_22_06', 'ECE 22.06'), ('ece_22_05', 'ECE 22.05'), ('dot', 'DOT (FMVSS 218)'), ('snell_m2020', 'Snell M2020'), ('snell_m2015', 'Snell M2015'), ('sharp_5', 'SHARP 5 stars'), ('sharp_4', 'SHARP 4 stars'), ('ce_aaa', 'CE AAA (highest)'), ('ce_aa', 'CE AA'), ('ce_a', 'CE A'), ('ce_b', 'CE B'), ('ce_level_1', 'CE Level 1 (impact)'), ('ce_level_2', 'CE Level 2 (impact)'), ('en_certified', 'EN certified')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='gear_size',
            field=models.CharField(blank=True, choices=[('other', 'Other'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('one_size', 'One size / Universal'), ('numeric', 'Numeric')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='gear_subtype',
            field=models.CharField(blank=True, choices=[('helmet:other', 'Other'), ('helmet:full_face', 'Full face'), ('helmet:integral', 'Integral'), ('helmet:modular', 'Modular / Flip-up'), ('helmet:open_face', 'Open face / Jet'), ('helmet:off_road', 'Off-road / Motocross'), ('helmet:dual_sport', 'Dual sport / Adventure'), ('helmet:half', 'Half helmet'), ('jacket:other', 'Other'), ('jacket:sport', 'Sport'), ('jacket:touring', 'Touring'), ('jacket:city', 'City / Urban'), ('jacket:adventure', 'Adventure'), ('jacket:off_road', 'Off-road'), ('jacket:cruiser', 'Cruiser'), ('pants:other', 'Other'), ('pants:sport', 'Sport'), ('pants:touring', 'Touring'), ('pants:jeans', 'Riding jeans'), ('pants:off_road', 'Off-road'), ('pants:rain', 'Rain pants'), ('suit:other', 'Other'), ('suit:one_piece', 'One-piece'), ('suit:two_piece', 'Two-piece'), ('suit:rain', 'Rain suit'), ('boots:other', 'Other'), ('boots:sport', 'Sport'), ('boots:touring', 'Touring'), ('boots:off_road', 'Off-road / Motocross'), ('boots:adventure', 'Adventure'), ('boots:urban', 'Urban / Casual'), ('gloves:other', 'Other'), ('gloves:sport', 'Sport'), ('gloves:touring', 'Touring'), ('gloves:off_road', 'Off-road'), ('gloves:summer', 'Summer / Mesh'), ('gloves:winter', 'Winter / Heated'), ('gloves:rain', 'Rain'), ('bag:other', 'Other'), ('bag:tank', 'Tank bag'), ('bag:tail', 'Tail bag'), ('bag:saddle', 'Saddle bag'), ('bag:backpack', 'Backpack'), ('bag:top_case', 'Top case'), ('bag:roll', 'Roll bag'), ('protective:other', 'Other'), ('protective:back', 'Back protector'), ('protective:chest', 'Chest protector'), ('protective:knee', 'Knee guards'), ('protective:elbow', 'Elbow guards'), ('protective:neck', 'Neck brace'), ('protective:airbag', 'Airbag vest')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='gear_type',
            field=models.CharField(blank=True, choices=[('helmet', 'Helmet'), ('protective', 'Protective gear'), ('boots', 'Boots'), ('pants', 'Pants'), ('suit', 'Suit / Combination'), ('bag', 'Bag / Backpack'), ('gloves', 'Gloves'), ('jacket', 'Jacket'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='gear_ventilation_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Number of vents'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='hide_exact_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='impressions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_business_seller',
            field=models.BooleanField(default=False, verbose_name='Business seller'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_shadow_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_boosted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_draft_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_expired_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_no_sale_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='last_views_milestone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='moto_engine_type',
            field=models.CharField(blank=True, choices=[('single', 'Single-cylinder'), ('twin', 'Twin-cylinder'), ('parallel_twin', 'Parallel-twin'), ('v_twin', 'V-twin'), ('triple', 'Triple (3-cylinder)'), ('inline_4', 'Inline-4'), ('v4', 'V4'), ('boxer', 'Boxer'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='motorcycle_type',
            field=models.CharField(blank=True, choices=[('sport', 'Sport'), ('cruiser', 'Cruiser'), ('touring', 'Touring'), ('enduro', 'Enduro'), ('motocross', 'Motocross'), ('chopper', 'Chopper'), ('naked', 'Naked'), ('scooter', 'Scooter'), ('moped', 'Moped'), ('atv', 'ATV / Quad'), ('trike', 'Trike'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='open_to_trade',
            field=models.BooleanField(default=False, verbose_name='Open to trade'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='origin_country',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('LT', 'Lithuania'), ('LV', 'Latvia'), ('EE', 'Estonia'), ('PL', 'Poland'), ('DE', 'Germany'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('AT', 'Austria'), ('CZ', 'Czech Republic'), ('SK', 'Slovakia'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('SE', 'Sweden'), ('DK', 'Denmark'), ('FI', 'Finland'), ('NO', 'Norway'), ('GB', 'United Kingdom'), ('IE', 'Ireland'), ('CH', 'Switzerland')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_tips_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='power',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='reservation_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rim_size',
            field=models.CharField(blank=True, choices=[('13', '13"'), ('14', '14"'), ('15', '15"'), ('16', '16"'), ('17', '17"'), ('18', '18"'), ('19', '19"'), ('20', '20"'), ('21', '21"'), ('22', '22"'), ('23', '23"'), ('24', '24"')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seats',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('9+', '9+')], max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='star_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='star_level',
            field=models.IntegerField(choices=[(0, 'No Stars'), (1, '⭐ One Star (7 days)'), (2, '⭐⭐ Two Stars (30 days)')], default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='steering',
            field=models.CharField(blank=True, choices=[('left', 'Left-hand drive'), ('right', 'Right-hand drive (UK)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.subcategory', verbose_name='Sub-category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='technical_inspection_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='technical_inspection_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='transmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.transmission'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='vin',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listings/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listingimpression',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='days_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='listing_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='listing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='marked_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='seller_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sold_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='notify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='query_params',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='track_price_drop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='listings.subcategory', verbose_name='Parent subcategory'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.gearbrand', verbose_name='Manufacturer'),
        ),
    ]
