# Generated by Django 5.0.1 on 2026-04-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0032_gearbrand_alter_emailscenario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='truck_type',
            field=models.CharField(blank=True, choices=[('', 'Any'), ('general', 'General Truck'), ('tipper', 'Tipper'), ('refrigerator', 'Refrigerator'), ('tanker', 'Tanker'), ('crane', 'Crane'), ('flatbed', 'Flatbed'), ('box', 'Box'), ('curtain_side', 'Curtain Side'), ('car_carrier', 'Car Carrier'), ('logging', 'Logging'), ('garbage', 'Garbage'), ('concrete_mixer', 'Concrete Mixer'), ('other', 'Other')], help_text="Used when subcategory is 'Trucks' (Sunkvežimiai)", max_length=30, verbose_name='Truck type'),
        ),
    ]
