# Generated by Django 5.0.1 on 2026-05-01 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_truckbrand_alter_emailscenario_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='truck_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.truckbrand', verbose_name='Truck Brand'),
        ),
        migrations.AddField(
            model_name='listing',
            name='truck_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.truckmodel', verbose_name='Truck Model'),
        ),
    ]
