# Generated by Django 5.0.1 on 2026-05-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_listing_truck_brand_listing_truck_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='truck_model_text',
            field=models.CharField(blank=True, help_text="User-typed model name (e.g. 'FH16', 'Actros 1845')", max_length=100, verbose_name='Truck Model (free text)'),
        ),
    ]
