# Generated by Django 5.0.1 on 2026-05-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_listing_truck_model_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='truck_type',
            field=models.CharField(blank=True, choices=[('', '— Select —'), ('tankers', 'Tankers'), ('car_carriers', 'Car Carriers'), ('concrete_mixers', 'Concrete Mixers'), ('flatbed', 'Flatbed'), ('flatbed_tarpaulin', 'Flatbed with Tarpaulin'), ('curtain_side', 'Curtain-Side'), ('double_cab', 'Double Cab'), ('livestock_carriers', 'Livestock Carriers'), ('insulated_box', 'Insulated Box'), ('hard_side_box', 'Hard-Side Box'), ('container_carriers', 'Container Carriers'), ('logging_trucks', 'Logging Trucks'), ('milk_tankers', 'Milk Tankers'), ('platforms', 'Platforms'), ('mobile_shop', 'Mobile Shop'), ('tippers', 'Tippers'), ('hook_lift_tippers', 'Hook-Lift Tippers'), ('crane_tippers', 'Crane Tippers'), ('with_crane', 'With Crane'), ('refrigerators', 'Refrigerators'), ('curtain_tarpaulin', 'Curtain / Tarpaulin'), ('chassis', 'Chassis'), ('other', 'Other')], max_length=30, verbose_name='Truck type'),
        ),
    ]
