# Generated by Django 5.0.1 on 2026-05-01 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0037_alter_truck_truck_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='front_suspension',
            field=models.CharField(blank=True, choices=[('', '— Select —'), ('air', 'Air'), ('spring', 'Spring'), ('parabolic', 'Parabolic'), ('hydraulic', 'Hydraulic'), ('rubber', 'Rubber')], max_length=20, verbose_name='Front suspension'),
        ),
        migrations.AddField(
            model_name='listing',
            name='fuel_tank_capacity_l',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Fuel tank capacity (L)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gross_weight_kg',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Gross weight (kg)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='mass_interval',
            field=models.CharField(blank=True, choices=[('', '— Select —'), ('up_to_3.5t', 'Up to 3.5 t'), ('3.5_to_7.5t', '3.5 - 7.5 t'), ('over_7.5t', 'Over 7.5 t')], max_length=20, verbose_name='Mass interval'),
        ),
        migrations.AddField(
            model_name='listing',
            name='payload_kg',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Payload capacity (kg)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='rear_suspension',
            field=models.CharField(blank=True, choices=[('', '— Select —'), ('air', 'Air'), ('spring', 'Spring'), ('parabolic', 'Parabolic'), ('hydraulic', 'Hydraulic'), ('rubber', 'Rubber')], max_length=20, verbose_name='Rear suspension'),
        ),
        migrations.AddField(
            model_name='listing',
            name='sdk_number',
            field=models.CharField(blank=True, help_text='Self-Declared Conformity number (Regitra)', max_length=50, verbose_name='SDK number'),
        ),
        migrations.AddField(
            model_name='listing',
            name='sleeping_seats',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Sleeping seats'),
        ),
        migrations.AddField(
            model_name='listing',
            name='truck_height_mm',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='Height (mm)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='truck_length_mm',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='Length (mm)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='truck_volume_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Volume (m³)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='truck_width_mm',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='Width (mm)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='wheel_formula',
            field=models.CharField(blank=True, choices=[('', '— Select —'), ('4x2', '4x2'), ('4x4', '4x4'), ('6x2', '6x2'), ('6x2/4', '6x2/4'), ('6x4', '6x4'), ('6x4/2', '6x4/2'), ('6x6', '6x6'), ('8x2', '8x2'), ('8x2/4', '8x2/4'), ('8x4', '8x4'), ('8x6', '8x6'), ('8x8', '8x8'), ('10x4', '10x4'), ('10x6', '10x6'), ('10x8', '10x8')], max_length=10, verbose_name='Wheel formula'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='truck_type',
            field=models.CharField(blank=True, choices=[('', '— Select —'), ('tankers', 'Tankers'), ('car_carriers', 'Car Carriers'), ('concrete_mixers', 'Concrete Mixers'), ('flatbed', 'Flatbed'), ('flatbed_tarpaulin', 'Flatbed with Tarpaulin'), ('curtain_side', 'Curtain-Side'), ('double_cab', 'Double Cab'), ('livestock_carriers', 'Livestock Carriers'), ('insulated_box', 'Insulated Box'), ('hard_side_box', 'Hard-Side Box'), ('container_carriers', 'Container Carriers'), ('logging_trucks', 'Logging Trucks'), ('milk_tankers', 'Milk Tankers'), ('platforms', 'Platforms'), ('mobile_shop', 'Mobile Shop'), ('tippers', 'Tippers'), ('hook_lift_tippers', 'Hook-Lift Tippers'), ('crane_tippers', 'Crane Tippers'), ('with_crane', 'With Crane'), ('refrigerators', 'Refrigerators'), ('curtain_tarpaulin', 'Curtain / Tarpaulin'), ('chassis', 'Chassis'), ('other', 'Other')], help_text="Used when subcategory is 'Trucks' (Sunkvežimiai)", max_length=30, verbose_name='Truck type'),
        ),
    ]
