# Generated by Django 5.0.1 on 2026-05-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_listing_front_suspension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='color_code',
            field=models.CharField(blank=True, help_text='Manufacturer color code, e.g. "LY7G"', max_length=30, verbose_name='Color code'),
        ),
        migrations.AddField(
            model_name='listing',
            name='engine_code',
            field=models.CharField(blank=True, help_text='e.g. "BKD"', max_length=30, verbose_name='Engine code'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gearbox_code',
            field=models.CharField(blank=True, help_text='e.g. "DSG7"', max_length=30, verbose_name='Gearbox code'),
        ),
        migrations.AddField(
            model_name='listing',
            name='modification',
            field=models.CharField(blank=True, help_text='e.g. "2.0 TDI 140kW"', max_length=100, verbose_name='Modification'),
        ),
        migrations.AddField(
            model_name='listing',
            name='version',
            field=models.CharField(blank=True, help_text='e.g. "TDI Sportline" — used in car-for-parts category', max_length=100, verbose_name='Version'),
        ),
    ]
