# Generated by Django 5.0.1 on 2026-05-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_listing_color_code_listing_engine_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='export_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional separate price for export buyers', max_digits=10, null=True, verbose_name='Export price'),
        ),
        migrations.AddField(
            model_name='listing',
            name='taxes_extra',
            field=models.BooleanField(default=False, help_text='Price excludes taxes — buyer should ask seller', verbose_name='+ Taxes'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='used', max_length=20),
        ),
    ]
