# Generated by Django 5.0.1 on 2026-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_listing_export_price_listing_taxes_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_on_lease',
            field=models.BooleanField(default=False, verbose_name='Available on lease'),
        ),
        migrations.AddField(
            model_name='listing',
            name='disabled_friendly',
            field=models.BooleanField(default=False, verbose_name='Adapted for disabled'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_service_book',
            field=models.BooleanField(default=False, verbose_name='Service book'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_warranty',
            field=models.BooleanField(default=False, verbose_name='Warranty included'),
        ),
        migrations.AddField(
            model_name='listing',
            name='imported_from_us',
            field=models.BooleanField(default=False, verbose_name='Imported from US'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_auction',
            field=models.BooleanField(default=False, verbose_name='From auction'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_sport_ready',
            field=models.BooleanField(default=False, verbose_name='Sport-ready'),
        ),
        migrations.AddField(
            model_name='listing',
            name='multiple_keys',
            field=models.BooleanField(default=False, verbose_name='Multiple key sets'),
        ),
        migrations.AddField(
            model_name='listing',
            name='pneumatic_suspension',
            field=models.BooleanField(default=False, verbose_name='Pneumatic suspension'),
        ),
        migrations.AddField(
            model_name='listing',
            name='power_boosted',
            field=models.BooleanField(default=False, verbose_name='Increased engine power'),
        ),
        migrations.AddField(
            model_name='listing',
            name='remote_start',
            field=models.BooleanField(default=False, verbose_name='Remote start'),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller_type',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('dealer', 'Dealer')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='spare_wheel',
            field=models.BooleanField(default=False, verbose_name='Spare wheel'),
        ),
        migrations.AddField(
            model_name='listing',
            name='valid_inspection',
            field=models.BooleanField(default=False, verbose_name='Valid technical inspection'),
        ),
    ]
