# Generated by Django 5.0.1 on 2026-05-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_listing_available_on_lease_listing_disabled_friendly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='star_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truck',
            name='star_count',
            field=models.IntegerField(default=0),
        ),
    ]
