# Generated by Django 5.0.1 on 2026-05-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0042_listing_star_count_truck_star_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='highlight_until',
            field=models.DateTimeField(blank=True, help_text='Listing card has highlighted background until this date', null=True),
        ),
    ]
