# Generated by Django 5.0.1 on 2026-05-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0043_truck_highlight_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highlight_until',
            field=models.DateTimeField(blank=True, help_text='Listing card has highlighted background until this date', null=True),
        ),
    ]
