# Generated by Django 5.0.1 on 2026-05-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0044_listing_highlight_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featured_until',
            field=models.DateTimeField(blank=True, help_text="Featured on homepage (Day's deals tab) until this date", null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='featured_until',
            field=models.DateTimeField(blank=True, help_text="Featured on homepage (Day's deals tab) until this date", null=True),
        ),
    ]
