# Generated by Django 5.0.1 on 2026-05-08 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0045_listing_featured_until_truck_featured_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMultiplierTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, help_text='Listing.price minimum (inclusive)', max_digits=12)),
                ('max_price', models.DecimalField(decimal_places=2, help_text='Listing.price maximum (exclusive)', max_digits=12)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Plano kaina × multiplier (pvz. 1.5 = +50%)', max_digits=4)),
                ('label', models.CharField(blank=True, help_text="Optional label (pvz. 'Pigus', 'Brangus', 'Luxury')", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Price Multiplier Tier',
                'verbose_name_plural': 'Price Multiplier Tiers',
                'ordering': ['min_price'],
            },
        ),
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier_enabled', models.BooleanField(default=False, help_text="ĮJUNGTI dynamic pricing (kuo brangesnis listing → tuo brangesnis plan'as)")),
                ('addon_renew_price', models.DecimalField(decimal_places=2, default=1.0, help_text='Cena už 1 žvaigždutę per dieną ($)', max_digits=6)),
                ('addon_featured_price', models.DecimalField(decimal_places=2, default=0.3, help_text='Cena už Featured on homepage per dieną ($)', max_digits=6)),
                ('addon_renew_max_count', models.PositiveIntegerField(default=20)),
                ('addon_renew_max_days', models.PositiveIntegerField(default=42)),
                ('addon_featured_max_days', models.PositiveIntegerField(default=42)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Settings',
                'verbose_name_plural': 'Pricing Settings',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Pvz. 'SPRING25', 'WELCOME10' (ne case-sensitive)", max_length=30, unique=True)),
                ('description', models.CharField(blank=True, help_text='Vidinis aprašymas (admin tik mato)', max_length=200)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage (%)'), ('fixed', 'Fixed amount ($)')], default='percent', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='25 = -25% (jei percent), arba 10 = - (jei fixed)', max_digits=8)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maksimalus panaudojimų skaičius (null = unlimited)', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('once_per_user', models.BooleanField(default=True, help_text="Vienas user'is gali naudoti tik kartą")),
                ('applies_to_cars', models.BooleanField(default=True)),
                ('applies_to_trucks', models.BooleanField(default=True)),
                ('applies_to_motorcycles', models.BooleanField(default=True)),
                ('applies_to_basic', models.BooleanField(default=True)),
                ('applies_to_standard', models.BooleanField(default=True)),
                ('applies_to_premium', models.BooleanField(default=True)),
                ('min_listing_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum listing.price kad kodas veiktų (null = no limit)', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='boost_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of stars (1-3) shown on listing card'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='code',
            field=models.CharField(blank=True, help_text="Plan code: 'basic_30', 'standard_60', 'premium_90'", max_length=30),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='featured_days',
            field=models.PositiveIntegerField(default=0, help_text="Days listing appears on homepage Day's deals"),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='highlight_days',
            field=models.PositiveIntegerField(default=0, help_text='Days listing card has highlighted background'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text="Show 'RECOMMENDED' badge on this plan"),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='label',
            field=models.CharField(blank=True, help_text="Display name: 'Basic', 'Standard', 'Recommended'", max_length=50),
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_usages', to='listings.listing')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='listings.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Code Usage',
                'verbose_name_plural': 'Promo Code Usages',
                'ordering': ['-used_at'],
            },
        ),
    ]
