# Generated by Django 5.0.1 on 2026-05-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0046_pricemultipliertier_pricingsettings_promocode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=120)),
                ('name_lt', models.CharField(blank=True, max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Category'), (1, 'Group'), (2, 'Subcategory')], default=0)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='listings.partcategory')),
            ],
            options={
                'verbose_name': 'Part Category',
                'verbose_name_plural': 'Part Categories',
                'ordering': ['level', 'order', 'name_en'],
                'indexes': [models.Index(fields=['level', 'parent'], name='listings_pa_level_4b1911_idx'), models.Index(fields=['slug'], name='listings_pa_slug_718ab7_idx')],
            },
        ),
    ]
