# Generated by Django 5.0.1 on 2026-05-27 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0047_partcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='oem_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Manufacturer part number (e.g., 63217160797)', max_length=50, verbose_name='OEM Code'),
        ),
        migrations.AddField(
            model_name='listing',
            name='part_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.partcategory', verbose_name='Part Category'),
        ),
    ]
