# Generated by Django 5.0.1 on 2026-06-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0048_listing_oem_code_listing_part_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='boat_engine_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='boat_length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='boat_make_text',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='listing',
            name='boat_material',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='listing',
            name='boat_model_text',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='listing',
            name='boat_width_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='transmission_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='e.g., 6HP19, ZF8HP', max_length=30, verbose_name='Gearbox Code'),
        ),
    ]
