# Generated by Django 5.0.1 on 2026-06-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0049_listing_boat_engine_count_listing_boat_length_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='boat_type',
            field=models.CharField(blank=True, choices=[('jet_ski', 'Jet Ski / Personal watercraft'), ('kayak_canoe', 'Kayak / Canoe'), ('surfboard', 'Surfboard / Windsurf'), ('yacht', 'Yacht'), ('motorboat', 'Motorboat / Cabin cruiser'), ('boat', 'Boat / Ship'), ('dinghy_raft', 'Dinghy / Raft'), ('engine', 'Boat engine'), ('other', 'Other')], max_length=20, verbose_name='Boat type'),
        ),
    ]
