# Generated by Django 5.0.1 on 2026-06-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0050_listing_boat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='boat_engine_type',
            field=models.CharField(blank=True, choices=[('petrol_4stroke_outboard', 'Petrol 4-stroke outboard'), ('petrol_4stroke_inboard', 'Petrol 4-stroke inboard'), ('diesel_inboard', 'Diesel inboard'), ('electric', 'Electric'), ('none', 'No engine'), ('petrol_2stroke_outboard', 'Petrol 2-stroke outboard'), ('petrol_2stroke_inboard', 'Petrol 2-stroke inboard')], max_length=30, verbose_name='Boat engine type'),
        ),
        migrations.AddField(
            model_name='listing',
            name='boat_fuel_tank_l',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Fuel tank capacity (L)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='boat_liftable_engine',
            field=models.BooleanField(default=False, verbose_name='Liftable engine'),
        ),
        migrations.AddField(
            model_name='listing',
            name='boat_propeller',
            field=models.BooleanField(default=False, verbose_name='Propeller'),
        ),
        migrations.AddField(
            model_name='listing',
            name='boat_water_turbine',
            field=models.BooleanField(default=False, verbose_name='Water turbine'),
        ),
    ]
