# Generated by Django 5.0.1 on 2026-07-09 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0051_listing_boat_engine_type_listing_boat_fuel_tank_l_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('tyre', 'Tyres'), ('rim', 'Rims')], db_index=True, max_length=8)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('purpose', models.CharField(blank=True, choices=[('passenger', 'Passenger cars'), ('suv', 'SUV / Off-road'), ('commercial', 'Commercial / Van'), ('truck', 'Trucks'), ('moto', 'Motorcycles'), ('industrial', 'Industrial')], db_index=True, max_length=20)),
                ('diameter', models.CharField(blank=True, choices=[('10', 'R10'), ('11', 'R11'), ('12', 'R12'), ('13', 'R13'), ('14', 'R14'), ('15', 'R15'), ('16', 'R16'), ('17', 'R17'), ('18', 'R18'), ('19', 'R19'), ('20', 'R20'), ('21', 'R21'), ('22', 'R22'), ('23', 'R23'), ('24', 'R24')], db_index=True, max_length=4)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='used', max_length=8)),
                ('quantity', models.PositiveSmallIntegerField(default=4)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('negotiable', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('tyre_width', models.CharField(blank=True, choices=[('125', '125'), ('135', '135'), ('145', '145'), ('155', '155'), ('165', '165'), ('175', '175'), ('185', '185'), ('195', '195'), ('205', '205'), ('215', '215'), ('225', '225'), ('235', '235'), ('245', '245'), ('255', '255'), ('265', '265'), ('275', '275'), ('285', '285'), ('295', '295'), ('305', '305'), ('315', '315'), ('325', '325'), ('335', '335'), ('345', '345'), ('355', '355')], db_index=True, max_length=4)),
                ('tyre_profile', models.CharField(blank=True, choices=[('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55'), ('60', '60'), ('65', '65'), ('70', '70'), ('75', '75'), ('80', '80'), ('85', '85')], db_index=True, max_length=4)),
                ('tyre_season', models.CharField(blank=True, choices=[('summer', 'Summer'), ('winter', 'Winter'), ('all_season', 'All-season')], db_index=True, max_length=12)),
                ('tyre_speed_index', models.CharField(blank=True, choices=[('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('H', 'H'), ('V', 'V'), ('W', 'W'), ('Y', 'Y'), ('Z', 'Z')], max_length=2)),
                ('tyre_load_index', models.CharField(blank=True, max_length=6)),
                ('tyre_tread_mm', models.CharField(blank=True, choices=[('1', '1 mm'), ('2', '2 mm'), ('3', '3 mm'), ('4', '4 mm'), ('5', '5 mm'), ('6', '6 mm'), ('7', '7 mm'), ('8', '8 mm'), ('9', '9 mm'), ('10', '10 mm')], max_length=4)),
                ('tyre_remaining_pct', models.CharField(blank=True, choices=[('10', '10%'), ('20', '20%'), ('30', '30%'), ('40', '40%'), ('50', '50%'), ('60', '60%'), ('70', '70%'), ('80', '80%'), ('90', '90%'), ('100', '100%')], max_length=4)),
                ('tyre_dot_year', models.CharField(blank=True, choices=[('2026', '2026'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006')], max_length=4)),
                ('feat_spare_thin', models.BooleanField(default=False)),
                ('feat_sold_single', models.BooleanField(default=False)),
                ('feat_sport', models.BooleanField(default=False)),
                ('feat_suv', models.BooleanField(default=False)),
                ('feat_rain', models.BooleanField(default=False)),
                ('feat_run_flat', models.BooleanField(default=False)),
                ('feat_reinforced', models.BooleanField(default=False)),
                ('feat_studded', models.BooleanField(default=False)),
                ('rim_width', models.CharField(blank=True, choices=[('4', '4J'), ('4.5', '4.5J'), ('5', '5J'), ('5.5', '5.5J'), ('6', '6J'), ('6.5', '6.5J'), ('7', '7J'), ('7.5', '7.5J'), ('8', '8J'), ('8.5', '8.5J'), ('9', '9J'), ('9.5', '9.5J'), ('10', '10J'), ('10.5', '10.5J'), ('11', '11J'), ('11.5', '11.5J'), ('12', '12J'), ('12.5', '12.5J'), ('13', '13J')], db_index=True, max_length=6)),
                ('rim_pcd', models.CharField(blank=True, choices=[('3x98', '3x98'), ('4x98', '4x98'), ('4x100', '4x100'), ('4x108', '4x108'), ('4x114.3', '4x114.3'), ('5x98', '5x98'), ('5x100', '5x100'), ('5x108', '5x108'), ('5x110', '5x110'), ('5x112', '5x112'), ('5x114.3', '5x114.3'), ('5x115', '5x115'), ('5x118', '5x118'), ('5x120', '5x120'), ('5x127', '5x127'), ('5x130', '5x130'), ('5x139.7', '5x139.7'), ('6x114.3', '6x114.3'), ('6x130', '6x130'), ('6x139.7', '6x139.7'), ('8x165.1', '8x165.1'), ('8x170', '8x170')], db_index=True, max_length=12)),
                ('rim_bolt_count', models.CharField(blank=True, choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('8', '8'), ('10', '10')], max_length=2)),
                ('rim_et', models.IntegerField(blank=True, null=True)),
                ('rim_dia', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('rim_material', models.CharField(blank=True, choices=[('alloy', 'Alloy'), ('steel', 'Steel'), ('forged', 'Forged'), ('carbon', 'Carbon fiber')], max_length=10)),
                ('country', models.CharField(choices=[('US', 'United States'), ('LT', 'Lithuania'), ('LV', 'Latvia'), ('EE', 'Estonia'), ('PL', 'Poland'), ('DE', 'Germany'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('AT', 'Austria'), ('CZ', 'Czech Republic'), ('SK', 'Slovakia'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('SE', 'Sweden'), ('DK', 'Denmark'), ('FI', 'Finland'), ('NO', 'Norway'), ('GB', 'United Kingdom'), ('IE', 'Ireland'), ('CH', 'Switzerland')], default='LT', max_length=2)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('expired', 'Expired'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('star_level', models.PositiveSmallIntegerField(default=0)),
                ('star_count', models.PositiveSmallIntegerField(default=0)),
                ('star_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_boosted_at', models.DateTimeField(blank=True, null=True)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('highlight_until', models.DateTimeField(blank=True, null=True)),
                ('is_shadow_banned', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('impressions_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wheel Listing',
                'verbose_name_plural': 'Wheel Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WheelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wheels/%Y/%m/')),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.wheellisting')),
            ],
            options={
                'verbose_name': 'Wheel Image',
                'verbose_name_plural': 'Wheel Images',
                'ordering': ['order', '-is_main'],
            },
        ),
        migrations.CreateModel(
            name='SavedWheelListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_wheels', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listings.wheellisting')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wheellisting',
            index=models.Index(fields=['product_type', 'status'], name='listings_wh_product_be6764_idx'),
        ),
        migrations.AddIndex(
            model_name='wheellisting',
            index=models.Index(fields=['tyre_width', 'tyre_profile', 'diameter'], name='listings_wh_tyre_wi_ae8c89_idx'),
        ),
        migrations.AddIndex(
            model_name='wheellisting',
            index=models.Index(fields=['rim_width', 'diameter', 'rim_pcd'], name='listings_wh_rim_wid_669d9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedwheellisting',
            unique_together={('user', 'listing')},
        ),
    ]
