# Generated by Django 5.0.1 on 2026-08-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0052_wheellisting_wheelimage_savedwheellisting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='gear_subtype',
            field=models.CharField(blank=True, choices=[('helmet:other', 'Kita'), ('helmet:full_face', 'Uždaras (full face)'), ('helmet:integral', 'Integralinis'), ('helmet:modular', 'Atverčiamas (modular)'), ('helmet:open_face', 'Atviras (jet)'), ('helmet:off_road', 'Krosinis / enduro'), ('helmet:dual_sport', 'Dual sport / kelioninis'), ('helmet:half', 'Pusinis'), ('jacket:other', 'Kita'), ('jacket:sport', 'Sportinė'), ('jacket:touring', 'Kelioninė'), ('jacket:city', 'Miesto'), ('jacket:adventure', 'Adventure'), ('jacket:off_road', 'Krosinė'), ('jacket:cruiser', 'Čioperistams'), ('pants:other', 'Kita'), ('pants:sport', 'Sportinės'), ('pants:touring', 'Kelioninės'), ('pants:jeans', 'Džinsai'), ('pants:off_road', 'Krosinės'), ('pants:rain', 'Nuo lietaus'), ('suit:other', 'Kita'), ('suit:one_piece', 'Vientisas'), ('suit:two_piece', 'Dviejų dalių'), ('suit:rain', 'Nuo lietaus'), ('boots:other', 'Kita'), ('boots:sport', 'Sportiniai'), ('boots:touring', 'Kelioniniai'), ('boots:off_road', 'Krosiniai'), ('boots:adventure', 'Adventure'), ('boots:urban', 'Miesto'), ('gloves:other', 'Kita'), ('gloves:sport', 'Sportinės'), ('gloves:touring', 'Kelioninės'), ('gloves:off_road', 'Krosinės'), ('gloves:summer', 'Vasarinės'), ('gloves:winter', 'Žieminės / šildomos'), ('gloves:rain', 'Nuo lietaus'), ('bag:other', 'Kita'), ('bag:tank', 'Ant bako'), ('bag:tail', 'Ant sėdynės'), ('bag:saddle', 'Šoninės'), ('bag:backpack', 'Kuprinė'), ('bag:top_case', 'Bagažinė (top case)'), ('bag:roll', 'Ritininis'), ('protective:other', 'Kita'), ('protective:back', 'Nugaros apsauga'), ('protective:chest', 'Krūtinės apsauga'), ('protective:knee', 'Kelių apsaugos'), ('protective:elbow', 'Alkūnių apsaugos'), ('protective:neck', 'Kaklo apsauga'), ('protective:airbag', 'Oro pagalvės liemenė')], max_length=50),
        ),
    ]
