# Generated by Django 5.0.1 on 2026-08-17 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0055_alter_listing_gear_material_alter_listing_gear_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='trailer_axle_count',
            field=models.CharField(blank=True, choices=[('1', '1 ašis'), ('2', '2 ašys'), ('3', '3 ašys'), ('3plus', '>3 ašių'), ('other', 'Kitas')], default='', max_length=12, verbose_name='Ašių skaičius'),
        ),
        migrations.AddField(
            model_name='listing',
            name='trailer_axle_make',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Ašys (gamintojas)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='trailer_brand_text',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Markė'),
        ),
        migrations.AddField(
            model_name='listing',
            name='trailer_kind',
            field=models.CharField(blank=True, choices=[('trailer', 'Priekaba'), ('semi_trailer', 'Puspriekabė')], default='', max_length=20, verbose_name='Tipas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='trailer_model_text',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Modelis'),
        ),
        migrations.AddField(
            model_name='listing',
            name='trailer_purpose',
            field=models.CharField(blank=True, choices=[('car_trailer', 'Automobilinė priekaba'), ('for_car_transport', 'Automobiliui vežti'), ('car_carrier', 'Automobilvežio'), ('concrete_mixer', 'Betonvežio'), ('flatbed', 'Bortinė'), ('flatbed_tarpaulin', 'Bortinė su tentu'), ('tanker', 'Cisterninė'), ('livestock', 'Gyvuliams vežti'), ('insulated_body', 'Izoterminis kėbulas'), ('swap_body', 'Keičiamas kėbulas'), ('container_chassis', 'Konteinerių važiuoklė'), ('cargo', 'Krovininė'), ('logging', 'Miškavežio'), ('motorcycle_trailer', 'Motociklų priekabos'), ('platform', 'Platforma'), ('refrigerator', 'Šaldytuvas'), ('tipper', 'Savivartė'), ('tarpaulin', 'Tentinė'), ('tractor_trailer', 'Traktoriaus priekaba'), ('touring', 'Turistinė'), ('watercraft', 'Vandens transporto'), ('other', 'Kita')], default='', max_length=40, verbose_name='Paskirtis'),
        ),
        migrations.AddField(
            model_name='listing',
            name='trailer_susp_1',
            field=models.CharField(blank=True, choices=[('mechanical', 'Mechaninė'), ('pneumatic', 'Pneumatinė'), ('pneumatic_liftable', 'Pneumatinė (pakeliama)')], default='', max_length=20, verbose_name='1 ašies pakabos tipas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='trailer_susp_2',
            field=models.CharField(blank=True, choices=[('mechanical', 'Mechaninė'), ('pneumatic', 'Pneumatinė'), ('pneumatic_liftable', 'Pneumatinė (pakeliama)')], default='', max_length=20, verbose_name='2 ašies pakabos tipas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='trailer_susp_3',
            field=models.CharField(blank=True, choices=[('mechanical', 'Mechaninė'), ('pneumatic', 'Pneumatinė'), ('pneumatic_liftable', 'Pneumatinė (pakeliama)')], default='', max_length=20, verbose_name='3 ašies pakabos tipas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='trailer_tyre_pct_1',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='1 ašies padangų likutis %'),
        ),
        migrations.AddField(
            model_name='listing',
            name='trailer_tyre_pct_2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='2 ašies padangų likutis %'),
        ),
        migrations.AddField(
            model_name='listing',
            name='trailer_tyre_pct_3',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='3 ašies padangų likutis %'),
        ),
        migrations.AddField(
            model_name='listing',
            name='trailer_tyre_size_1',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='1 ašies padangų išmatavimai'),
        ),
        migrations.AddField(
            model_name='listing',
            name='trailer_tyre_size_2',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='2 ašies padangų išmatavimai'),
        ),
        migrations.AddField(
            model_name='listing',
            name='trailer_tyre_size_3',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='3 ašies padangų išmatavimai'),
        ),
        migrations.AddField(
            model_name='listing',
            name='trailer_wheel_count',
            field=models.CharField(blank=True, default='', help_text="'2'-'13' arba '13plus'", max_length=8, verbose_name='Bendras ratų skaičius'),
        ),
    ]
