# Generated by Django 5.0.1 on 2026-08-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0056_trailer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='euro_standard',
            field=models.CharField(blank=True, choices=[('euro1', 'Euro 1'), ('euro2', 'Euro 2'), ('euro3', 'Euro 3'), ('euro4', 'Euro 4'), ('euro5', 'Euro 5'), ('euro6', 'Euro 6'), ('euro6d', 'Euro 6d'), ('other', 'Kitas')], max_length=10),
        ),
    ]
