# Generated by Django 5.0.1 on 2026-08-18 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0058_category_tree_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='agri_brand_text',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Markė'),
        ),
        migrations.AddField(
            model_name='listing',
            name='agri_kind',
            field=models.CharField(blank=True, choices=[('implement', 'Padargas'), ('self_propelled', 'Savaeigė')], default='', max_length=20, verbose_name='Padargas / Savaeigė'),
        ),
        migrations.AddField(
            model_name='listing',
            name='agri_model_text',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Modelis'),
        ),
        migrations.AddField(
            model_name='listing',
            name='agri_type',
            field=models.CharField(blank=True, choices=[('akecios', 'Akėčios'), ('bulviu_kasamosios', 'Bulvių kasamosios'), ('buldozeris', 'Buldozeris'), ('ekskavatorius', 'Ekskavatorius'), ('greideris', 'Greideris'), ('grudu_valymo_iranga', 'Grūdų valymo įranga'), ('grudu_dziovinimo_iranga', 'Grūdų džiovinimo įranga'), ('grudu_sandeliavimo_iranga', 'Grūdų sandėliavimo įranga'), ('grudu_transportavimo_iranga', 'Grūdų transportavimo įranga'), ('kombainas', 'Kombainas'), ('krautuvas', 'Krautuvas'), ('kultivatorius', 'Kultivatorius'), ('manipuliatorius', 'Manipuliatorius'), ('mini_ekskavatorius', 'Mini ekskavatorius'), ('motoblokas', 'Motoblokas'), ('traktorius', 'Traktorius'), ('zoliapjove', 'Žoliapjovė'), ('grebliai', 'Grėbliai'), ('lekstiniai_skutikai', 'Lėkštiniai skutikai'), ('meslo_kratytuvai', 'Mėšlo kratytuvai'), ('pasaru_dalytuvai', 'Pašarų dalytuvai'), ('pienininkystes_ir_fermu_irengimai', 'Pienininkystės ir fermų įrengimai'), ('pjaunamosios', 'Pjaunamosios'), ('plugai', 'Plūgai'), ('presai', 'Presai'), ('purkstuvai_pakabinami', 'Purkštuvai pakabinami'), ('purkstuvai_prikabinami', 'Purkštuvai prikabinami'), ('razieniniai_skutikai', 'Ražieniniai skutikai'), ('rinktuvai', 'Rinktuvai'), ('savaeiges_pjaunamosios_smulkintuvai', 'Savaeigės pjaunamosios-smulkintuvai'), ('sejamosios', 'Sėjamosios'), ('sejos_agregatai', 'Sėjos agregatai'), ('smulkintuvai_pjaunamosios', 'Smulkintuvai-pjaunamosios'), ('sniego_peilis', 'Sniego peilis'), ('sodo_ir_parko_technika', 'Sodo ir parko technika'), ('srutu_laistytuvai', 'Srutų laistytuvai'), ('srutu_siurbliai', 'Srutų siurbliai'), ('trasu_barstytuvai', 'Trąšų barstytuvai'), ('vartytuvai', 'Vartytuvai'), ('volai', 'Volai'), ('vyniotuvai', 'Vyniotuvai'), ('kita', 'Kita')], default='', max_length=40, verbose_name='Tipas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='engine_hours',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Motovalandos'),
        ),
        migrations.AddField(
            model_name='listing',
            name='working_width_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Darbinis plotis (m)'),
        ),
    ]
