# Generated by Django 5.0.1 on 2026-08-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0059_agriculture_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='constr_attach_type',
            field=models.CharField(blank=True, choices=[('a_barstytuvai', 'Barstytuvai'), ('a_betono_maisykles', 'Betono maišyklės'), ('a_asfalto_frezos', 'Asfalto frezos'), ('a_gerves_kabliai', 'Gervės / kabliai'), ('a_greideriai', 'Greideriai'), ('a_griebtuvai', 'Griebtuvai'), ('a_hidraulines_zirkles', 'Hidraulinės žirklės'), ('a_hidrauliniai_kujai', 'Hidrauliniai kūjai'), ('a_hidrauliniai_graztai', 'Hidrauliniai gražtai'), ('a_kausai', 'Kaušai'), ('a_kelimo_platformos', 'Kėlimo platformos'), ('a_kranai_manipuliatoriai', 'Kranai / manipuliatoriai'), ('a_paleciu_sakes', 'Palečių šakės'), ('a_sniego_buldozerio_peiliai', 'Sniego (buldozerio) peiliai'), ('a_sniego_putikai', 'Sniego pūtikai'), ('a_pjuklai', 'Pjūklai'), ('a_sijotuvai', 'Sijotuvai'), ('a_streles', 'Strėlės'), ('a_sluotos_sepeciai', 'Šluotos / šepečiai'), ('a_trupintuvai_smulkintuvai', 'Trupintuvai / smulkintuvai'), ('a_viksrai', 'Vikšrai'), ('a_volai', 'Volai'), ('a_kita', 'Kita')], default='', max_length=48, verbose_name='Priedo tipas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='constr_brand_text',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Markė'),
        ),
        migrations.AddField(
            model_name='listing',
            name='constr_drive_type',
            field=models.CharField(blank=True, choices=[('d_mechanine', 'Mechaninė'), ('d_automatine', 'Automatinė'), ('d_elektromechanine', 'Elektromechaninė'), ('d_hidrodinamine', 'Hidrodinaminė'), ('d_hidrostatine', 'Hidrostatinė'), ('d_kita', 'Kita')], default='', max_length=24, verbose_name='Pavaros tipas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='constr_model_text',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Modelis'),
        ),
        migrations.AddField(
            model_name='listing',
            name='constr_type',
            field=models.CharField(blank=True, choices=[('akmens_smulkinimo_masina', 'Akmens smulkinimo mašina'), ('asenizacine_masina', 'Asenizacinė mašina'), ('asfaloto_klojimo_masinos', 'Asfaloto klojimo mašinos'), ('automobilinis_bokstelis', 'Automobilinis bokštelis'), ('automobilinis_kranas', 'Automobilinis kranas'), ('automobilinis_krautuvas', 'Automobilinis krautuvas'), ('betono_gamybos_irenginys', 'Betono gamybos įrenginys'), ('betonvezis', 'Betonvežis'), ('buldozeris', 'Buldozeris'), ('dumperis_savivartis', 'Dumperis (savivartis)'), ('ekskavatorius_krautuvas', 'Ekskavatorius krautuvas'), ('ekskavatorius_griovimo', 'Ekskavatorius griovimo'), ('ekskavatorius_ratinis', 'Ekskavatorius ratinis'), ('ekskavatorius_viksrinis', 'Ekskavatorius vikšrinis'), ('frontalinis_krautuvas', 'Frontalinis krautuvas'), ('greideris', 'Greideris'), ('griebtuvas', 'Griebtuvas'), ('hidraulines_zirkles', 'Hidraulinės žirklės'), ('hidraulinis_graztas', 'Hidraulinis grąžtas'), ('hidraulinis_kujis', 'Hidraulinis kūjis'), ('kausinis_krautuvas', 'Kaušinis krautuvas'), ('kelkrasciu_prieziuros_masinos', 'Kelkraščių priežiūros mašinos'), ('keliu_tiesimo_masina', 'Kelių tiesimo mašina'), ('kompresorius', 'Kompresorius'), ('kranas', 'Kranas'), ('manipuliatorius', 'Manipuliatorius'), ('mini_ekskavatorius', 'Mini ekskavatorius'), ('mini_krautuvas', 'Mini krautuvas'), ('poliakales', 'Poliakalės'), ('skaldykle', 'Skaldyklė'), ('skaldos_rusiavimo_masina', 'Skaldos rūšiavimo mašina'), ('tankinimo_technika', 'Tankinimo technika'), ('vibracines_plokstes', 'Vibracinės plokštės'), ('vibrovolai', 'Vibrovolai'), ('volai', 'Volai'), ('zirklinis_keltuvas', 'Žirklinis keltuvas'), ('zirklinis_krautuvas', 'Žirklinis krautuvas'), ('vibro_masina', 'Vibro mašina'), ('kitas', 'Kitas')], default='', max_length=48, verbose_name='Tipas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Aukštis (m)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ilgis (m)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='width_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Plotis (m)'),
        ),
    ]
