# Generated by Django 5.0.1 on 2026-08-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0060_construction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='aisle_width_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Kelplotis (m²)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='fork_length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Šakių / strėlės ilgis (m)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='lift_height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Max kėlimo aukštis (m)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='load_brand_text',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Markė'),
        ),
        migrations.AddField(
            model_name='listing',
            name='load_energy_source',
            field=models.CharField(blank=True, choices=[('e_akumuliatorinis_elektrinis', 'Akumuliatorinis/elektrinis'), ('e_benzininis_dujinis', 'Benzininis/dujinis'), ('e_benzininis', 'Benzininis'), ('e_dyzelininis_elektrinis', 'Dyzelininis/elektrinis'), ('e_dyzelininis', 'Dyzelininis'), ('e_dujinis', 'Dujinis'), ('e_rankinis_hidraulinis', 'Rankinis/hidraulinis'), ('e_rankinis', 'Rankinis'), ('e_kita', 'Kita')], default='', max_length=32, verbose_name='Energijos šaltinis'),
        ),
        migrations.AddField(
            model_name='listing',
            name='load_type',
            field=models.CharField(blank=True, choices=[('l_konteineriai', 'Konteineriai'), ('l_alkuninis_keltuvas', 'Alkūninis keltuvas'), ('l_ekskavatorinis_krautuvas', 'Ekskavatorinis krautuvas'), ('l_elektriniai_vezimeliai', 'Elektriniai vežimėliai'), ('l_krautuvas', 'Krautuvas'), ('l_paleciu_vyniotuvai', 'Palečių vyniotuvai'), ('l_sandeliavimo_technika', 'Sandėliavimo technika'), ('l_savaeigis_stiebinis_keltuvas', 'Savaeigis stiebinis keltuvas'), ('l_savaeigis_zirklinis_keltuvas', 'Savaeigis žirklinis keltuvas'), ('l_sakinis_krautuvas', 'Šakinis krautuvas'), ('l_teleskopinis_krautuvas', 'Teleskopinis krautuvas'), ('l_universalus_krautuvas', 'Universalus krautuvas'), ('l_kita', 'Kita')], default='', max_length=40, verbose_name='Tipas'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='constr_drive_type',
            field=models.CharField(blank=True, choices=[('d_hidrauline_2_ratu', 'Hidraulinė–2 ratų'), ('d_hidrauline_4x4', 'Hidraulinė–4x4'), ('d_mechanine', 'Mechaninė'), ('d_automatine', 'Automatinė'), ('d_elektromechanine', 'Elektromechaninė'), ('d_hidrodinamine', 'Hidrodinaminė'), ('d_hidrostatine', 'Hidrostatinė'), ('d_kita', 'Kita')], default='', max_length=24, verbose_name='Pavaros tipas'),
        ),
    ]
