# Generated by Django 5.0.1 on 2026-08-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0061_loading_equipment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='forest_brand_text',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Markė'),
        ),
        migrations.AddField(
            model_name='listing',
            name='forest_type',
            field=models.CharField(blank=True, choices=[('f_kitas', 'Kitas'), ('f_gerve', 'Gervė'), ('f_kapokle', 'Kapoklė'), ('f_krumapjove', 'Krūmapjovė'), ('f_manipuliatorius', 'Manipuliatorius'), ('f_medkirte', 'Medkirtė'), ('f_medveze', 'Medvežė'), ('f_misko_traktorius', 'Miško traktorius'), ('f_miskovezio_priekaba', 'Miškovežio priekaba'), ('f_miskovezio_puspriekabe', 'Miškovežio puspriekabė'), ('f_miskovezis', 'Miškovežis'), ('f_motorinis_pjuklas', 'Motorinis pjūklas'), ('f_pjovimo_galvute', 'Pjovimo galvutė'), ('f_savikrove_misko_priekaba', 'Savikrovė Miško priekaba'), ('f_medienos_smulkintuvas', 'Medienos smulkintuvas')], default='', max_length=40, verbose_name='Tipas'),
        ),
    ]
