# Generated by Django 5.0.1 on 2026-08-19 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0063_seed_category_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='b_licence_ok',
            field=models.BooleanField(default=False, verbose_name='Tinka su B kat. teisėmis'),
        ),
        migrations.AddField(
            model_name='listing',
            name='camp_brand_text',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Markė'),
        ),
        migrations.AddField(
            model_name='listing',
            name='camp_type',
            field=models.CharField(blank=True, choices=[('touring_car', 'Turistinis automobilis'), ('towed_house', 'Prikabinamas namelis'), ('other', 'Kita')], default='', max_length=20, verbose_name='Tipas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gearbox_speeds',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Pavarų skaičius'),
        ),
        migrations.AddField(
            model_name='listing',
            name='tyre_condition_pct',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Padangų likutis %'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='defects',
            field=models.CharField(choices=[('none', 'No defects'), ('dented', 'Dented'), ('burned', 'Burned'), ('gearbox_defect', 'Gearbox defect'), ('hail_damage', 'Hail damage'), ('sunken', 'Sunken'), ('engine_defect', 'Engine defect'), ('major_defects', 'Major defects'), ('minor_defects', 'Kiti smulkūs defektai')], default='none', max_length=50),
        ),
    ]
