# Generated by Django 5.0.1 on 2026-08-19 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0065_seed_camping_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='metallic',
            field=models.BooleanField(default=False, verbose_name='Metalikas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='rent_brand_text',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Markė'),
        ),
        migrations.AddField(
            model_name='listing',
            name='rent_price_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nuomos kaina valandai'),
        ),
        migrations.AddField(
            model_name='listing',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('bus', 'Autobusas'), ('water', 'Vandens transportas'), ('moto_rental', 'Motociklų nuoma'), ('passenger_minibus', 'Keleivinis mikroautobusas'), ('cargo_minibus', 'Krovininis mikroautobusas'), ('towed_house', 'Prikabinamas namelis'), ('touring_car', 'Turistinis automobilis'), ('road_train', 'Autotraukinys'), ('agri_constr', 'Žemės ūkio, statybos transportas'), ('truck', 'Sunkvežimis'), ('tractor_unit', 'Vilkikas'), ('warehouse', 'Sandėliavimo, krovimo technika'), ('trailer', 'Priekaba')], default='', max_length=20, verbose_name='Tipas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='seats_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Sėdimų vietų skaičius'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('silver', 'Silver'), ('grey', 'Grey'), ('blue', 'Blue'), ('white', 'White'), ('red', 'Red / Burgundy'), ('green_khaki', 'Green / Khaki'), ('beige', 'Beige'), ('brown_beige', 'Brown / Beige'), ('gold', 'Gold'), ('yellow_gold', 'Yellow / Gold'), ('purple', 'Purple'), ('orange', 'Orange'), ('multicolor', 'Multicolor'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cooling_type',
            field=models.CharField(blank=True, choices=[('air', 'Air-cooled'), ('water', 'Water-cooled'), ('oil', 'Oil-cooled'), ('mixed', 'Mixed cooling')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='doors',
            field=models.CharField(blank=True, choices=[('2/3', '2/3 doors'), ('4/5', '4/5 doors'), ('6/7', '6/7 doors')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='motorcycle_type',
            field=models.CharField(blank=True, choices=[('sport', 'Sport'), ('cruiser', 'Cruiser'), ('touring', 'Touring'), ('enduro', 'Enduro'), ('motocross', 'Motocross'), ('chopper', 'Chopper'), ('naked', 'Naked'), ('scooter', 'Scooter'), ('moped', 'Moped'), ('atv', 'ATV / Quad'), ('trike', 'Trike'), ('kart', 'Kart'), ('mini_bike', 'Mini bike'), ('snowmobile', 'Snowmobile'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='trailer_kind',
            field=models.CharField(blank=True, choices=[('trailer', 'Priekaba'), ('semi_trailer', 'Puspriekabė'), ('light_car_trailer', 'Lengvojo automobilio priekaba')], default='', max_length=20, verbose_name='Tipas'),
        ),
    ]
