# Generated by Django 5.0.1 on 2026-08-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0067_seed_rental_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='service_type',
            field=models.CharField(blank=True, choices=[('alarm_install', 'Apsaugos sistemų montavimas'), ('car_buying', 'Automobilių supirkimas'), ('service_equipment', 'Autoservisų įrangos aptarnavimas'), ('parts_buying', 'Dalių supirkimas'), ('lpg_install', 'Dujų įrangos montavimas'), ('audio_install', 'Garso aparatūros montavimas'), ('catalyst_buying', 'Katalizatorių supirkimas'), ('passenger_transport', 'Keleivių vežimas'), ('other_services', 'Kitos paslaugos'), ('cargo_transport', 'Krovinių gabenimas'), ('car_repair', 'Lengvųjų automobilių remontas'), ('moto_repair', 'Motociklų motorolerių remontas'), ('moto_buying', 'Motociklų supirkimas'), ('tyre_buying', 'Padangų supirkimas'), ('roadside_assistance', 'Pagalba kelyje'), ('washing', 'Plovimo paslaugos'), ('rim_buying', 'Ratlankių supirkimas'), ('tyre_service', 'Ratų montavimas, padangų remontas'), ('glass_tinting', 'Stiklų tonavimas, keitimas'), ('heavy_repair', 'Sunkiosios technikos remontas'), ('truck_buying', 'Sunkvežimių supirkimas'), ('tuning', 'Tiuning'), ('agri_buying', 'Žemės ūkio technikos supirkimas'), ('agri_repair', 'Žemės ūkio technikos remontas')], default='', max_length=25, verbose_name='Paslaugos tipas'),
        ),
    ]
