# Generated by Django 5.0.1 on 2026-08-19 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0069_seed_services_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='elec_brand_text',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Gamintojas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='elec_channels',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Kanalų skaičius'),
        ),
        migrations.AddField(
            model_name='listing',
            name='elec_type',
            field=models.CharField(blank=True, choices=[('car_alarm', 'Automobilių signalizacija'), ('cd_player', 'CD grotuvas'), ('cd_changer', 'CD keitiklis'), ('cd_mp3_player', 'CD/MP3 grotuvas'), ('dvd_player', 'DVD grotuvas'), ('speaker', 'Garsiakalbis'), ('amplifier', 'Garso stiprintuvas'), ('player_with_nav', 'Grotuvas su navigacija'), ('capacitors', 'Kondensatoriai'), ('cables', 'Laidai/Laidų komplektai'), ('monitors', 'Monitoriai'), ('mc_radio', 'MC automagnetola'), ('moto_alarm', 'Motociklų signalizacija'), ('multimedia', 'Multimedia'), ('agri_navigation', 'Navigacija žemės ūkio technikai'), ('navigation_gps', 'Navigacija, GPS'), ('parking_system', 'Parkavimo sistema'), ('cb_radio', 'Radijas/CB radijo stotelės'), ('dashcam', 'Video registratorius'), ('subwoofer', 'Žemų dažnių garsiakalbis'), ('other', 'Kita')], default='', max_length=20, verbose_name='Tipas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='power_w',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Galingumas W'),
        ),
    ]
