# Generated by Django 5.0.1 on 2026-08-19 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0071_seed_electronics_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='battery_ah',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Baterijos talpa, Ah'),
        ),
        migrations.AddField(
            model_name='listing',
            name='battery_pct',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Baterijos talpos likutis, %'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bike_brand_text',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Gamintojas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bike_type',
            field=models.CharField(blank=True, choices=[('e_scooter', 'Elektrinis paspirtukas'), ('e_board', 'Elektrinis riedis'), ('e_bike', 'Elektrinis dviratis')], default='', max_length=15, verbose_name='Tipas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='charge_time_h',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Įkrovimo laikas, val.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='max_incline_deg',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='Įveikiama įkalnė, °'),
        ),
        migrations.AddField(
            model_name='listing',
            name='max_speed_kmh',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Maksimalus greitis, km/h'),
        ),
        migrations.AddField(
            model_name='listing',
            name='range_km',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rida su vienu įkrovimu, km'),
        ),
        migrations.AddField(
            model_name='listing',
            name='tyre_kind',
            field=models.CharField(blank=True, choices=[('solid', 'Pilnavidurės'), ('pneumatic', 'Pripučiamos')], default='', max_length=10, verbose_name='Padangų tipas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='wheel_diameter_in',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ratų skersmuo, coliais'),
        ),
    ]
