# Generated by Django 5.0.1 on 2026-08-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0073_seed_bicycles_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheellisting',
            name='fits_brands',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wheellisting',
            name='rim_feat_bent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wheellisting',
            name='rim_feat_chromed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wheellisting',
            name='rim_feat_original',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wheellisting',
            name='rim_feat_with_tyres',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wheellisting',
            name='rim_material',
            field=models.CharField(blank=True, choices=[('accessory', 'Accessories'), ('alloy', 'Alloy'), ('steel', 'Stamped steel'), ('forged', 'Forged'), ('spare', 'Spare wheel'), ('hubcap', 'Wheel covers'), ('centercap', 'Centre caps')], max_length=16),
        ),
    ]
