# Generated by Django 5.0.1 on 2026-08-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0076_seed_legacy_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='Raktas')),
                ('name', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('has_models', models.BooleanField(default=False, verbose_name='Turi modelių kaskadą')),
                ('order', models.IntegerField(default=0, verbose_name='Eiliškumas')),
            ],
            options={
                'verbose_name': 'Markių šeima',
                'verbose_name_plural': 'Markių šeimos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Top markė'),
        ),
        migrations.AddField(
            model_name='brand',
            name='legacy_gear',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified', to='listings.gearbrand'),
        ),
        migrations.AddField(
            model_name='brand',
            name='legacy_moto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified', to='listings.motorcyclebrand'),
        ),
        migrations.AddField(
            model_name='brand',
            name='legacy_truck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified', to='listings.truckbrand'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/', verbose_name='Logotipas'),
        ),
        migrations.AddField(
            model_name='brand',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Eiliškumas'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='listings.vehicletype'),
        ),
        migrations.AddField(
            model_name='brand',
            name='scopes',
            field=models.ManyToManyField(blank=True, related_name='brands', to='listings.brandscope', verbose_name='Šeimos'),
        ),
    ]
