# Generated by Django 5.0.1 on 2026-08-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0077_brand_scopes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('times_used', models.PositiveIntegerField(default=1, verbose_name='Kiek kartų įvesta')),
                ('status', models.CharField(choices=[('new', 'Naujas'), ('approved', 'Patvirtinta'), ('rejected', 'Atmesta')], default='new', max_length=10, verbose_name='Būsena')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('approved_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_suggestions', to='listings.brand', verbose_name='Sukurta markė')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='listings.brandscope', verbose_name='Šeima')),
            ],
            options={
                'verbose_name': 'Markės pasiūlymas',
                'verbose_name_plural': 'Markių pasiūlymai',
                'ordering': ['-times_used', 'name'],
                'unique_together': {('scope', 'name')},
            },
        ),
    ]
