# Generated by Django 5.0.1 on 2026-08-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0080_unify_moto_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('brand', 'name'), ('brand', 'slug')},
        ),
    ]
