# Generated by Django 5.0.1 on 2026-08-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0081_model_unique_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='h_lg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_lg',
            field=models.ImageField(blank=True, null=True, upload_to='listings/derived/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_lg_webp',
            field=models.ImageField(blank=True, null=True, upload_to='listings/derived/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_sm',
            field=models.ImageField(blank=True, null=True, upload_to='listings/derived/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_sm_webp',
            field=models.ImageField(blank=True, null=True, upload_to='listings/derived/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='w_lg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
