# Generated by Django 5.0.1 on 2026-08-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0082_listingimage_h_lg_listingimage_image_lg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='notify_onsite',
            field=models.BooleanField(default=True),
        ),
    ]
