# Generated by Django 5.0.1 on 2026-08-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0083_savedsearch_notify_onsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
