# Generated by Django 5.0.1 on 2026-08-22 20:02

from django.db import migrations, models


def uzpildyti_kainas(apps, schema_editor):
    """Seniems įrašams įrašom dabartinę kainą.

    Kitaip jau įsiminti skelbimai amžinai liktų be atskaitos taško ir
    „kaina krito" žyma jiems niekada nesuveiktų.
    """
    SavedListing = apps.get_model('listings', 'SavedListing')
    for saved in SavedListing.objects.select_related('listing').filter(price_at_save__isnull=True):
        saved.price_at_save = saved.listing.price
        saved.save(update_fields=['price_at_save'])


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0084_valiuta_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlisting',
            name='price_at_save',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(uzpildyti_kainas, migrations.RunPython.noop),
    ]
