# Generated by Django 5.0.1 on 2026-08-23 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0085_pranesimai_apie_kainos_kritima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('estate', 'Estate/Wagon'), ('minivan', 'Minivan'), ('suv', 'SUV/Crossover'), ('coupe', 'Coupe'), ('commercial', 'Commercial'), ('convertible', 'Convertible'), ('limousine', 'Limousine'), ('pickup', 'Pickup'), ('minibus', 'Minibus'), ('truck', 'Truck/Van'), ('other', 'Other')], max_length=50, verbose_name='Kėbulo tipas'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='doors',
            field=models.CharField(blank=True, choices=[('2/3', '2/3 doors'), ('4/5', '4/5 doors'), ('6/7', '6/7 doors')], max_length=10, verbose_name='Durų skaičius'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.fueltype', verbose_name='Kuro tipas'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='transmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.transmission', verbose_name='Pavarų dėžė'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='vin',
            field=models.CharField(blank=True, max_length=17, verbose_name='VIN kodas'),
        ),
    ]
