# Generated by Django 5.0.1 on 2026-08-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0086_laukų_pavadinimai_lt'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cylinders',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('16', '16')], max_length=2, verbose_name='Cilindrų skaičius'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gear_count',
            field=models.CharField(blank=True, choices=[('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='Pavarų skaičius'),
        ),
        migrations.AddField(
            model_name='listing',
            name='manufacturer_warranty',
            field=models.BooleanField(default=False, verbose_name='Gamintojo garantija'),
        ),
        migrations.AddField(
            model_name='listing',
            name='sdk_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='SDK kodas'),
        ),
    ]
