# Generated by Django 5.0.1 on 2026-08-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0087_etalono_laukai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rim_size',
            field=models.CharField(blank=True, choices=[('13', 'R13'), ('14', 'R14'), ('15', 'R15'), ('16', 'R16'), ('17', 'R17'), ('18', 'R18'), ('19', 'R19'), ('20', 'R20'), ('21', 'R21'), ('22', 'R22'), ('23', 'R23'), ('24', 'R24')], max_length=5, verbose_name='Ratlankiai'),
        ),
    ]
