# Generated by Django 5.0.1 on 2026-08-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0090_savybiu_dublikatai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('estate', 'Estate/Wagon'), ('minivan', 'Minivan'), ('suv', 'SUV/Crossover'), ('coupe', 'Coupe'), ('commercial', 'Commercial'), ('convertible', 'Convertible'), ('limousine', 'Limousine'), ('pickup', 'Pickup'), ('minibus', 'Minibus'), ('truck', 'Truck/Van'), ('kombi_minibus', 'Kombi mikroautobusas'), ('homemade', 'Savadarbis auto'), ('other', 'Other')], max_length=50, verbose_name='Kėbulo tipas'),
        ),
    ]
