# Generated by Django 5.0.1 on 2026-08-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0091_kebulo_tipai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='sdk_code',
        ),
    ]
