# Generated by Django 5.0.1 on 2026-08-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0093_pranesimai_apie_skelbimus'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlisting',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
