# Generated by Django 5.0.1 on 2026-08-24 11:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0094_savedlisting_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerziuretasSkelbimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perziureta', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perziuros', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perziureti_skelbimai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Peržiūrėtas skelbimas',
                'verbose_name_plural': 'Peržiūrėti skelbimai',
                'ordering': ['-perziureta'],
                'indexes': [models.Index(fields=['user', '-perziureta'], name='listings_pe_user_id_2ca35e_idx')],
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
