# Generated by Django 5.0.1 on 2026-08-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0095_perziuretasskelbimas'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='koordinates_tikslios',
            field=models.BooleanField(default=False),
        ),
    ]
