# Generated by Django 5.2.17 on 2026-09-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "listings",
            "0097_alter_listing_country_alter_listing_origin_country_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
