# Generated by Django 5.2.17 on 2026-09-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0100_valiuta_pagal_sali"),
    ]

    operations = [
        migrations.AlterField(
            model_name="truck",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound (£)"),
                ],
                default="EUR",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="trucksalesrecord",
            name="currency",
            field=models.CharField(default="EUR", max_length=3),
        ),
    ]
