# Generated by Django 5.2.17 on 2026-09-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0101_alter_truck_currency_alter_trucksalesrecord_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="axle_count",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("more", ">3"),
                    ("other", "Kitas"),
                ],
                default="",
                max_length=10,
                verbose_name="Ašių skaičius",
            ),
        ),
    ]
