# Generated by Django 5.2.17 on 2026-09-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0104_alter_wheellisting_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
