# Generated by Django 5.0.1 on 2026-05-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AddField(
            model_name='pageview',
            name='country_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
