# Generated by Django 5.0.1 on 2026-05-27 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_pageview_country_pageview_country_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='bot_reason',
            field=models.CharField(blank=True, default='', help_text='empty_ua | ua_pattern | path_scan | behavior', max_length=20),
        ),
        migrations.AddField(
            model_name='pageview',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pageview',
            name='referrer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pageview',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['is_bot', 'created_at'], name='analytics_p_is_bot_8ecec0_idx'),
        ),
    ]
