# Generated by Django 5.2.17 on 2026-09-14 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_visitorhit_ip_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="visitorhit",
            new_name="analytics_v_is_bot_cf95cb_idx",
            old_name="analytics_p_is_bot_8ecec0_idx",
        ),
        migrations.AddIndex(
            model_name="visitorhit",
            index=models.Index(
                fields=["ip_hash", "created_at"], name="analytics_v_ip_hash_8bcea3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorhit",
            index=models.Index(
                fields=["country", "created_at"], name="analytics_v_country_fdda5b_idx"
            ),
        ),
    ]
