# Generated by Django 5.0.1 on 2026-05-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_message_image_alter_message_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_lang', models.CharField(help_text="ISO kalbos kodas: 'en', 'de', 'es', 'lt', etc.", max_length=10)),
                ('translated_text', models.TextField()),
                ('detected_source_lang', models.CharField(blank=True, help_text="Google'o auto-detected šaltinio kalba", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='conversations.message')),
            ],
            options={
                'verbose_name': 'Message Translation',
                'verbose_name_plural': 'Message Translations',
                'indexes': [models.Index(fields=['message', 'target_lang'], name='conversatio_message_38267f_idx')],
                'unique_together': {('message', 'target_lang')},
            },
        ),
    ]
