# Generated by Django 5.0.1 on 2026-10-02 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversationtranslation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='kalba_originalo',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.CreateModel(
            name='PokalbioPerziura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perziurejo_el_pastas', models.CharField(max_length=254)),
                ('pokalbio_nr', models.PositiveIntegerField()),
                ('priezastis', models.CharField(choices=[('gincas', 'Ginčas'), ('grazinimas', 'Grąžinimas'), ('sukciavimas', 'Pranešimas apie sukčiavimą'), ('teisine', 'Teisinė užklausa'), ('kita', 'Kita')], max_length=20)),
                ('paaiskinimas', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('kada', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dalyviai', models.ManyToManyField(blank=True, related_name='pokalbiu_perziuros', to=settings.AUTH_USER_MODEL)),
                ('perziurejo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atliktos_pokalbiu_perziuros', to=settings.AUTH_USER_MODEL)),
                ('pokalbis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perziuros', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Pokalbio peržiūra',
                'verbose_name_plural': 'Pokalbių peržiūros (žurnalas)',
                'ordering': ['-kada'],
            },
        ),
    ]
